<?php
/**
 * Casualties
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  Hubsante\Model\emsi
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Hubsante\Model\emsi;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Casualties model.
 *
 * @package Hubsante\Model\emsi
 * @author  OpenAPI Generator team
 */

class Casualties 
{
        /**
     * Le champ doit être renseigné mais peut ne pas être interprété
     *
     * @var string|null
     * @SerializedName("CONTEXT")
     * @Type("string")
    */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $cONTEXT = null;

    /**
     * Optionnel
     *
     * @var \DateTime|null
     * @SerializedName("DATIME")
     * @Type("DateTime")
    */
    #[Assert\Type("\DateTime")]
    #[Assert\Regex("/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}[\\-+]\\d{2}:\\d{2}$/")]
    protected ?\DateTime $dATIME = null;

    /**
     * Optionnel
     *
     * @var int|null
     * @SerializedName("DECONT")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $dECONT = null;

    /**
     * Optionnel, Triage victime au sens EMSI
     *
     * @var int|null
     * @SerializedName("TRIAGERED")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $tRIAGERED = null;

    /**
     * Optionnel
     *
     * @var int|null
     * @SerializedName("TRIAGEYELLOW")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $tRIAGEYELLOW = null;

    /**
     * Optionnel
     *
     * @var int|null
     * @SerializedName("TRIAGEGREEN")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $tRIAGEGREEN = null;

    /**
     * Optionnel
     *
     * @var int|null
     * @SerializedName("TRIAGEBLACK")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $tRIAGEBLACK = null;

    /**
     * Optionnel
     *
     * @var int|null
     * @SerializedName("MISSING")
     * @Type("int")
    */
    #[Assert\Type("int")]
    protected ?int $mISSING = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->cONTEXT = array_key_exists('cONTEXT', $data) ? $data['cONTEXT'] : $this->cONTEXT;
            $this->dATIME = array_key_exists('dATIME', $data) ? $data['dATIME'] : $this->dATIME;
            $this->dECONT = array_key_exists('dECONT', $data) ? $data['dECONT'] : $this->dECONT;
            $this->tRIAGERED = array_key_exists('tRIAGERED', $data) ? $data['tRIAGERED'] : $this->tRIAGERED;
            $this->tRIAGEYELLOW = array_key_exists('tRIAGEYELLOW', $data) ? $data['tRIAGEYELLOW'] : $this->tRIAGEYELLOW;
            $this->tRIAGEGREEN = array_key_exists('tRIAGEGREEN', $data) ? $data['tRIAGEGREEN'] : $this->tRIAGEGREEN;
            $this->tRIAGEBLACK = array_key_exists('tRIAGEBLACK', $data) ? $data['tRIAGEBLACK'] : $this->tRIAGEBLACK;
            $this->mISSING = array_key_exists('mISSING', $data) ? $data['mISSING'] : $this->mISSING;
        }
    }

    /**
     * Gets cONTEXT.
     *
     * @return string|null
     */
    public function getCONTEXT(): ?string
    {
        return $this->cONTEXT;
    }

    /**
    * Sets cONTEXT.
    *
    * @param string|null $cONTEXT  Le champ doit être renseigné mais peut ne pas être interprété
    *
    * @return $this
    */
    public function setCONTEXT(?string $cONTEXT): self
    {
        $this->cONTEXT = $cONTEXT;

        return $this;
    }




    /**
     * Gets dATIME.
     *
     * @return \DateTime|null
     */
    public function getDATIME(): ?\DateTime
    {
        return $this->dATIME;
    }

    /**
    * Sets dATIME.
    *
    * @param \DateTime|null $dATIME  Optionnel
    *
    * @return $this
    */
    public function setDATIME(?\DateTime $dATIME = null): self
    {
        $this->dATIME = $dATIME;

        return $this;
    }




    /**
     * Gets dECONT.
     *
     * @return int|null
     */
    public function getDECONT(): ?int
    {
        return $this->dECONT;
    }

    /**
    * Sets dECONT.
    *
    * @param int|null $dECONT  Optionnel
    *
    * @return $this
    */
    public function setDECONT(?int $dECONT = null): self
    {
        $this->dECONT = $dECONT;

        return $this;
    }




    /**
     * Gets tRIAGERED.
     *
     * @return int|null
     */
    public function getTRIAGERED(): ?int
    {
        return $this->tRIAGERED;
    }

    /**
    * Sets tRIAGERED.
    *
    * @param int|null $tRIAGERED  Optionnel, Triage victime au sens EMSI
    *
    * @return $this
    */
    public function setTRIAGERED(?int $tRIAGERED = null): self
    {
        $this->tRIAGERED = $tRIAGERED;

        return $this;
    }




    /**
     * Gets tRIAGEYELLOW.
     *
     * @return int|null
     */
    public function getTRIAGEYELLOW(): ?int
    {
        return $this->tRIAGEYELLOW;
    }

    /**
    * Sets tRIAGEYELLOW.
    *
    * @param int|null $tRIAGEYELLOW  Optionnel
    *
    * @return $this
    */
    public function setTRIAGEYELLOW(?int $tRIAGEYELLOW = null): self
    {
        $this->tRIAGEYELLOW = $tRIAGEYELLOW;

        return $this;
    }




    /**
     * Gets tRIAGEGREEN.
     *
     * @return int|null
     */
    public function getTRIAGEGREEN(): ?int
    {
        return $this->tRIAGEGREEN;
    }

    /**
    * Sets tRIAGEGREEN.
    *
    * @param int|null $tRIAGEGREEN  Optionnel
    *
    * @return $this
    */
    public function setTRIAGEGREEN(?int $tRIAGEGREEN = null): self
    {
        $this->tRIAGEGREEN = $tRIAGEGREEN;

        return $this;
    }




    /**
     * Gets tRIAGEBLACK.
     *
     * @return int|null
     */
    public function getTRIAGEBLACK(): ?int
    {
        return $this->tRIAGEBLACK;
    }

    /**
    * Sets tRIAGEBLACK.
    *
    * @param int|null $tRIAGEBLACK  Optionnel
    *
    * @return $this
    */
    public function setTRIAGEBLACK(?int $tRIAGEBLACK = null): self
    {
        $this->tRIAGEBLACK = $tRIAGEBLACK;

        return $this;
    }




    /**
     * Gets mISSING.
     *
     * @return int|null
     */
    public function getMISSING(): ?int
    {
        return $this->mISSING;
    }

    /**
    * Sets mISSING.
    *
    * @param int|null $mISSING  Optionnel
    *
    * @return $this
    */
    public function setMISSING(?int $mISSING = null): self
    {
        $this->mISSING = $mISSING;

        return $this;
    }



}


