<?php
/**
 * Rgeo
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  Hubsante\Model\emsi
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Hubsante\Model\emsi;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Rgeo model.
 *
 * @package Hubsante\Model\emsi
 * @author  OpenAPI Generator team
 */

class Rgeo 
{
        /**
     * Horaire associé à l&#39;arrivée de la ressource sur la position. En fonction du TYPE de position, peut indiquer un horaire de relevé de position, un horaire cible d&#39;arrivée.
     *
     * @var \DateTime|null
     * @SerializedName("DATIME")
     * @Type("DateTime")
    */
    #[Assert\Type("\DateTime")]
    #[Assert\Regex("/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}[\\-+]\\d{2}:\\d{2}$/")]
    protected ?\DateTime $dATIME = null;

    /**
     * Type de position indiqué pour la ressource : - ASP : assembly point. Point de rassemblement par défaut des ressources liées à la mission. Peut ne pas être utilisé - CUR : current. Position actualisée de la ressource permettant le suivi géolocalisé des véhicules notamment. Peut ne pas être utilisé - INC : incident. Consigne relative au positionnement de la ressource sur le lieu d&#39;intervention. Peut ne pas être utilisé - STG : staging point. Consigne relative au stationnement des véhicules ou au stockage du matériel par exemple. peut ne pas être utilisé - TGT : targer location. Si renseigné, doit être cohérent avec la position renseignée pour la mission. Plusieurs positions du même type avec des horodatages différents peuvent être fournies.
     *
     * @var string|null
     * @SerializedName("TYPE")
     * @Type("string")
    */
    #[Assert\NotNull]
    #[Assert\Choice(['ASP', 'CUR', 'INC', 'STG', 'TGT'])]
    #[Assert\Type("string")]
    protected ?string $tYPE = null;

    /**
     * Permet de rajouter des précisions sur la localisation de la ressource transmise
     *
     * @var string|null
     * @SerializedName("FREETEXT")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $fREETEXT = null;

    /**
     * Identifiant unique de la position dans le système du partenaire
     *
     * @var string|null
     * @SerializedName("ID")
     * @Type("string")
    */
    #[Assert\Type("string")]
    protected ?string $iD = null;

    /**
     * @var Position[]|null
     * @SerializedName("POSITION")
     * @Type("array<Hubsante\Model\emsi\Position>")
    */
    #[Assert\All([
        new Assert\Type("Hubsante\Model\emsi\Position"),
    ])]
    protected ?array $pOSITION = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->dATIME = array_key_exists('dATIME', $data) ? $data['dATIME'] : $this->dATIME;
            $this->tYPE = array_key_exists('tYPE', $data) ? $data['tYPE'] : $this->tYPE;
            $this->fREETEXT = array_key_exists('fREETEXT', $data) ? $data['fREETEXT'] : $this->fREETEXT;
            $this->iD = array_key_exists('iD', $data) ? $data['iD'] : $this->iD;
            $this->pOSITION = array_key_exists('pOSITION', $data) ? $data['pOSITION'] : $this->pOSITION;
        }
    }

    /**
     * Gets dATIME.
     *
     * @return \DateTime|null
     */
    public function getDATIME(): ?\DateTime
    {
        return $this->dATIME;
    }

    /**
    * Sets dATIME.
    *
    * @param \DateTime|null $dATIME  Horaire associé à l'arrivée de la ressource sur la position. En fonction du TYPE de position, peut indiquer un horaire de relevé de position, un horaire cible d'arrivée.
    *
    * @return $this
    */
    public function setDATIME(?\DateTime $dATIME = null): self
    {
        $this->dATIME = $dATIME;

        return $this;
    }




    /**
     * Gets tYPE.
     *
     * @return string|null
     */
    public function getTYPE(): ?string
    {
        return $this->tYPE;
    }

    /**
    * Sets tYPE.
    *
    * @param string|null $tYPE  Type de position indiqué pour la ressource : - ASP : assembly point. Point de rassemblement par défaut des ressources liées à la mission. Peut ne pas être utilisé - CUR : current. Position actualisée de la ressource permettant le suivi géolocalisé des véhicules notamment. Peut ne pas être utilisé - INC : incident. Consigne relative au positionnement de la ressource sur le lieu d'intervention. Peut ne pas être utilisé - STG : staging point. Consigne relative au stationnement des véhicules ou au stockage du matériel par exemple. peut ne pas être utilisé - TGT : targer location. Si renseigné, doit être cohérent avec la position renseignée pour la mission. Plusieurs positions du même type avec des horodatages différents peuvent être fournies.
    *
    * @return $this
    */
    public function setTYPE(?string $tYPE): self
    {
        $this->tYPE = $tYPE;

        return $this;
    }




    /**
     * Gets fREETEXT.
     *
     * @return string|null
     */
    public function getFREETEXT(): ?string
    {
        return $this->fREETEXT;
    }

    /**
    * Sets fREETEXT.
    *
    * @param string|null $fREETEXT  Permet de rajouter des précisions sur la localisation de la ressource transmise
    *
    * @return $this
    */
    public function setFREETEXT(?string $fREETEXT = null): self
    {
        $this->fREETEXT = $fREETEXT;

        return $this;
    }




    /**
     * Gets iD.
     *
     * @return string|null
     */
    public function getID(): ?string
    {
        return $this->iD;
    }

    /**
    * Sets iD.
    *
    * @param string|null $iD  Identifiant unique de la position dans le système du partenaire
    *
    * @return $this
    */
    public function setID(?string $iD = null): self
    {
        $this->iD = $iD;

        return $this;
    }




    /**
     * Gets pOSITION.
     *
     * @return Position[]|null
     */
    public function getPOSITION(): ?array
    {
        return $this->pOSITION;
    }

    /**
    * Sets pOSITION.
    *
    * @param Position[]|null $pOSITION
    *
    * @return $this
    */
    public function setPOSITION(?array $pOSITION = null): self
    {
        $this->pOSITION = $pOSITION;

        return $this;
    }



}


