package com.hubsante.model.report;

public enum ErrorCode {
    NOT_ALLOWED_CONTENT_TYPE,
    UNRECOGNIZED_MESSAGE_FORMAT,
    INVALID_MESSAGE,
    SENDER_INCONSISTENCY,
    DELIVERY_MODE_INCONSISTENCY,
    EXPIRED_MESSAGE_BEFORE_ROUTING,
    DEAD_LETTER_QUEUED
}
