<?php
/**
 * Resource
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hubsante
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hubsante\Model\resources.info;

use \ArrayAccess;
use \Hubsante\ObjectSerializer;

/**
 * Resource Class Doc Comment
 *
 * @category Class
 * @package  Hubsante
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Resource implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'resource';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'datetime' => '\DateTime',
        'resourceId' => 'string',
        'requestId' => 'string',
        'missionId' => 'string',
        'orgId' => 'string',
        'patientId' => 'string',
        'centerName' => 'string',
        'vehicleType' => 'string',
        'name' => 'string',
        'centerCity' => 'string',
        'team' => '\Hubsante\Model\resources.info\Team',
        'state' => '\Hubsante\Model\resources.info\State[]',
        'contact' => '\Hubsante\Model\resources.info\Contact',
        'freetext' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'datetime' => 'date-time',
        'resourceId' => null,
        'requestId' => null,
        'missionId' => null,
        'orgId' => null,
        'patientId' => null,
        'centerName' => null,
        'vehicleType' => null,
        'name' => null,
        'centerCity' => null,
        'team' => null,
        'state' => null,
        'contact' => null,
        'freetext' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'datetime' => false,
        'resourceId' => false,
        'requestId' => false,
        'missionId' => false,
        'orgId' => false,
        'patientId' => false,
        'centerName' => false,
        'vehicleType' => false,
        'name' => false,
        'centerCity' => false,
        'team' => false,
        'state' => false,
        'contact' => false,
        'freetext' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'datetime' => 'datetime',
        'resourceId' => 'resourceId',
        'requestId' => 'requestId',
        'missionId' => 'missionId',
        'orgId' => 'orgId',
        'patientId' => 'patientId',
        'centerName' => 'centerName',
        'vehicleType' => 'vehicleType',
        'name' => 'name',
        'centerCity' => 'centerCity',
        'team' => 'team',
        'state' => 'state',
        'contact' => 'contact',
        'freetext' => 'freetext'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'datetime' => 'setDatetime',
        'resourceId' => 'setResourceId',
        'requestId' => 'setRequestId',
        'missionId' => 'setMissionId',
        'orgId' => 'setOrgId',
        'patientId' => 'setPatientId',
        'centerName' => 'setCenterName',
        'vehicleType' => 'setVehicleType',
        'name' => 'setName',
        'centerCity' => 'setCenterCity',
        'team' => 'setTeam',
        'state' => 'setState',
        'contact' => 'setContact',
        'freetext' => 'setFreetext'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'datetime' => 'getDatetime',
        'resourceId' => 'getResourceId',
        'requestId' => 'getRequestId',
        'missionId' => 'getMissionId',
        'orgId' => 'getOrgId',
        'patientId' => 'getPatientId',
        'centerName' => 'getCenterName',
        'vehicleType' => 'getVehicleType',
        'name' => 'getName',
        'centerCity' => 'getCenterCity',
        'team' => 'getTeam',
        'state' => 'getState',
        'contact' => 'getContact',
        'freetext' => 'getFreetext'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const VEHICLE_TYPE_AASC = 'AASC';
    public const VEHICLE_TYPE_AASC_VLSC = 'AASC.VLSC';
    public const VEHICLE_TYPE_AASC_VPSP = 'AASC.VPSP';
    public const VEHICLE_TYPE_AASC_AUTRESC = 'AASC.AUTRESC';
    public const VEHICLE_TYPE_AUTREVEC = 'AUTREVEC';
    public const VEHICLE_TYPE_AUTREVEC_APIED = 'AUTREVEC.APIED';
    public const VEHICLE_TYPE_AUTREVEC_AVION = 'AUTREVEC.AVION';
    public const VEHICLE_TYPE_AUTREVEC_PERSO = 'AUTREVEC.PERSO';
    public const VEHICLE_TYPE_AUTREVEC_TAXI = 'AUTREVEC.TAXI';
    public const VEHICLE_TYPE_AUTREVEC_TRAIN = 'AUTREVEC.TRAIN';
    public const VEHICLE_TYPE_AUTREVEC_TRANSP = 'AUTREVEC.TRANSP';
    public const VEHICLE_TYPE_AUTREVEC_AUTRE = 'AUTREVEC.AUTRE';
    public const VEHICLE_TYPE_AUTREVEC_AUTRETRA = 'AUTREVEC.AUTRETRA';
    public const VEHICLE_TYPE_FSI = 'FSI';
    public const VEHICLE_TYPE_FSI_HELIFSI = 'FSI.HELIFSI';
    public const VEHICLE_TYPE_FSI_VLFSI = 'FSI.VLFSI';
    public const VEHICLE_TYPE_FSI_FFSI = 'FSI.FFSI';
    public const VEHICLE_TYPE_FSI_VHFSI = 'FSI.VHFSI';
    public const VEHICLE_TYPE_LIB = 'LIB';
    public const VEHICLE_TYPE_LIB_MEDV = 'LIB.MEDV';
    public const VEHICLE_TYPE_LIB_INF = 'LIB.INF';
    public const VEHICLE_TYPE_LIB_AUTREPRO = 'LIB.AUTREPRO';
    public const VEHICLE_TYPE_SIS = 'SIS';
    public const VEHICLE_TYPE_SIS_DRAGON = 'SIS.DRAGON';
    public const VEHICLE_TYPE_SIS_AVSC = 'SIS.AVSC';
    public const VEHICLE_TYPE_SIS_FEUSIS = 'SIS.FEUSIS';
    public const VEHICLE_TYPE_SIS_GRIMP = 'SIS.GRIMP';
    public const VEHICLE_TYPE_SIS_NAVISIS = 'SIS.NAVISIS';
    public const VEHICLE_TYPE_SIS_PCSIS = 'SIS.PCSIS';
    public const VEHICLE_TYPE_SIS_SRSIS = 'SIS.SRSIS';
    public const VEHICLE_TYPE_SIS_VCH = 'SIS.VCH';
    public const VEHICLE_TYPE_SIS_VLCG = 'SIS.VLCG';
    public const VEHICLE_TYPE_SIS_VLISP = 'SIS.VLISP';
    public const VEHICLE_TYPE_SIS_VLMSP = 'SIS.VLMSP';
    public const VEHICLE_TYPE_SIS_VLSIS = 'SIS.VLSIS';
    public const VEHICLE_TYPE_SIS_VPL = 'SIS.VPL';
    public const VEHICLE_TYPE_SIS_VPMA = 'SIS.VPMA';
    public const VEHICLE_TYPE_SIS_VR = 'SIS.VR';
    public const VEHICLE_TYPE_SIS_VSAV = 'SIS.VSAV';
    public const VEHICLE_TYPE_SIS_MOYSSE = 'SIS.MOYSSE';
    public const VEHICLE_TYPE_SIS_AUTRESIS = 'SIS.AUTRESIS';
    public const VEHICLE_TYPE_SMUR = 'SMUR';
    public const VEHICLE_TYPE_SMUR_VLM = 'SMUR.VLM';
    public const VEHICLE_TYPE_SMUR_VL = 'SMUR.VL';
    public const VEHICLE_TYPE_SMUR_PSM1 = 'SMUR.PSM1';
    public const VEHICLE_TYPE_SMUR_PSM2 = 'SMUR.PSM2';
    public const VEHICLE_TYPE_SMUR_PSM3 = 'SMUR.PSM3';
    public const VEHICLE_TYPE_SMUR_PSMP = 'SMUR.PSMP';
    public const VEHICLE_TYPE_SMUR_VPC = 'SMUR.VPC';
    public const VEHICLE_TYPE_SMUR_AR = 'SMUR.AR';
    public const VEHICLE_TYPE_SMUR_AR_BAR = 'SMUR.AR-BAR';
    public const VEHICLE_TYPE_SMUR_AR_PED = 'SMUR.AR-PED';
    public const VEHICLE_TYPE_SMUR_HELISMUR = 'SMUR.HELISMUR';
    public const VEHICLE_TYPE_SMUR_HELISAN = 'SMUR.HELISAN';
    public const VEHICLE_TYPE_SMUR_AVSMUR = 'SMUR.AVSMUR';
    public const VEHICLE_TYPE_SMUR_AVSAN = 'SMUR.AVSAN';
    public const VEHICLE_TYPE_SMUR_NAVISMUR = 'SMUR.NAVISMUR';
    public const VEHICLE_TYPE_TSU = 'TSU';
    public const VEHICLE_TYPE_TSU_VSL = 'TSU.VSL';
    public const VEHICLE_TYPE_TSU_AMB_GV = 'TSU.AMB-GV';
    public const VEHICLE_TYPE_TSU_AMB_PV = 'TSU.AMB-PV';
    public const VEHICLE_TYPE_TSU_AMB_BAR = 'TSU.AMB-BAR';
    public const VEHICLE_TYPE_TSU_AMB = 'TSU.AMB';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getVehicleTypeAllowableValues()
    {
        return [
            self::VEHICLE_TYPE_AASC,
            self::VEHICLE_TYPE_AASC_VLSC,
            self::VEHICLE_TYPE_AASC_VPSP,
            self::VEHICLE_TYPE_AASC_AUTRESC,
            self::VEHICLE_TYPE_AUTREVEC,
            self::VEHICLE_TYPE_AUTREVEC_APIED,
            self::VEHICLE_TYPE_AUTREVEC_AVION,
            self::VEHICLE_TYPE_AUTREVEC_PERSO,
            self::VEHICLE_TYPE_AUTREVEC_TAXI,
            self::VEHICLE_TYPE_AUTREVEC_TRAIN,
            self::VEHICLE_TYPE_AUTREVEC_TRANSP,
            self::VEHICLE_TYPE_AUTREVEC_AUTRE,
            self::VEHICLE_TYPE_AUTREVEC_AUTRETRA,
            self::VEHICLE_TYPE_FSI,
            self::VEHICLE_TYPE_FSI_HELIFSI,
            self::VEHICLE_TYPE_FSI_VLFSI,
            self::VEHICLE_TYPE_FSI_FFSI,
            self::VEHICLE_TYPE_FSI_VHFSI,
            self::VEHICLE_TYPE_LIB,
            self::VEHICLE_TYPE_LIB_MEDV,
            self::VEHICLE_TYPE_LIB_INF,
            self::VEHICLE_TYPE_LIB_AUTREPRO,
            self::VEHICLE_TYPE_SIS,
            self::VEHICLE_TYPE_SIS_DRAGON,
            self::VEHICLE_TYPE_SIS_AVSC,
            self::VEHICLE_TYPE_SIS_FEUSIS,
            self::VEHICLE_TYPE_SIS_GRIMP,
            self::VEHICLE_TYPE_SIS_NAVISIS,
            self::VEHICLE_TYPE_SIS_PCSIS,
            self::VEHICLE_TYPE_SIS_SRSIS,
            self::VEHICLE_TYPE_SIS_VCH,
            self::VEHICLE_TYPE_SIS_VLCG,
            self::VEHICLE_TYPE_SIS_VLISP,
            self::VEHICLE_TYPE_SIS_VLMSP,
            self::VEHICLE_TYPE_SIS_VLSIS,
            self::VEHICLE_TYPE_SIS_VPL,
            self::VEHICLE_TYPE_SIS_VPMA,
            self::VEHICLE_TYPE_SIS_VR,
            self::VEHICLE_TYPE_SIS_VSAV,
            self::VEHICLE_TYPE_SIS_MOYSSE,
            self::VEHICLE_TYPE_SIS_AUTRESIS,
            self::VEHICLE_TYPE_SMUR,
            self::VEHICLE_TYPE_SMUR_VLM,
            self::VEHICLE_TYPE_SMUR_VL,
            self::VEHICLE_TYPE_SMUR_PSM1,
            self::VEHICLE_TYPE_SMUR_PSM2,
            self::VEHICLE_TYPE_SMUR_PSM3,
            self::VEHICLE_TYPE_SMUR_PSMP,
            self::VEHICLE_TYPE_SMUR_VPC,
            self::VEHICLE_TYPE_SMUR_AR,
            self::VEHICLE_TYPE_SMUR_AR_BAR,
            self::VEHICLE_TYPE_SMUR_AR_PED,
            self::VEHICLE_TYPE_SMUR_HELISMUR,
            self::VEHICLE_TYPE_SMUR_HELISAN,
            self::VEHICLE_TYPE_SMUR_AVSMUR,
            self::VEHICLE_TYPE_SMUR_AVSAN,
            self::VEHICLE_TYPE_SMUR_NAVISMUR,
            self::VEHICLE_TYPE_TSU,
            self::VEHICLE_TYPE_TSU_VSL,
            self::VEHICLE_TYPE_TSU_AMB_GV,
            self::VEHICLE_TYPE_TSU_AMB_PV,
            self::VEHICLE_TYPE_TSU_AMB_BAR,
            self::VEHICLE_TYPE_TSU_AMB,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('datetime', $data ?? [], null);
        $this->setIfExists('resourceId', $data ?? [], null);
        $this->setIfExists('requestId', $data ?? [], null);
        $this->setIfExists('missionId', $data ?? [], null);
        $this->setIfExists('orgId', $data ?? [], null);
        $this->setIfExists('patientId', $data ?? [], null);
        $this->setIfExists('centerName', $data ?? [], null);
        $this->setIfExists('vehicleType', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('centerCity', $data ?? [], null);
        $this->setIfExists('team', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('contact', $data ?? [], null);
        $this->setIfExists('freetext', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['datetime'] === null) {
            $invalidProperties[] = "'datetime' can't be null";
        }
        if (!preg_match("/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}[\\-+]\\d{2}:\\d{2}$/", $this->container['datetime'])) {
            $invalidProperties[] = "invalid value for 'datetime', must be conform to the pattern /^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}[\\-+]\\d{2}:\\d{2}$/.";
        }

        if ($this->container['resourceId'] === null) {
            $invalidProperties[] = "'resourceId' can't be null";
        }
        if (!preg_match("/^([a-zA-Z0-9_-]+\\.){3,8}resource(\\.[a-zA-Z0-9_-]+){1,2}$/", $this->container['resourceId'])) {
            $invalidProperties[] = "invalid value for 'resourceId', must be conform to the pattern /^([a-zA-Z0-9_-]+\\.){3,8}resource(\\.[a-zA-Z0-9_-]+){1,2}$/.";
        }

        if (!is_null($this->container['requestId']) && !preg_match("/^([a-zA-Z0-9_-]+\\.){3,8}request(\\.[a-zA-Z0-9_-]+){1,2}$/", $this->container['requestId'])) {
            $invalidProperties[] = "invalid value for 'requestId', must be conform to the pattern /^([a-zA-Z0-9_-]+\\.){3,8}request(\\.[a-zA-Z0-9_-]+){1,2}$/.";
        }

        if ($this->container['vehicleType'] === null) {
            $invalidProperties[] = "'vehicleType' can't be null";
        }
        $allowedValues = $this->getVehicleTypeAllowableValues();
        if (!is_null($this->container['vehicleType']) && !in_array($this->container['vehicleType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'vehicleType', must be one of '%s'",
                $this->container['vehicleType'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['centerCity']) && !preg_match("/^[0-9]{5}$/", $this->container['centerCity'])) {
            $invalidProperties[] = "invalid value for 'centerCity', must be conform to the pattern /^[0-9]{5}$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets datetime
     *
     * @return \DateTime
     */
    public function getDatetime()
    {
        return $this->container['datetime'];
    }

    /**
     * Sets datetime
     *
     * @param \DateTime $datetime A valoriser avec la date et heure d'engagement de la ressource/du vecteur
     *
     * @return self
     */
    public function setDatetime($datetime)
    {
        if (is_null($datetime)) {
            throw new \InvalidArgumentException('non-nullable datetime cannot be null');
        }

        if ((!preg_match("/^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}[\\-+]\\d{2}:\\d{2}$/", ObjectSerializer::toString($datetime)))) {
            throw new \InvalidArgumentException("invalid value for \$datetime when calling Resource., must conform to the pattern /^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}[\\-+]\\d{2}:\\d{2}$/.");
        }

        $this->container['datetime'] = $datetime;

        return $this;
    }

    /**
     * Gets resourceId
     *
     * @return string
     */
    public function getResourceId()
    {
        return $this->container['resourceId'];
    }

    /**
     * Sets resourceId
     *
     * @param string $resourceId A valoriser avec l'identifiant partagé unique de la ressource engagée, normé comme suit : {orgID}.resource.{ID unique de la ressource partagée} OU - uniquement dans le cas où un ID unique de ressource ne peut pas être garanti par l'organisation propriétaire : {orgID}.resource.{sendercaseId}.{n° d’ordre chronologique de la ressource}
     *
     * @return self
     */
    public function setResourceId($resourceId)
    {
        if (is_null($resourceId)) {
            throw new \InvalidArgumentException('non-nullable resourceId cannot be null');
        }

        if ((!preg_match("/^([a-zA-Z0-9_-]+\\.){3,8}resource(\\.[a-zA-Z0-9_-]+){1,2}$/", ObjectSerializer::toString($resourceId)))) {
            throw new \InvalidArgumentException("invalid value for \$resourceId when calling Resource., must conform to the pattern /^([a-zA-Z0-9_-]+\\.){3,8}resource(\\.[a-zA-Z0-9_-]+){1,2}$/.");
        }

        $this->container['resourceId'] = $resourceId;

        return $this;
    }

    /**
     * Gets requestId
     *
     * @return string|null
     */
    public function getRequestId()
    {
        return $this->container['requestId'];
    }

    /**
     * Sets requestId
     *
     * @param string|null $requestId A valoriser avec l'identifiant unique partagé de la demande de ressource (si la ressource a été engagée suite à une demande de ressource), normé comme suit : {orgID}.request.{ID unique de la demande dans le système émetteur} OU - si un ID unique de la demande n'était pas disponible :  {OrgId émetteur}.request.{senderCaseId}.{numéro d’ordre chronologique}
     *
     * @return self
     */
    public function setRequestId($requestId)
    {
        if (is_null($requestId)) {
            throw new \InvalidArgumentException('non-nullable requestId cannot be null');
        }

        if ((!preg_match("/^([a-zA-Z0-9_-]+\\.){3,8}request(\\.[a-zA-Z0-9_-]+){1,2}$/", ObjectSerializer::toString($requestId)))) {
            throw new \InvalidArgumentException("invalid value for \$requestId when calling Resource., must conform to the pattern /^([a-zA-Z0-9_-]+\\.){3,8}request(\\.[a-zA-Z0-9_-]+){1,2}$/.");
        }

        $this->container['requestId'] = $requestId;

        return $this;
    }

    /**
     * Gets missionId
     *
     * @return string|null
     */
    public function getMissionId()
    {
        return $this->container['missionId'];
    }

    /**
     * Sets missionId
     *
     * @param string|null $missionId A valoriser avec le numéro de mission unique du central d’appel (PSAP, …) qui a déclenché le vecteur
     *
     * @return self
     */
    public function setMissionId($missionId)
    {
        if (is_null($missionId)) {
            throw new \InvalidArgumentException('non-nullable missionId cannot be null');
        }
        $this->container['missionId'] = $missionId;

        return $this;
    }

    /**
     * Gets orgId
     *
     * @return string|null
     */
    public function getOrgId()
    {
        return $this->container['orgId'];
    }

    /**
     * Sets orgId
     *
     * @param string|null $orgId A valoriser avec l'identifiant de l'organisation à laquelle appartient la ressource, normé comme suit :  {pays}.{domaine}.{organisation}
     *
     * @return self
     */
    public function setOrgId($orgId)
    {
        if (is_null($orgId)) {
            throw new \InvalidArgumentException('non-nullable orgId cannot be null');
        }
        $this->container['orgId'] = $orgId;

        return $this;
    }

    /**
     * Gets patientId
     *
     * @return string|null
     */
    public function getPatientId()
    {
        return $this->container['patientId'];
    }

    /**
     * Sets patientId
     *
     * @param string|null $patientId Identifiant partagé du patient qui est transporté. Ce n'est à remplir que lorsque l'on sait quel vecteur transporte quel patient.  Il est valorisé comme suit lors de sa création :  {OrgId émetteur}.patient.{n°patient unique dans le système émetteur}  OU, si un n°patient unique n'existe pas dans le système émetteur : {ID émetteur}.{senderCaseId}.patient.{numéro d’ordre chronologique au dossier}
     *
     * @return self
     */
    public function setPatientId($patientId)
    {
        if (is_null($patientId)) {
            throw new \InvalidArgumentException('non-nullable patientId cannot be null');
        }
        $this->container['patientId'] = $patientId;

        return $this;
    }

    /**
     * Gets centerName
     *
     * @return string|null
     */
    public function getCenterName()
    {
        return $this->container['centerName'];
    }

    /**
     * Sets centerName
     *
     * @param string|null $centerName A valoriser avec le lieu de garage principal
     *
     * @return self
     */
    public function setCenterName($centerName)
    {
        if (is_null($centerName)) {
            throw new \InvalidArgumentException('non-nullable centerName cannot be null');
        }
        $this->container['centerName'] = $centerName;

        return $this;
    }

    /**
     * Gets vehicleType
     *
     * @return string
     */
    public function getVehicleType()
    {
        return $this->container['vehicleType'];
    }

    /**
     * Sets vehicleType
     *
     * @param string $vehicleType A valoriser avec le type de vecteur mobilisé : cf. nomenclature associée
     *
     * @return self
     */
    public function setVehicleType($vehicleType)
    {
        if (is_null($vehicleType)) {
            throw new \InvalidArgumentException('non-nullable vehicleType cannot be null');
        }
        $allowedValues = $this->getVehicleTypeAllowableValues();
        if (!in_array($vehicleType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'vehicleType', must be one of '%s'",
                    $vehicleType,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['vehicleType'] = $vehicleType;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name A valoriser avec le nom donné à la ressource par l’organisation d’appartenance
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets centerCity
     *
     * @return string|null
     */
    public function getCenterCity()
    {
        return $this->container['centerCity'];
    }

    /**
     * Sets centerCity
     *
     * @param string|null $centerCity A valoriser avec le code INSEE de la commune du centre d'affectation
     *
     * @return self
     */
    public function setCenterCity($centerCity)
    {
        if (is_null($centerCity)) {
            throw new \InvalidArgumentException('non-nullable centerCity cannot be null');
        }

        if ((!preg_match("/^[0-9]{5}$/", ObjectSerializer::toString($centerCity)))) {
            throw new \InvalidArgumentException("invalid value for \$centerCity when calling Resource., must conform to the pattern /^[0-9]{5}$/.");
        }

        $this->container['centerCity'] = $centerCity;

        return $this;
    }

    /**
     * Gets team
     *
     * @return \Hubsante\Model\resources.info\Team|null
     */
    public function getTeam()
    {
        return $this->container['team'];
    }

    /**
     * Sets team
     *
     * @param \Hubsante\Model\resources.info\Team|null $team team
     *
     * @return self
     */
    public function setTeam($team)
    {
        if (is_null($team)) {
            throw new \InvalidArgumentException('non-nullable team cannot be null');
        }
        $this->container['team'] = $team;

        return $this;
    }

    /**
     * Gets state
     *
     * @return \Hubsante\Model\resources.info\State[]|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param \Hubsante\Model\resources.info\State[]|null $state state
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            throw new \InvalidArgumentException('non-nullable state cannot be null');
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets contact
     *
     * @return \Hubsante\Model\resources.info\Contact|null
     */
    public function getContact()
    {
        return $this->container['contact'];
    }

    /**
     * Sets contact
     *
     * @param \Hubsante\Model\resources.info\Contact|null $contact contact
     *
     * @return self
     */
    public function setContact($contact)
    {
        if (is_null($contact)) {
            throw new \InvalidArgumentException('non-nullable contact cannot be null');
        }
        $this->container['contact'] = $contact;

        return $this;
    }

    /**
     * Gets freetext
     *
     * @return string[]|null
     */
    public function getFreetext()
    {
        return $this->container['freetext'];
    }

    /**
     * Sets freetext
     *
     * @param string[]|null $freetext freetext
     *
     * @return self
     */
    public function setFreetext($freetext)
    {
        if (is_null($freetext)) {
            throw new \InvalidArgumentException('non-nullable freetext cannot be null');
        }
        $this->container['freetext'] = $freetext;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


