<?php
/**
 * Practitioner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hubsante
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hubsante\Model\sas;

use \ArrayAccess;
use \Hubsante\ObjectSerializer;

/**
 * Practitioner Class Doc Comment
 *
 * @category Class
 * @package  Hubsante
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Practitioner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'practitioner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'rppsId' => 'string',
        'lastName' => 'string',
        'firstName' => 'string',
        'specialityCode' => 'string',
        'specialityUrl' => 'string',
        'professionCode' => 'string',
        'professionUrl' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'rppsId' => null,
        'lastName' => null,
        'firstName' => null,
        'specialityCode' => null,
        'specialityUrl' => null,
        'professionCode' => null,
        'professionUrl' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'rppsId' => false,
        'lastName' => false,
        'firstName' => false,
        'specialityCode' => false,
        'specialityUrl' => false,
        'professionCode' => false,
        'professionUrl' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rppsId' => 'rppsId',
        'lastName' => 'lastName',
        'firstName' => 'firstName',
        'specialityCode' => 'specialityCode',
        'specialityUrl' => 'specialityUrl',
        'professionCode' => 'professionCode',
        'professionUrl' => 'professionUrl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rppsId' => 'setRppsId',
        'lastName' => 'setLastName',
        'firstName' => 'setFirstName',
        'specialityCode' => 'setSpecialityCode',
        'specialityUrl' => 'setSpecialityUrl',
        'professionCode' => 'setProfessionCode',
        'professionUrl' => 'setProfessionUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rppsId' => 'getRppsId',
        'lastName' => 'getLastName',
        'firstName' => 'getFirstName',
        'specialityCode' => 'getSpecialityCode',
        'specialityUrl' => 'getSpecialityUrl',
        'professionCode' => 'getProfessionCode',
        'professionUrl' => 'getProfessionUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('rppsId', $data ?? [], null);
        $this->setIfExists('lastName', $data ?? [], null);
        $this->setIfExists('firstName', $data ?? [], null);
        $this->setIfExists('specialityCode', $data ?? [], null);
        $this->setIfExists('specialityUrl', $data ?? [], null);
        $this->setIfExists('professionCode', $data ?? [], null);
        $this->setIfExists('professionUrl', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['rppsId'] === null) {
            $invalidProperties[] = "'rppsId' can't be null";
        }
        if (!preg_match("/^81[0-9]{10}$/", $this->container['rppsId'])) {
            $invalidProperties[] = "invalid value for 'rppsId', must be conform to the pattern /^81[0-9]{10}$/.";
        }

        if ($this->container['lastName'] === null) {
            $invalidProperties[] = "'lastName' can't be null";
        }
        if ($this->container['firstName'] === null) {
            $invalidProperties[] = "'firstName' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rppsId
     *
     * @return string
     */
    public function getRppsId()
    {
        return $this->container['rppsId'];
    }

    /**
     * Sets rppsId
     *
     * @param string $rppsId Identifiant national (RPPS) du PS
     *
     * @return self
     */
    public function setRppsId($rppsId)
    {
        if (is_null($rppsId)) {
            throw new \InvalidArgumentException('non-nullable rppsId cannot be null');
        }

        if ((!preg_match("/^81[0-9]{10}$/", ObjectSerializer::toString($rppsId)))) {
            throw new \InvalidArgumentException("invalid value for \$rppsId when calling Practitioner., must conform to the pattern /^81[0-9]{10}$/.");
        }

        $this->container['rppsId'] = $rppsId;

        return $this;
    }

    /**
     * Gets lastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->container['lastName'];
    }

    /**
     * Sets lastName
     *
     * @param string $lastName Nom du professionnel de santé
     *
     * @return self
     */
    public function setLastName($lastName)
    {
        if (is_null($lastName)) {
            throw new \InvalidArgumentException('non-nullable lastName cannot be null');
        }
        $this->container['lastName'] = $lastName;

        return $this;
    }

    /**
     * Gets firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->container['firstName'];
    }

    /**
     * Sets firstName
     *
     * @param string $firstName Prénom du professionnel de santé
     *
     * @return self
     */
    public function setFirstName($firstName)
    {
        if (is_null($firstName)) {
            throw new \InvalidArgumentException('non-nullable firstName cannot be null');
        }
        $this->container['firstName'] = $firstName;

        return $this;
    }

    /**
     * Gets specialityCode
     *
     * @return string|null
     */
    public function getSpecialityCode()
    {
        return $this->container['specialityCode'];
    }

    /**
     * Sets specialityCode
     *
     * @param string|null $specialityCode Code de la spécialité du professionnel de santé
     *
     * @return self
     */
    public function setSpecialityCode($specialityCode)
    {
        if (is_null($specialityCode)) {
            throw new \InvalidArgumentException('non-nullable specialityCode cannot be null');
        }
        $this->container['specialityCode'] = $specialityCode;

        return $this;
    }

    /**
     * Gets specialityUrl
     *
     * @return string|null
     */
    public function getSpecialityUrl()
    {
        return $this->container['specialityUrl'];
    }

    /**
     * Sets specialityUrl
     *
     * @param string|null $specialityUrl Url de la terminologie utilisée pour la spécialité
     *
     * @return self
     */
    public function setSpecialityUrl($specialityUrl)
    {
        if (is_null($specialityUrl)) {
            throw new \InvalidArgumentException('non-nullable specialityUrl cannot be null');
        }
        $this->container['specialityUrl'] = $specialityUrl;

        return $this;
    }

    /**
     * Gets professionCode
     *
     * @return string|null
     */
    public function getProfessionCode()
    {
        return $this->container['professionCode'];
    }

    /**
     * Sets professionCode
     *
     * @param string|null $professionCode Code de la profession du professionnel de santé
     *
     * @return self
     */
    public function setProfessionCode($professionCode)
    {
        if (is_null($professionCode)) {
            throw new \InvalidArgumentException('non-nullable professionCode cannot be null');
        }
        $this->container['professionCode'] = $professionCode;

        return $this;
    }

    /**
     * Gets professionUrl
     *
     * @return string|null
     */
    public function getProfessionUrl()
    {
        return $this->container['professionUrl'];
    }

    /**
     * Sets professionUrl
     *
     * @param string|null $professionUrl Url de la terminologie utilisée pour la profession
     *
     * @return self
     */
    public function setProfessionUrl($professionUrl)
    {
        if (is_null($professionUrl)) {
            throw new \InvalidArgumentException('non-nullable professionUrl cannot be null');
        }
        $this->container['professionUrl'] = $professionUrl;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


