class ResourcesInfoConstants:
    V3_TO_V2_STATUS_MAPPING = {
        "FINPEC": "FINMED",
    }

    V1_TO_V2_STATUS_MAPPING = {
        "ARRIVE": "ARRIVEE",
        "TRANSPOR": "TRANSP",
        "FINPEC": "FINMED",
    }

    V2_PATHS_TO_DELETE = [
        "resource",
        "mobilizedResource[].team.medicalLevel",
        "mobilizedResource[].vehicleType",
    ]

    V3_PATHS_TO_DELETE = [
        "resource[].patientId",
    ]

    V1_PATHS_TO_DELETE = [
        "resource[].coord",
        "resource[].vehiculeType",
        "resource[].team.teamCare",
        "resource[].resourceType",
        "resource[].plate",
        "mobilizedResource",
    ]

    V1_TO_V2_VEHICULE_TYPE_MAPPING = {
        "AASC": "AASC",
        "VLSC": "AASC.VLSC",
        "VPSP": "AASC.VPSP",
        "AUTRESC": "AASC.AUTRESC",
        "AUTREVEC": "AUTREVEC",
        "TAXI": "AUTREVEC.TAXI",
        "TRANSP": "AUTREVEC.TRANSP",
        "TRAIN": "AUTREVEC.TRAIN",
        "AVION": "AUTREVEC.AVION",
        "PERSO": "AUTREVEC.PERSO",
        "APIED": "AUTREVEC.APIED",
        "AUTRE": "AUTREVEC.AUTRE",
        "AUTRETRA": "AUTREVEC.AUTRETRA",
        "FSI": "FSI",
        "HELIFSI": "FSI.HELIFSI",
        "VLFSI": "FSI.VLFSI",
        "FFSI": "FSI.FFSI",
        "VHFSI": "FSI.VHFSI",
        "LIB": "LIB",
        "MEDV": "LIB.MEDV",
        "INF": "LIB.INF",
        "AUTREPRO": "LIB.AUTREPRO",
        "SIS": "SIS",
        "VSAV": "SIS.VSAV",
        "GRIMP": "SIS.GRIMP",
        "VPL": "SIS.VPL",
        "SRSIS": "SIS.SRSIS",
        "FEUSIS": "SIS.FEUSIS",
        "VPMA": "SIS.VPMA",
        "VCH": "SIS.VCH",
        "VR": "SIS.VR",
        "PCSIS": "SIS.PCSIS",
        "VLISP": "SIS.VLISP",
        "VLMSP": "SIS.VLMSP",
        "VLCG": "SIS.VLCG",
        "VLSIS": "SIS.VLSIS",
        "DRAGON": "SIS.DRAGON",
        "AVSC": "SIS.AVSC",
        "MOYSSE": "SIS.MOYSSE",
        "AUTRESIS": "SIS.AUTRESIS",
        "NAVISIS": "SIS.NAVISIS",
        "SMUR": "SMUR",
        "VLM": "SMUR.VLM",
        "VL": "SMUR.VL",
        "PSM1": "SMUR.PSM1",
        "PSM2": "SMUR.PSM2",
        "PSM3": "SMUR.PSM3",
        "PSMP": "SMUR.PSMP",
        "VPC": "SMUR.VPC",
        "AR": "SMUR.AR",
        "AR-BAR": "SMUR.AR-BAR",
        "AR-PED": "SMUR.AR-PED",
        "HELISMUR": "SMUR.HELISMUR",
        "HELISAN": "SMUR.HELISAN",
        "AVSMUR": "SMUR.AVSMUR",
        "AVSAN": "SMUR.AVSAN",
        "NAVISMUR": "SMUR.NAVISMUR",
        "TSU": "TSU",
        "VSL": "TSU.VSL",
        "AMB-GV": "TSU.AMB-GV",
        "AMB-PV": "TSU.AMB-PV",
        "AMB-BAR": "TSU.AMB-BAR",
        "AMB": "TSU.AMB",
    }
