name: 'Fix Trivy SARIF File Paths'
description: 'Fixes file paths in Trivy SARIF output for GitHub Security tab'

inputs:
  sarif-file:
    description: 'Path to the SARIF file to fix'
    required: true
  scan-path:
    description: 'The relative path that was scanned (e.g., converter, generator)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Fix SARIF file paths
      shell: bash
      run: |
        SARIF_FILE="${{ inputs.sarif-file }}"
        SCAN_PATH="${{ inputs.scan-path }}"
        
        if [ ! -f "$SARIF_FILE" ]; then
          echo "::error::SARIF file not found: $SARIF_FILE"
          exit 1
        fi
        
        echo "🔧 Fixing SARIF file paths in $SARIF_FILE for scan path: $SCAN_PATH"
        
        # Use jq to fix the file paths in the SARIF output
        jq --arg scan_path "$SCAN_PATH" '
          def fix_uri:
            if startswith("/") then
              . as $full_path |
              ($full_path | split("/") | reverse) as $parts |
              ($scan_path | split("/") | reverse) as $scan_parts |
              # Find the matching suffix and construct the relative path
              if ($parts | length) > ($scan_parts | length) then
                ($parts[0:($scan_parts | length)] == $scan_parts) as $matches |
                if $matches then
                  $parts | reverse | join("/")
                else
                  .
                end
              else
                .
              end
            else
              .
            end;
          
          (.runs[]?.results[]?.locations[]?.physicalLocation?.artifactLocation?.uri?) |= fix_uri |
          (.runs[]?.artifacts[]?.location?.uri?) |= fix_uri
        ' "$SARIF_FILE" > "${SARIF_FILE}.tmp" && mv "${SARIF_FILE}.tmp" "$SARIF_FILE"
        
        echo "✅ SARIF file paths fixed successfully"