# Composite action | https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-composite-action
name: Generate test cases
description: Generate the json containing the test cases
runs:
  using: "composite"
  steps:  
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install python requirements
      working-directory: ./csv_parser
      shell: bash
      run: pip install -r ./requirements.txt

    - name: Run test_case_generator
      working-directory: ./csv_parser
      run: |
        rm -r ./out/test-cases || true
        python workflow.py --stage test_case_parser
      shell: bash
    
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ⚙️ Auto-génération des cas de test