=begin
Generated by: https://github.com/openapitools/openapi-generator.git

=end


class CreateCaseHealth < ApplicationRecord
  validates_presence_of :case_id
  validates_presence_of :creation
  validates_presence_of :qualification
  validates_presence_of :location
  validates_presence_of :owner

  serialize :patient, Array
  serialize :medical_note, Array
  serialize :decision, Array
end
