openapi: 3.0.0
components:
  schemas:
    customContentWrapper:
      type: object
      required:
      - customContent
      properties:
        customContent:
          $ref: '#/components/schemas/customContent'
    customContent:
      $id: classpath:/json-schema/schema#
      x-id: customContent.schema.json#
      example: example.json#
      type: object
      title: customContent
      required: []
      properties: {}
      additionalProperties: true
      examples:
      - {}
