openapi: 3.0.0
components:
  schemas:
    emsiWrapper:
      $id: classpath:/json-schema/schema#
      x-id: EMSI.schema.json#
      example: example.json#
      type: object
      title: emsi
      required:
      - emsi
      properties:
        emsi:
          $ref: '#/components/schemas/emsi'
    emsi:
      type: object
      title: Objet emsi
      x-display: expansion-panels
      x-health-only: false
      required: []
      properties:
        RESOURCE:
          type: array
          items:
            $ref: '#/components/schemas/resource'
      example: example.json#/emsi
    resource:
      type: object
      title: Ressource
      x-display: expansion-panels
      x-health-only: true
      required:
      - RTYPE
      properties:
        RTYPE:
          $ref: '#/components/schemas/rtype'
        ID:
          type: string
          title: ID de la ressource
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/ID
          description: "Identifiant unique de la ressource  dans le syst\xE8me du\
            \ partenaire propri\xE9taire. Les syst\xE8mes sont garants de l'unicit\xE9\
            \ et de l'invariablit\xE9 des ids de v\xE9hicule dans le temps. Ils peuvent\
            \ se servir des ids dans les r\xE9f\xE9rentiels existants si ils sont\
            \ uniques et stables.\nDans le cas d'un v\xE9hicule agr\xE9g\xE9 par un\
            \ LRM (comme un SMUR), l'ID doit \xEAtre valoris\xE9 avec son immatriculation.\n\
            Dans le cas d'un v\xE9hicule agr\xE9g\xE9 par NexSIS, l'ID fournit peut\
            \ ne pas correspondre \xE0 une immatriculation."
          examples:
          - 77_45102#VSAV 1#
        ORG_ID:
          type: string
          title: "Identifiant de l'organisation propri\xE9taire"
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/ORG_ID
          description: "Identifiant de l'organisation \xE0 laquelle la ressource est\
            \ rattach\xE9e (caserne, SAMU etc).\nSe r\xE9f\xE9rer au DSF pour la structure\
            \ norm\xE9e des organisations\nLe format est le suivant {pays}.{domaine}.{code\
            \ d\xE9partement}.{organisation}.{structure interne}*.{unit\xE9 fonctionnelle}*.\n\
            Dans le cas o\xF9 le LRM/NexSIS sert d'aggr\xE9gateur pour des v\xE9hicules\
            \ appartenant \xE0 un partenaire tiers (type ambulance priv\xE9e), l'identifiant\
            \ d'organisation permet d'identifier ce tiers\nA constituer par le r\xE9\
            dacteur du pr\xE9sent EMSI pour \xEAtre unique, identique \xE0 <CONTEXT><ORIGIN><ORG_ID>"
          examples:
          - FR:Administration:44:CASERNENANTES
        NAME:
          type: string
          title: Nom de la ressource
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/NAME
          description: "Nom donn\xE9 \xE0 la ressource par le partenaire. L'immatriculation\
            \ peut \xEAtre utilis\xE9e dans le nom courant des v\xE9hicules.\nDans\
            \ le cas pompier, les v\xE9hicules sont nomm\xE9s\nDans le cas d'\xE9\
            quipier, cela peut \xEAtre leur nom"
          examples:
          - VSAV 1 Nantes
        FREETEXT:
          type: string
          title: Description de la ressource
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/FREETEXT
          description: "Texte libre permettant de d\xE9crire la ressource o\xF9 d'ajouter\
            \ des pr\xE9cisions sur son engagement.\nPermet aussi notamment de d\xE9\
            crire des attributs librement pour la ressource.\nPar exemple, pour un\
            \ v\xE9hicule, sa plaque d'immatriculation."
          examples:
          - None
        RGEO:
          type: array
          items:
            $ref: '#/components/schemas/rgeo'
        QUANTITY:
          type: number
          title: "Quantit\xE9 de la ressource"
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/QUANTITY
          description: "Dans le cadre d'un \xE9change d'op\xE9ration, optionnel. Permet\
            \ de quantifier une ressource :\n- \xE0 ne pas utiliser pour les v\xE9\
            hicules ni le personnel\n- utilisable pour du mat\xE9riel\n- utilisable\
            \ pour des consommables (dans le cas de consommable, \xE0 compl\xE9ter\
            \ avec le champ UM)"
          examples:
          - 1
        UM:
          type: string
          title: "Unit\xE9 de mesure pour la ressource"
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/UM
          description: "Dans le cadre d'un \xE9change d'op\xE9ration, optionnel. Unit\xE9\
            \ de mesure pour des ressources consommables"
          examples:
          - None
        STATUS:
          type: string
          title: Statut de la ressource
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/STATUS
          description: "D\xE9finit le statut de disponibilit\xE9 d'une ressource.\n\
            - AVAILB : Lorsqu'une mission est termin\xE9e, une ressource redevient\
            \ disponible\n- RESRVD : Lorsque la ressource est r\xE9serv\xE9e pour\
            \ intervenir sur l'affaire mais pas encore engag\xE9e dans l'op\xE9ration.\
            \ Par exemple : un SMUR termine un autre transfert patient/victime avant\
            \ de rejoindre une autre intervention : il est alors RESRVD\n- IN_USE/MOBILE\
            \ : \xE0 utiliser pour les v\xE9hicules et le personnel lorsqu'ils se\
            \ d\xE9places\n- IN_USE/ON_SCENE : \xE0 utiliser pour les v\xE9hicules\
            \ et le personnel lorsqu'ils sont sur les lieux de l'affaire"
          examples:
          - IN_USE/MOBILE
        NATIONALITY:
          type: string
          title: "Nationalit\xE9 de la ressource"
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/NATIONALITY
          description: "Nationalit\xE9 d'une ressource, r\xE9employer ISO 3166-1-alpha-2\
            \ code elements."
          examples:
          - FR
        CONTACTS:
          type: array
          items:
            $ref: '#/components/schemas/contact'
      example: example.json#/emsi/RESOURCE/0
    rtype:
      type: object
      title: Type de la ressource
      x-display: expansion-panels
      x-health-only: true
      required:
      - RCLASS
      properties:
        RCLASS:
          type: array
          items:
            type: string
            title: Classes de la ressource
            x-cols: 6
            example: example.json#/emsi/RESOURCE/0/RTYPE/RCLASS/0
            description: "Permet d'indiquer la classe de l'objet RESOURCE. Plusieurs\
              \ niveau de d\xE9tails sont fournis par la nomenclature associ\xE9e.\n\
              Le premier niveau permet notamment de d\xE9crire la classe principale\
              \ de ressource :\n- Un v\xE9hicule,\n- Le personnel mobilis\xE9,\n-\
              \ Des consommables/ du mat\xE9riel,\n- Un lieu ou une organisation (non\
              \ utilis\xE9 pour le moment)\nVoir nomenclature EMSI associ\xE9e"
            examples:
            - MAT/VEH/ROADVE/FRFGTN
        CAPABILITY:
          type: array
          items:
            type: string
            title: "Capacit\xE9s de la ressource"
            x-cols: 6
            example: example.json#/emsi/RESOURCE/0/RTYPE/CAPABILITY/0
            description: "Permet d'indiquer les capacit\xE9s de la ressource d'apr\xE8\
              s le standard EMSI"
            examples:
            - None
        CHARACTERISTICS:
          type: array
          items:
            type: string
            title: "Caract\xE9ristiques de la ressource"
            x-cols: 6
            example: example.json#/emsi/RESOURCE/0/RTYPE/CHARACTERISTICS/0
            description: "Permet d'indiquer des caract\xE9ristique physiques de la\
              \ ressource (hauteur, largeur, longueur et poids).\nLe d\xE9tail de\
              \ fonctionnement de cette nomenclature est fournie en annexe."
            examples:
            - None
      example: example.json#/emsi/RESOURCE/0/RTYPE
    rgeo:
      type: object
      title: Localisation de la ressource
      x-display: expansion-panels
      x-health-only: true
      required:
      - TYPE
      properties:
        DATIME:
          type: string
          title: Horaire de la localisation
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/RGEO/0/DATIME
          description: "Horaire associ\xE9 \xE0 l'arriv\xE9e de la ressource sur la\
            \ position. En fonction du TYPE de possition, peut indiquer un horaire\
            \ de relev\xE9 de position, un horaire cible d'arriv\xE9e."
          pattern: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\-+]\d{2}:\d{2}
          format: date-time
          examples:
          - '2022-09-27T08:44:00+02:00'
        TYPE:
          type: string
          title: Type de localisation
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/RGEO/0/TYPE
          description: "Type de position indiqu\xE9 pour la ressource :\n- ASP : assembly\
            \ point. Point de rassemblement par d\xE9faut des ressources li\xE9es\
            \ \xE0 la mission. Peut ne pas \xEAtre utilis\xE9\n- CUR : current. Position\
            \ actualis\xE9e de la ressource permettant le suivi g\xE9olocalis\xE9\
            \ des v\xE9hicules notamment. Peut ne pas \xEAtre utilis\xE9\n- INC :\
            \ incident. Consigne relative au positionnement de la ressource sur le\
            \ lieu d'intervention. Peut ne pas \xEAtre utilis\xE9\n- STG : staging\
            \ point. Consigne relative au stationnement des v\xE9hicules ou au stockage\
            \ du mat\xE9riel par exemple. peut ne pas \xEAtre utilis\xE9\n- TGT :\
            \ targer location. Si renseign\xE9, doit \xEAtre coh\xE9rent avec la position\
            \ renseign\xE9e pour la mission.\nPlusieurs positions du m\xEAme type\
            \ avec des horodatages diff\xE9rents peuvent \xEAtre fournies. "
          examples:
          - CUR
        FREETEXT:
          type: string
          title: 'Texte libre '
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/RGEO/0/FREETEXT
          description: "Permet de rajouter des pr\xE9cisions sur la localisation de\
            \ la ressource transmise"
          examples:
          - "Position actualis\xE9e du VSAV 1 Nantes"
        ID:
          type: string
          title: ID localisation
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/RGEO/0/ID
          description: "Identifiant unique de la position dans le syst\xE8me du partenaire"
          examples:
          - None
        POSITION:
          type: array
          items:
            $ref: '#/components/schemas/position'
      example: example.json#/emsi/RESOURCE/0/RGEO/0
    contact:
      type: object
      title: Contacts
      x-display: expansion-panels
      x-health-only: true
      required:
      - TYPE
      - DETAIL
      properties:
        TYPE:
          type: string
          title: Type de contact
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/CONTACTS/0/TYPE
          description: "Type de contact, voir \xE9num\xE9ration associ\xE9e\n\n1.\
            \ PMRADD (si RFGI disponible)\n2. PHNADD pour t\xE9l\xE9phonie"
          examples:
          - PHNADD
        DETAIL:
          type: string
          title: "D\xE9tails de contact"
          x-cols: 6
          example: example.json#/emsi/RESOURCE/0/CONTACTS/0/DETAIL
          description: "1. RFGI du moyen NEXSIS (si RFGI disponible)\n2. Num\xE9ro\
            \ de t\xE9l\xE9phone"
          examples:
          - 606070707
      example: example.json#/emsi/RESOURCE/0/CONTACTS/0
      examples:
      - TYPE: PHNADD
        DETAIL: 606070707
    position:
      type: object
      title: "Position g\xE9ographique"
      x-display: expansion-panels
      x-health-only: true
      required: []
      properties: {}
      example: example.json#/emsi/RESOURCE/0/RGEO/0/POSITION/0
      examples:
      - {}
