openapi: 3.0.0
components:
  schemas:
    DistributionElement:
      $id: classpath:/json-schema/schema#
      x-id: RC-DE.schema.json#
      example: example.json#
      type: object
      title: DistributionElement
      required: []
      properties: {}
      additionalProperties: true
      examples:
      - {}
