openapi: '3.0.0'

components:
  schemas:
    DistributionElement:
      type: object
      title: DistributionElement
      required:
        - messageId
        - sender
        - sentAt
        - kind
        - status
        - recipient
      properties:
        messageId:
          type: string
        sender:
          $ref: '#/components/schemas/sender'
        sentAt:
          type: string
          pattern: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\-+]\d{2}:\d{2}
          format: date-time
        kind:
          type: string
          enum:
            - Report
            - Update
            - Cancel
            - Ack
            - Error
        status:
          type: string
          enum:
            - Actual
            - Exercise
            - System
        recipient:
          type: array
          items:
            $ref: '#/components/schemas/recipient'
          minItems: 1
    sender:
      type: object
      required:
        - name
        - URI
      properties:
        name:
          type: string
        URI:
          type: string
    recipient:
      type: object
      required:
        - name
        - URI
      properties:
        name:
          type: string
        URI:
          type: string