openapi: 3.0.0
components:
  schemas:
    referenceWrapper:
      type: object
      required:
      - reference
      properties:
        reference:
          $ref: '#/components/schemas/reference'
    reference:
      $id: classpath:/json-schema/schema#
      x-id: RC-REF.schema.json#
      example: example.json#
      type: object
      title: reference
      required:
      - distributionID
      properties:
        distributionID:
          type: string
          title: "Identifiant du message r\xE9f\xE9renc\xE9"
          x-health-only: false
          x-cols: 6
          example: example.json#/distributionID
          description: "Identifiant unique du message r\xE9f\xE9renc\xE9"
          examples:
          - None
        refused:
          type: boolean
          title: Indicateur de refus de message
          x-health-only: false
          x-cols: 6
          example: example.json#/refused
          description: "Indique si le message acquitt\xE9 a \xE9t\xE9 refus\xE9"
          examples:
          - None
        errorDistributionID:
          type: string
          title: "Identifiant du message d'erreur li\xE9"
          x-health-only: false
          x-cols: 6
          example: example.json#/errorDistributionID
          description: "Identifiant unique du message d'erreur li\xE9"
          examples:
          - None
        step:
          type: string
          title: "Etape d'int\xE9gration du message"
          x-health-only: false
          x-cols: 6
          example: example.json#/step
          description: "Nomenclature permettant d'identifier les diff\xE9rentes \xE9\
            tapes d'int\xE9gration et de consultation du message dans le syst\xE8\
            me \xE9metteur"
          examples:
          - None
      additionalProperties: false
      examples:
      - distributionID: None
        refused: None
        errorDistributionID: None
        step: None
