openapi: 3.0.0
components:
  schemas:
    resourcesInfoWrapper:
      type: object
      required:
      - resourcesInfo
      properties:
        resourcesInfo:
          $ref: '#/components/schemas/resourcesInfo'
    resourcesInfo:
      $id: classpath:/json-schema/schema#
      x-id: RS-RIG.schema.json#
      example: example.json#
      type: object
      title: resourcesInfo
      required:
      - caseId
      - RSRIGId
      properties:
        caseId:
          type: string
          title: Identifiant affaire/dossier
          x-health-only: false
          x-cols: 6
          example: example.json#/caseId
          description: "Identifiant de l'affaire partag\xE9 entre tous les intervenants\
            \ = aux champs {organization}.{senderCaseId}.\nIl doit pouvoir \xEAtre\
            \ g\xE9n\xE9r\xE9 de fa\xE7on unique et d\xE9centralis\xE9e et ne pr\xE9\
            senter aucune ambigu\xEFt\xE9. \nIl est g\xE9n\xE9r\xE9 par le syst\xE8\
            me du partenaire r\xE9cepteur de la primo-demande de secours (cr\xE9ateur\
            \ du dossier).\nValorisation : {pays}.{domaine}.{organisation}.{structure\
            \ interne}*.{unit\xE9 fonctionnelle}*.{num\xE9ro de dossier}"
          examples:
          - fr.health.samu440-DRFR15DDXAAJJJ0000
        RSRIGId:
          type: string
          title: "ID partag\xE9 du message RS-RIG"
          x-health-only: false
          x-cols: 6
          example: example.json#/RSRIGId
          description: "Identifiant unique de l'Echange de Ressource concern\xE9.\
            \ Le premier qui le cr\xE9\xE9 \xE0 raison, ensuite il ne change pas.\
            \ Il s'agit du message servant \xE0 \xE9changer l'ensemble des ressources\
            \ mobilis\xE9es/engag\xE9es sur un dossier"
          examples:
          - None
        mobilizedResources:
          type: array
          items:
            $ref: '#/components/schemas/resource'
      additionalProperties: false
    resource:
      type: object
      title: "Ressource engag\xE9e"
      x-display: expansion-panels
      x-health-only: false
      required:
      - dateTime
      - resourceID
      - ownerID
      - type
      properties:
        dateTime:
          type: string
          title: "Date/heure de d\xE9clenchement"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/dateTime
          description: date et heure d'engagement de la ressource
          pattern: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\-+]\d{2}:\d{2}
          format: date-time
          examples:
          - None
        resourceID:
          type: string
          title: "ID partag\xE9"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/resourceID
          description: "ID unique de la ressource engag\xE9e"
          examples:
          - None
        ownerID:
          type: string
          title: "ID central d\u2019appel "
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/ownerID
          description: "(PSAP, \u2026) qui a d\xE9clench\xE9 le vecteur et coordonne\
            \ le vecteur"
          examples:
          - None
        missionID:
          type: string
          title: ID mission local
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/missionID
          description: "Num\xE9ro de mission du central d\u2019appel (PSAP, \u2026\
            ) qui a d\xE9clench\xE9 le vecteur"
          examples:
          - None
        type:
          type: string
          title: Type
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/type
          description: "Type de ressource mobilis\xE9e (nomenclature type de vecteur\
            \ \xE0 impl\xE9menter pour l'instant, voir ensuite si elle est compl\xE9\
            t\xE9e par des ressources autres que des vecteurs)"
          examples:
          - None
        plate:
          type: string
          title: Immatriculation
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/plate
          examples:
          - None
        name:
          type: string
          title: Nom
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/name
          description: "Nom donn\xE9 \xE0 la ressource par l\u2019organisation d\u2019\
            appartenance"
          examples:
          - None
        orgID:
          type: string
          title: "ID Organisation propri\xE9taire"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/orgID
          description: "Organisation \xE0 laquelle appartient la ressource"
          examples:
          - None
        centerName:
          type: string
          title: "ID Centre d\u2019affectation"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/centerName
          description: Lieu de garage principal
          examples:
          - None
        centerType:
          type: string
          title: "Type de centre d\u2019affectation"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/centerType
          examples:
          - None
        centerCity:
          type: string
          title: "Commune du centre d\u2019affectation"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/centerCity
          description: Code INSEE de la commune du centre d'affectation
          examples:
          - None
        make:
          type: string
          title: Marque vecteur
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/make
          description: Marque vecteur
          examples:
          - None
        model:
          type: string
          title: "Mod\xE8le vecteur"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/model
          description: "Mod\xE8le vecteur"
          examples:
          - None
        team:
          $ref: '#/components/schemas/team'
        state:
          type: array
          items:
            $ref: '#/components/schemas/state'
        coord:
          type: .nan
          title: "Derni\xE8re g\xE9olocalisation du vecteur"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/coord
          examples:
          - None
        contact:
          $ref: '#/components/schemas/contact'
        freetext:
          type: array
          x-health-only: false
          items:
            type: string
            title: Commentaires
            x-health-only: false
            x-cols: 6
            example: example.json#/mobilizedResources/0/freetext/0
            description: "Texte libre permettant de passer toute autre information\
              \ (\xE9quipements suppl\xE9mentaires / particuliers, particularit\xE9\
              s du vecteur)"
            examples:
            - None
      additionalProperties: false
      example: example.json#/mobilizedResources/0
    team:
      type: object
      title: Equipe vecteur
      x-display: expansion-panels
      x-health-only: false
      required: []
      properties:
        teamCare:
          type: string
          title: Type
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/team/teamCare
          description: "M\xE9dical / param\xE9dical : indique le niveau de m\xE9dicalisation\
            \ du vecteur"
          examples:
          - None
        name:
          type: string
          title: Nom
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/team/name
          description: "Nom de l'\xE9quipe \xE0 bord du vecteur"
          examples:
          - None
      additionalProperties: false
      example: example.json#/mobilizedResources/0/team
      examples:
      - teamCare: None
        name: None
    state:
      type: object
      title: Etats vecteur
      x-display: expansion-panels
      x-health-only: false
      required: []
      properties:
        dateTime:
          type: string
          title: Date/heure de changement de statut
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/state/0/dateTime
          pattern: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\-+]\d{2}:\d{2}
          format: date-time
          examples:
          - None
        status:
          type: string
          title: Statut du vecteur
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/state/0/status
          description: Statuts Antares
          examples:
          - None
        availability:
          type: string
          title: "Disponibilit\xE9 du vecteur"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/state/0/availability
          description: Indique si le vecteur est disponible / indisponible
          examples:
          - None
      additionalProperties: false
      example: example.json#/mobilizedResources/0/state/0
      examples:
      - dateTime: None
        status: None
        availability: None
    contact:
      type: object
      title: Contact
      x-display: expansion-panels
      x-health-only: false
      required: []
      properties:
        type:
          type: string
          title: "Type de contact du requ\xE9rant"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/contact/type
          description: "Type de l'URI utilis\xE9e"
          enum:
          - PSTADD
          - EMLADD
          - IPADD
          - FTPADD
          - WWWADD
          - PHNADD
          - FAXADD
          - PMRADD
          examples:
          - PHNADD
        details:
          type: string
          title: "URI du contact requ\xE9rant"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/contact/details
          description: "Valeur de l'URI utilis\xE9e pour contacter la ressource"
          examples:
          - 0671830530
      additionalProperties: false
      example: example.json#/mobilizedResources/0/contact
      examples:
      - type: PHNADD
        details: 0671830530
