openapi: 3.0.0
components:
  schemas:
    resourcesInfoWrapper:
      type: object
      required:
      - resourcesInfo
      properties:
        resourcesInfo:
          $ref: '#/components/schemas/resourcesInfo'
    resourcesInfo:
      $id: classpath:/json-schema/schema#
      x-id: RS-RI.schema.json#
      example: example.json#
      type: object
      title: resourcesInfo
      required:
      - caseId
      - resource
      properties:
        caseId:
          type: string
          title: Identifiant affaire/dossier
          x-health-only: false
          x-cols: 6
          example: example.json#/caseId
          description: "A valoriser avec l'identifiant partag\xE9 de l'affaire/dossier,\
            \ g\xE9n\xE9r\xE9 une seule fois par le syst\xE8me du partenaire qui recoit\
            \ la primo-demande de secours (cr\xE9ateur du dossier). \nIl est valoris\xE9\
            \ comme suit lors de sa cr\xE9ation : \n{pays}.{domaine}.{organisation}.{senderCaseId}\n\
            \nIl doit pouvoir \xEAtre g\xE9n\xE9r\xE9 de fa\xE7on d\xE9centralis\xE9\
            e et ne pr\xE9senter aucune ambigu\xEFt\xE9.\n Il doit \xEAtre unique\
            \ dans l'ensemble des syst\xE8mes : le num\xE9ro de dossier fourni par\
            \ celui qui g\xE9n\xE8re l'identifiant partag\xE9 doit donc \xEAtre un\
            \ num\xE9ro unique dans son syst\xE8me."
          pattern: ^([\w-]+\.?){4,10}$
          examples:
          - fr.health.samu440.DRFR15440241550012
        resource:
          type: array
          items:
            $ref: '#/components/schemas/resource'
          minItems: 1
      additionalProperties: false
    resource:
      type: object
      title: Ressource
      x-display: expansion-panels
      x-health-only: false
      required:
      - datetime
      - resourceId
      - vehicleType
      properties:
        datetime:
          type: string
          title: "Date/heure de d\xE9clenchement"
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/datetime
          description: A valoriser avec la date et heure d'engagement de la ressource/du
            vecteur
          pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\-+]\d{2}:\d{2}$
          format: date-time
          examples:
          - '2022-09-27T08:23:34+02:00'
        resourceId:
          type: string
          title: "ID Ressource partag\xE9"
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/resourceId
          description: "A valoriser avec l'identifiant partag\xE9 unique de la ressource\
            \ engag\xE9e, norm\xE9 comme suit :\n{orgID}.resource.{ID unique de la\
            \ ressource partag\xE9e}\nOU - uniquement dans le cas o\xF9 un ID unique\
            \ de ressource ne peut pas \xEAtre garanti par l'organisation propri\xE9\
            taire :\n{orgID}.resource.{sendercaseId}.{n\xB0 d\u2019ordre chronologique\
            \ de la ressource}"
          pattern: ^([\w-]+\.){3,8}resource(\.[\w-]+){1,2}$
          examples:
          - 'fr.health.samu770.resource.VLM250

            fr.health.samu440.resource.DRFR15DDXAAJJJ0000.1'
        requestId:
          type: string
          title: "ID Demande partag\xE9"
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/requestId
          description: "A valoriser avec l'identifiant unique partag\xE9 de la demande\
            \ de ressource (si la ressource a \xE9t\xE9 engag\xE9e suite \xE0 une\
            \ demande de ressource), norm\xE9 comme suit :\n{orgID}.request.{ID unique\
            \ de la demande dans le syst\xE8me \xE9metteur}\nOU - si un ID unique\
            \ de la demande n'\xE9tait pas disponible : \n{OrgId \xE9metteur}.request.{senderCaseId}.{num\xE9\
            ro d\u2019ordre chronologique}"
          pattern: ^([\w-]+\.){3,8}request(\.[\w-]+){1,2}$
          examples:
          - 'fr.health.samu770.request.1249875

            fr.health.samu690.request.DRFR15690242370035.3'
        missionId:
          type: string
          title: ID Mission local
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/missionId
          description: "A valoriser avec le num\xE9ro de mission unique du central\
            \ d\u2019appel (PSAP, \u2026) qui a d\xE9clench\xE9 le vecteur"
          examples:
          - DRFR15DDXAAJJJ0000.M001
        orgId:
          type: string
          title: "ID Organisation propri\xE9taire"
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/orgId
          description: "A valoriser avec l'identifiant de l'organisation \xE0 laquelle\
            \ appartient la ressource, norm\xE9 comme suit : \n{pays}.{domaine}.{organisation}"
          examples:
          - fr.health.samu440
        patientId:
          type: string
          title: "ID partag\xE9 du patient transport\xE9"
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/patientId
          description: "Identifiant partag\xE9 du patient qui est transport\xE9. Ce\
            \ n'est \xE0 remplir que lorsque l'on sait quel vecteur transporte quel\
            \ patient. \nIl est valoris\xE9 comme suit lors de sa cr\xE9ation : \n\
            {OrgId \xE9metteur}.patient.{n\xB0patient unique dans le syst\xE8me \xE9\
            metteur}\n\nOU, si un n\xB0patient unique n'existe pas dans le syst\xE8\
            me \xE9metteur :\n{ID \xE9metteur}.{senderCaseId}.patient.{num\xE9ro d\u2019\
            ordre chronologique au dossier}"
          examples:
          - fr.health.samu440.patient.P23AZ59
        centerName:
          type: string
          title: "Nom du centre d\u2019affectation"
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/centerName
          description: A valoriser avec le lieu de garage principal
          examples:
          - CHU Nantes
        vehicleType:
          type: string
          title: Type de vecteur
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/vehicleType
          description: "A valoriser avec le type de vecteur mobilis\xE9 : cf. nomenclature\
            \ associ\xE9e"
          enum:
          - AASC
          - AASC.VLSC
          - AASC.VPSP
          - AASC.AUTRESC
          - AUTREVEC
          - AUTREVEC.APIED
          - AUTREVEC.AVION
          - AUTREVEC.PERSO
          - AUTREVEC.TAXI
          - AUTREVEC.TRAIN
          - AUTREVEC.TRANSP
          - AUTREVEC.AUTRE
          - AUTREVEC.AUTRETRA
          - FSI
          - FSI.HELIFSI
          - FSI.VLFSI
          - FSI.FFSI
          - FSI.VHFSI
          - LIB
          - LIB.MEDV
          - LIB.INF
          - LIB.AUTREPRO
          - SIS
          - SIS.DRAGON
          - SIS.AVSC
          - SIS.FEUSIS
          - SIS.GRIMP
          - SIS.NAVISIS
          - SIS.PCSIS
          - SIS.SRSIS
          - SIS.VCH
          - SIS.VLCG
          - SIS.VLISP
          - SIS.VLMSP
          - SIS.VLSIS
          - SIS.VPL
          - SIS.VPMA
          - SIS.VR
          - SIS.VSAV
          - SIS.MOYSSE
          - SIS.AUTRESIS
          - SMUR
          - SMUR.VLM
          - SMUR.VL
          - SMUR.PSM1
          - SMUR.PSM2
          - SMUR.PSM3
          - SMUR.PSMP
          - SMUR.VPC
          - SMUR.AR
          - SMUR.AR-BAR
          - SMUR.AR-PED
          - SMUR.HELISMUR
          - SMUR.HELISAN
          - SMUR.AVSMUR
          - SMUR.AVSAN
          - SMUR.NAVISMUR
          - TSU
          - TSU.VSL
          - TSU.AMB-GV
          - TSU.AMB-PV
          - TSU.AMB-BAR
          - TSU.AMB
          examples:
          - VLM
        name:
          type: string
          title: Nom du vecteur
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/name
          description: "A valoriser avec le nom donn\xE9 \xE0 la ressource par l\u2019\
            organisation d\u2019appartenance"
          examples:
          - SMUR 123
        centerCity:
          type: string
          title: "Commune du centre d\u2019affectation"
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/centerCity
          description: A valoriser avec le code INSEE de la commune du centre d'affectation
          pattern: ^[0-9]{5}$
          examples:
          - 44109
        team:
          $ref: '#/components/schemas/team'
        state:
          type: array
          items:
            $ref: '#/components/schemas/state'
        contact:
          $ref: '#/components/schemas/contact'
        freetext:
          type: array
          x-health-only: false
          items:
            type: string
            title: Commentaires
            x-health-only: false
            x-cols: 6
            example: example.json#/resource/0/freetext/0
            description: "Texte libre permettant de passer toute autre information\
              \ sur la ressource (\xE9quipements suppl\xE9mentaires / sp\xE9cifiques,\
              \ particularit\xE9s du vecteur, etc.)"
            examples:
            - "SMUR p\xE9diatrique"
      additionalProperties: false
      example: example.json#/resource/0
    team:
      type: object
      title: Equipe vecteur
      x-display: expansion-panels
      x-health-only: false
      required: []
      properties:
        medicalLevel:
          type: string
          title: Type
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/team/medicalLevel
          description: "A valoriser avec le  niveau de m\xE9dicalisation du vecteur.\
            \ Cf. nomenclature associ\xE9e"
          enum:
          - MED
          - PARAMED
          - SECOURS
          - SANS
          examples:
          - MED
        name:
          type: string
          title: Nom
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/team/name
          description: "A valoriser avec le nom de l'\xE9quipe \xE0 bord du vecteur\
            \ (celui communiqu\xE9 par l'organisation \xE0 laquelle l'\xE9quipe appartient)"
          examples:
          - Equipe A
      additionalProperties: false
      example: example.json#/resource/0/team
      examples:
      - medicalLevel: MED
        name: Equipe A
    state:
      type: object
      title: Etat vecteur
      x-display: expansion-panels
      x-health-only: false
      required:
      - datetime
      - status
      properties:
        datetime:
          type: string
          title: Date/heure de changement de statut
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/state/0/datetime
          description: A valoriser avec la date et heure d'engagement de changement
            vers le nouveau statut
          pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\-+]\d{2}:\d{2}$
          format: date-time
          examples:
          - '2022-09-27T08:23:34+02:00'
        status:
          type: string
          title: Statut du vecteur
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/state/0/status
          description: "A valoriser avec le statut du vecteur. Cf nomenclature associ\xE9\
            e."
          enum:
          - DECISION
          - DECLENCHE
          - DEPART
          - ANNULE
          - ARRIVEE
          - PEC
          - BILAN
          - ORIENTAT
          - TRANSP
          - ETAPE1
          - TRANSP2
          - ETAPE2
          - TRANSP3
          - DESTIN
          - FINPEC
          - RETOUR
          - RET-BASE
          - REN-BASE
          examples:
          - ARRIVE
        availability:
          type: boolean
          title: "Disponibilit\xE9 du vecteur"
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/state/0/availability
          description: "A valoriser de mani\xE8re \xE0 indiquer la disponibilit\xE9\
            \ du vecteur.\nTRUE = DISPONIBLE\nFALSE = INDISPONIBLE\nVIDE = INCONNU"
          examples:
          - 'FALSE'
      additionalProperties: false
      example: example.json#/resource/0/state/0
      examples:
      - datetime: '2022-09-27T08:23:34+02:00'
        status: ARRIVE
        availability: 'FALSE'
    contact:
      type: object
      title: Contact
      x-display: expansion-panels
      x-health-only: false
      required: []
      properties:
        type:
          type: string
          title: 'Type de contact '
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/contact/type
          description: "A valoriser avec le type de l'URI utilis\xE9e. Cf nomenclature\
            \ associ\xE9e."
          enum:
          - EMAIL
          - FAX
          - MSS
          - POSTAL
          - RADIO
          - TEL
          - WEB
          examples:
          - PHNADD
        details:
          type: string
          title: URI du contact
          x-health-only: false
          x-cols: 6
          example: example.json#/resource/0/contact/details
          description: "A valoriser avec la valeur de l'URI utilis\xE9e\nLe format\
            \ attendu pour un num\xE9ro de t\xE9l\xE9phone est le suivant : +{indicatif\
            \ pays}{num\xE9ro de t\xE9l\xE9phone}"
          examples:
          - '+33671830530'
      additionalProperties: false
      example: example.json#/resource/0/contact
      examples:
      - type: PHNADD
        details: '+33671830530'
