openapi: 3.0.0
components:
  schemas:
    resourcesResponseWrapper:
      type: object
      required:
      - resourcesResponse
      properties:
        resourcesResponse:
          $ref: '#/components/schemas/resourcesResponse'
    resourcesResponse:
      $id: classpath:/json-schema/schema#
      x-id: RS-RDR.schema.json#
      example: example.json#
      type: object
      title: resourcesResponse
      required:
      - caseId
      - RSDDRId
      properties:
        caseId:
          type: string
          title: Identifiant affaire/dossier
          x-health-only: false
          x-cols: 6
          example: example.json#/caseId
          description: "Identifiant de l'affaire partag\xE9 entre tous les intervenants\
            \ = aux champs {organization}.{senderCaseId}.\nIl doit pouvoir \xEAtre\
            \ g\xE9n\xE9r\xE9 de fa\xE7on unique et d\xE9centralis\xE9e et ne pr\xE9\
            senter aucune ambigu\xEFt\xE9. \nIl est g\xE9n\xE9r\xE9 par le syst\xE8\
            me du partenaire r\xE9cepteur de la primo-demande de secours (cr\xE9ateur\
            \ du dossier).\nValorisation : {pays}.{domaine}.{organisation}.{structure\
            \ interne}*.{unit\xE9 fonctionnelle}*.{num\xE9ro de dossier}"
          examples:
          - fr.health.samu440.DRFR15DDXAAJJJ0000
        RSDDRId:
          type: string
          title: "ID DDR partag\xE9"
          x-health-only: false
          x-cols: 6
          example: example.json#/RSDDRId
          description: "Identifiant unique partag\xE9 de la demande de ressource \xE0\
            \ laquelle l'exp\xE9diteur r\xE9pond"
          examples:
          - None
        resourceRequest:
          $ref: '#/components/schemas/request'
        mobilizedResources:
          type: array
          items:
            $ref: '#/components/schemas/resource'
      additionalProperties: false
    request:
      type: object
      title: "R\xE9ponse \xE0 la demande de concours"
      x-display: expansion-panels
      x-health-only: false
      required:
      - dateTime
      - answer
      properties:
        dateTime:
          type: string
          title: "Date Heure de r\xE9ponse"
          x-health-only: false
          x-cols: 6
          example: example.json#/resourceRequest/dateTime
          description: "Voir liste des effets \xE0 obtenir identifi\xE9s"
          pattern: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\-+]\d{2}:\d{2}
          format: date-time
          examples:
          - None
        answer:
          type: string
          title: "R\xE9ponse"
          x-health-only: false
          x-cols: 6
          example: example.json#/resourceRequest/answer
          description: "oui / non / oui partiel / diff\xE9r\xE9"
          examples:
          - None
        deadline:
          type: string
          title: "D\xE9lai de r\xE9ponse"
          x-health-only: false
          x-cols: 6
          example: example.json#/resourceRequest/deadline
          description: "Indique le d\xE9lai de r\xE9ponse auquel s'engage l'exp\xE9\
            diteur"
          examples:
          - None
        freetext:
          type: string
          title: "Pr\xE9cisions sur la r\xE9ponse"
          x-health-only: false
          x-cols: 6
          example: example.json#/resourceRequest/freetext
          description: "Commentaire libre pour apporter toutes pr\xE9cisions utiles\
            \ \xE0 la r\xE9ponse"
          examples:
          - None
      additionalProperties: false
      example: example.json#/resourceRequest
      examples:
      - dateTime: None
        answer: None
        deadline: None
        freetext: None
    resource:
      type: object
      title: "Ressource engag\xE9e"
      x-display: expansion-panels
      x-health-only: false
      required:
      - commitmentDateTime
      - resourceID
      - resourceType
      properties:
        commitmentDateTime:
          type: string
          title: "Date/heure de d\xE9clenchement"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/commitmentDateTime
          description: date et heure d'engagement de la ressource
          pattern: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\-+]\d{2}:\d{2}
          format: date-time
          examples:
          - None
        originDateTime:
          type: string
          title: "Date/heure pr\xE9visionnelle d'arriv\xE9e au lieu d'intervention\
            \ / lieu d'origine"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/originDateTime
          description: "date et heure d'arriv\xE9e pr\xE9visionnelle sur le lieu de\
            \ prise en charge du patient"
          pattern: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\-+]\d{2}:\d{2}
          format: date-time
          examples:
          - None
        destinationDateTime:
          type: string
          title: "Date/heure pr\xE9visionnelle d'arriv\xE9e au lieu de destination"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/destinationDateTime
          description: "date et heure d'arriv\xE9e pr\xE9visionnelle sur le lieu de\
            \ destination du patient"
          pattern: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\-+]\d{2}:\d{2}
          format: date-time
          examples:
          - None
        resourceID:
          type: string
          title: "ID partag\xE9"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/resourceID
          description: "ID unique de la ressource engag\xE9e partag\xE9e \n{orgID}.{ID\
            \ du dossier partag\xE9}.R{num\xE9ro d\u2019ordre chronologique}"
          examples:
          - fr.health.samu440.DRFR15DDXAAJJJ0000.R01
        orgID:
          type: string
          title: "Identifiant de l'organisation propri\xE9taire"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/orgID
          description: "Organisation \xE0 laquelle appartient la ressource"
          examples:
          - fr.health.samu440
        resourceType:
          type: string
          title: Type de ressource
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/resourceType
          description: "Type de ressource mobilis\xE9e : Smur, Hospitaliers (hors\
            \ Smur), Professionnels Lib\xE9raux, Ambulanciers priv\xE9s (Transporteurs\
            \ Sanitaires Urgent), etc."
          enum:
          - SMUR
          - HOSPIT
          - LIB
          - 'TSU '
          - SIS
          - AASC
          - FDO
          - ADM
          - DAE
          - AUTRE
          examples:
          - SMUR
        vehiculeType:
          type: string
          title: Type de vecteur
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/vehiculeType
          description: "Type de vecteur mobilis\xE9 : V\xE9hicule L\xE9ger M\xE9dicalis\xE9\
            , Ambulance de r\xE9animation, Ambulance de r\xE9animation Bariatrique,\
            \ Ambulance de r\xE9animation P\xE9diatrique, etc."
          enum:
          - VPSP
          - VLSC
          - AUTRESC
          - TAXI
          - TRANSP
          - AUTRE
          - TRAIN
          - AVION
          - PERSO
          - APIED
          - INCONNU
          - CONSEIL
          - DAE
          - HELIFSI
          - VLFSI
          - FFSI
          - VHFSI
          - MEDC
          - MEDV
          - PHARMA
          - INF
          - MEDSPE
          - DENT
          - AUTREPRO
          - DRAGON
          - AVSC
          - VSAV
          - GRIMP
          - VPL
          - SRSIS
          - FEUSIS
          - VPMA
          - VCH
          - VR
          - PCSIS
          - VLISP
          - VLMSP
          - VLCG
          - VLSIS
          - MOYSSE
          - AUTRESIS
          - VLM
          - AR
          - AR-BAR
          - AR-PED
          - VL
          - HELISMUR
          - HELISAN
          - AVSMUR
          - AVSAN
          - NAVISMUR
          - PSM1
          - PSM2
          - PSM3
          - PSMP
          - VPC
          - AMB-GV
          - AMB-PV
          - AMB-BAR
          - AMB
          - VSL
          - NAVISIS
          examples:
          - VLM
        plate:
          type: string
          title: Immatriculation
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/plate
          examples:
          - None
        name:
          type: string
          title: Nom
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/name
          description: "Nom donn\xE9 par l\u2019organisation d\u2019appartenance"
          examples:
          - None
        order:
          type: string
          title: "N\xB0 d'ordre de la ressource"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/order
          description: "S'il existe plusieurs types de vecteurs ou ressource identiques\
            \ portant le m\xEAme nom dans un m\xEAme dans le m\xEAme centre d\u2019\
            affectation; pr\xE9ciser le num\xE9ro d'ordre"
          examples:
          - None
        centerName:
          type: string
          title: "Centre d\u2019affectation"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/centerName
          description: Lieu de garage principal
          examples:
          - None
        centerCity:
          type: string
          title: "Commune du centre d\u2019affectation"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/centerCity
          description: Code INSEE de la commune du centre d'affectation
          examples:
          - None
        make:
          type: string
          title: Marque vecteur
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/make
          description: Marque vecteur
          examples:
          - None
        model:
          type: string
          title: "Mod\xE8le vecteur"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/model
          description: "Mod\xE8le vecteur"
          examples:
          - None
        team:
          $ref: '#/components/schemas/team'
        state:
          $ref: '#/components/schemas/state'
        contact:
          $ref: '#/components/schemas/contact'
      additionalProperties: false
      example: example.json#/mobilizedResources/0
    team:
      type: object
      title: Equipe vecteur
      x-display: expansion-panels
      x-health-only: false
      required: []
      properties:
        type:
          type: string
          title: Type
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/team/type
          description: "M\xE9dical / param\xE9dical : indique le niveau de m\xE9dicalisation\
            \ du vecteur"
          enum:
          - MED
          - PARAMED
          - SECOURS
          examples:
          - None
        name:
          type: string
          title: Nom
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/team/name
          description: "Nom de l'\xE9quipe \xE0 bord du vecteur"
          examples:
          - None
      additionalProperties: false
      example: example.json#/mobilizedResources/0/team
      examples:
      - type: None
        name: None
    state:
      type: object
      title: Etat vecteur
      x-display: expansion-panels
      x-health-only: false
      required: []
      properties:
        dateTime:
          type: string
          title: Date/heure de changement de statut
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/state/dateTime
          pattern: \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\-+]\d{2}:\d{2}
          format: date-time
          examples:
          - None
        status:
          type: string
          title: Statut du vecteur
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/state/status
          description: Statuts Antares
          examples:
          - 'ENUM : Alerte, Parti, Arrivee Sur Les Lieux, Transport Destination, Arrivee
            Destination, Fin De Medicalisation , Quitte Destination, Retour Base,
            Rentree Base'
        availability:
          type: string
          title: "Disponibilit\xE9 du vecteur"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/state/availability
          description: Indique si le vecteur est disponible / indisponible
          examples:
          - 'ENUM : Disponible, Indisponible, Inconnu'
      additionalProperties: false
      example: example.json#/mobilizedResources/0/state
      examples:
      - dateTime: None
        status: 'ENUM : Alerte, Parti, Arrivee Sur Les Lieux, Transport Destination,
          Arrivee Destination, Fin De Medicalisation , Quitte Destination, Retour
          Base, Rentree Base'
        availability: 'ENUM : Disponible, Indisponible, Inconnu'
    contact:
      type: object
      title: Contact
      x-display: expansion-panels
      x-health-only: false
      required: []
      properties:
        type:
          type: string
          title: "Type de contact du requ\xE9rant"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/contact/type
          description: "Type de l'URI utilis\xE9e"
          enum:
          - PSTADD
          - EMLADD
          - IPADD
          - FTPADD
          - WWWADD
          - PHNADD
          - FAXADD
          - PMRADD
          examples:
          - PHNADD
        details:
          type: string
          title: "URI du contact requ\xE9rant"
          x-health-only: false
          x-cols: 6
          example: example.json#/mobilizedResources/0/contact/details
          description: "Valeur de l'URI utilis\xE9e pour contacter la ressource"
          examples:
          - 0671830530
      additionalProperties: false
      example: example.json#/mobilizedResources/0/contact
      examples:
      - type: PHNADD
        details: 0671830530
