openapi: 3.0.0
components:
  schemas:
    resourcesStatusWrapper:
      type: object
      required:
      - resourcesStatus
      properties:
        resourcesStatus:
          $ref: '#/components/schemas/resourcesStatus'
    resourcesStatus:
      $id: classpath:/json-schema/schema#
      x-id: RS-SR.schema.json#
      example: example.json#
      type: object
      title: resourcesStatus
      required:
      - caseId
      - resourceId
      - state
      properties:
        caseId:
          type: string
          title: Identifiant affaire/dossier
          x-health-only: false
          x-cols: 6
          example: example.json#/caseId
          description: "A valoriser avec l'identifiant partag\xE9 de l'affaire/dossier,\
            \ g\xE9n\xE9r\xE9 une seule fois par le syst\xE8me du partenaire qui recoit\
            \ la primo-demande de secours (cr\xE9ateur du dossier). \nIl est valoris\xE9\
            \ comme suit lors de sa cr\xE9ation : \n{pays}.{domaine}.{organisation}.{senderCaseId}\n\
            \nIl doit pouvoir \xEAtre g\xE9n\xE9r\xE9 de fa\xE7on d\xE9centralis\xE9\
            e et ne pr\xE9senter aucune ambigu\xEFt\xE9.\n Il doit \xEAtre unique\
            \ dans l'ensemble des syst\xE8mes : le num\xE9ro de dossier fourni par\
            \ celui qui g\xE9n\xE8re l'identifiant partag\xE9 doit donc \xEAtre un\
            \ num\xE9ro unique dans son syst\xE8me."
          pattern: ^([a-zA-Z0-9_-]+\.?){4,10}$
          examples:
          - fr.health.samu440.DRFR15440241550012
        resourceId:
          type: string
          title: "ID Ressource partag\xE9"
          x-health-only: false
          x-cols: 6
          example: example.json#/resourceId
          description: "A valoriser avec l'identifiant partag\xE9 unique de la ressource\
            \ engag\xE9e , norm\xE9 comme suit :\n{orgID}.R.{ID unique de la ressource\
            \ partag\xE9e}\nOu, uniquement dans le cas o\xF9 un ID unique de ressource\
            \ ne peut pas \xEAtre garanti par l'organisation propri\xE9taire :\n{orgID}.R.{ID\
            \ du dossier partag\xE9}.{num\xE9ro d\u2019ordre chronologique ressource}\n\
            \nN.B. Il s'agit de l'orgId de l'organisation \xE0 qui appartient la ressource"
          pattern: ^([a-zA-Z0-9_-]+\.){3,8}resource(\.[a-zA-Z0-9_-]+){1,2}$
          examples:
          - 'fr.health.samu770.resource.VLM250 ;

            fr.health.samu440.resource.DRFR15DDXAAJJJ0000.1'
        state:
          $ref: '#/components/schemas/state'
      additionalProperties: false
    state:
      type: object
      title: Etat vecteur
      x-display: expansion-panels
      x-health-only: false
      required:
      - datetime
      - status
      properties:
        datetime:
          type: string
          title: Date/heure de changement de statut
          x-health-only: false
          x-cols: 6
          example: example.json#/state/datetime
          description: A valoriser avec la date et heure d'engagement de changement
            vers le nouveau statut
          pattern: ^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}[\-+]\d{2}:\d{2}$
          format: date-time
          examples:
          - '2022-09-27T08:23:34+02:00'
        status:
          type: string
          title: Statut du vecteur
          x-health-only: false
          x-cols: 6
          example: example.json#/state/status
          description: "A valoriser avec le statut du vecteur. Cf nomenclature associ\xE9\
            e."
          enum:
          - DECISION
          - DECLENCHE
          - DEPART
          - ANNULE
          - ARRIVEE
          - PEC
          - BILAN
          - ORIENTAT
          - TRANSP
          - ETAPE1
          - TRANSP2
          - ETAPE2
          - TRANSP3
          - DESTIN
          - FINPEC
          - RETOUR
          - RET-BASE
          - REN-BASE
          examples:
          - ARRIVE
        availability:
          type: boolean
          title: "Disponibilit\xE9 du vecteur"
          x-health-only: false
          x-cols: 6
          example: example.json#/state/availability
          description: "A valoriser de mani\xE8re \xE0 indiquer la disponibilit\xE9\
            \ du vecteur.\nTRUE = DISPONIBLE\nFALSE = INDISPONIBLE\nVIDE = INCONNU"
          examples:
          - 'FALSE'
      additionalProperties: false
      example: example.json#/state
      examples:
      - datetime: '2022-09-27T08:23:34+02:00'
        status: ARRIVE
        availability: 'FALSE'
