openapi: 3.0.0
components:
  schemas:
    technicalWrapper:
      type: object
      required:
      - technical
      properties:
        technical:
          $ref: '#/components/schemas/technical'
    technical:
      $id: classpath:/json-schema/schema#
      x-id: TECHNICAL.schema.json#
      example: example.json#
      type: object
      title: technical
      required:
      - requiredStringField
      properties:
        requiredStringField:
          type: string
          title: Required string
          x-health-only: false
          x-cols: 6
          example: example.json#/requiredStringField
          description: This field is required
          examples:
          - None
        optionalStringField:
          type: string
          title: Optional string
          x-health-only: false
          x-cols: 6
          example: example.json#/optionalStringField
          description: This field is optional
          examples:
          - None
        enumerationField:
          type: string
          title: Enumeration
          x-health-only: false
          x-cols: 6
          example: example.json#/enumerationField
          description: This is an enumeration
          enum:
          - REPORT
          - UPDATE
          - CANCEL
          - ACK
          - ERROR
          examples:
          - None
        numberField:
          type: number
          title: Optional number
          x-health-only: false
          x-cols: 6
          example: example.json#/numberField
          description: This is a number
          examples:
          - None
        objectField:
          type: technicalObject
          title: Object
          x-health-only: false
          x-cols: 6
          example: example.json#/objectField
          description: This is an object
          examples:
          - None
      additionalProperties: false
      examples:
      - requiredStringField: None
        optionalStringField: None
        enumerationField: None
        numberField: None
        objectField: None
