<?php
/**
 * Etype
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hubsante
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hubsante\Model\emsi;

use \ArrayAccess;
use \Hubsante\ObjectSerializer;

/**
 * Etype Class Doc Comment
 *
 * @category Class
 * @package  Hubsante
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Etype implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'etype';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'cATEGORY' => 'string[]',
        'aCTOR' => 'string[]',
        'lOCTYPE' => 'string[]',
        'eNV' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'cATEGORY' => null,
        'aCTOR' => null,
        'lOCTYPE' => null,
        'eNV' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'cATEGORY' => false,
        'aCTOR' => false,
        'lOCTYPE' => false,
        'eNV' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cATEGORY' => 'CATEGORY',
        'aCTOR' => 'ACTOR',
        'lOCTYPE' => 'LOCTYPE',
        'eNV' => 'ENV'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cATEGORY' => 'setCATEGORY',
        'aCTOR' => 'setACTOR',
        'lOCTYPE' => 'setLOCTYPE',
        'eNV' => 'setENV'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cATEGORY' => 'getCATEGORY',
        'aCTOR' => 'getACTOR',
        'lOCTYPE' => 'getLOCTYPE',
        'eNV' => 'getENV'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const C_ATEGORY_ASB = 'ASB';
    public const C_ATEGORY_ASR = 'ASR';
    public const C_ATEGORY_EXP = 'EXP';
    public const C_ATEGORY_FIR = 'FIR';
    public const C_ATEGORY_FLD = 'FLD';
    public const C_ATEGORY_GND = 'GND';
    public const C_ATEGORY_HLT = 'HLT';
    public const C_ATEGORY_POL = 'POL';
    public const C_ATEGORY_PSW = 'PSW';
    public const C_ATEGORY_TRP = 'TRP';
    public const C_ATEGORY_ASB_ABV = 'ASB/ABV';
    public const C_ATEGORY_ASR_ATM = 'ASR/ATM';
    public const C_ATEGORY_ASR_HGT = 'ASR/HGT';
    public const C_ATEGORY_ASR_ICE = 'ASR/ICE';
    public const C_ATEGORY_ASR_MAR = 'ASR/MAR';
    public const C_ATEGORY_ASR_SIL = 'ASR/SIL';
    public const C_ATEGORY_ASR_TRP = 'ASR/TRP';
    public const C_ATEGORY_ASR_UDG = 'ASR/UDG';
    public const C_ATEGORY_ASR_WAT = 'ASR/WAT';
    public const C_ATEGORY_EXP_AER = 'EXP/AER';
    public const C_ATEGORY_EXP_AMM = 'EXP/AMM';
    public const C_ATEGORY_EXP_BLEVE = 'EXP/BLEVE';
    public const C_ATEGORY_EXP_CHM = 'EXP/CHM';
    public const C_ATEGORY_EXP_CYL = 'EXP/CYL';
    public const C_ATEGORY_EXP_DST = 'EXP/DST';
    public const C_ATEGORY_EXP_FRW = 'EXP/FRW';
    public const C_ATEGORY_EXP_GAS = 'EXP/GAS';
    public const C_ATEGORY_EXP_HGHFLM = 'EXP/HGHFLM';
    public const C_ATEGORY_EXP_HPP = 'EXP/HPP';
    public const C_ATEGORY_EXP_IMP = 'EXP/IMP';
    public const C_ATEGORY_EXP_LPG = 'EXP/LPG';
    public const C_ATEGORY_EXP_NUK = 'EXP/NUK';
    public const C_ATEGORY_EXP_PRD = 'EXP/PRD';
    public const C_ATEGORY_EXP_UKN = 'EXP/UKN';
    public const C_ATEGORY_FIR_CLA = 'FIR/CLA';
    public const C_ATEGORY_FIR_CLB = 'FIR/CLB';
    public const C_ATEGORY_FIR_CLC = 'FIR/CLC';
    public const C_ATEGORY_FIR_CLD = 'FIR/CLD';
    public const C_ATEGORY_FIR_UKN = 'FIR/UKN';
    public const C_ATEGORY_FLD_FLS = 'FLD/FLS';
    public const C_ATEGORY_FLD_PLN = 'FLD/PLN';
    public const C_ATEGORY_FLD_TID = 'FLD/TID';
    public const C_ATEGORY_GND_AVL = 'GND/AVL';
    public const C_ATEGORY_GND_EQK = 'GND/EQK';
    public const C_ATEGORY_GND_GEY = 'GND/GEY';
    public const C_ATEGORY_GND_LDS = 'GND/LDS';
    public const C_ATEGORY_GND_MUD = 'GND/MUD';
    public const C_ATEGORY_GND_SUB = 'GND/SUB';
    public const C_ATEGORY_GND_VUL = 'GND/VUL';
    public const C_ATEGORY_HLT_EPI = 'HLT/EPI';
    public const C_ATEGORY_HLT_FMN = 'HLT/FMN';
    public const C_ATEGORY_HLT_NDS = 'HLT/NDS';
    public const C_ATEGORY_POL_BIO = 'POL/BIO';
    public const C_ATEGORY_POL_CHM = 'POL/CHM';
    public const C_ATEGORY_POL_NUK = 'POL/NUK';
    public const C_ATEGORY_POL_RAD = 'POL/RAD';
    public const C_ATEGORY_PSW_ALM = 'PSW/ALM';
    public const C_ATEGORY_PSW_ASY = 'PSW/ASY';
    public const C_ATEGORY_PSW_DEM = 'PSW/DEM';
    public const C_ATEGORY_PSW_IMM = 'PSW/IMM';
    public const C_ATEGORY_PSW_MEV = 'PSW/MEV';
    public const C_ATEGORY_PSW_MIS = 'PSW/MIS';
    public const C_ATEGORY_PSW_PKG = 'PSW/PKG';
    public const C_ATEGORY_PSW_PRO = 'PSW/PRO';
    public const C_ATEGORY_PSW_PRSUIT = 'PSW/PRSUIT';
    public const C_ATEGORY_PSW_RIOT = 'PSW/RIOT';
    public const C_ATEGORY_PSW_SUS = 'PSW/SUS';
    public const C_ATEGORY_PSW_WNG = 'PSW/WNG';
    public const C_ATEGORY_TRP_BRK = 'TRP/BRK';
    public const C_ATEGORY_TRP_COL = 'TRP/COL';
    public const C_ATEGORY_TRP_CRS = 'TRP/CRS';
    public const A_CTOR_ANI = 'ANI';
    public const A_CTOR_BEV = 'BEV';
    public const A_CTOR_PPL = 'PPL';
    public const A_CTOR_VEH = 'VEH';
    public const A_CTOR_ANI_CON = 'ANI/CON';
    public const A_CTOR_ANI_DEA = 'ANI/DEA';
    public const A_CTOR_ANI_DGR = 'ANI/DGR';
    public const A_CTOR_ANI_FRM = 'ANI/FRM';
    public const A_CTOR_ANI_HRD = 'ANI/HRD';
    public const A_CTOR_ANI_INJ = 'ANI/INJ';
    public const A_CTOR_ANI_LIV = 'ANI/LIV';
    public const A_CTOR_ANI_PET = 'ANI/PET';
    public const A_CTOR_ANI_PRO = 'ANI/PRO';
    public const A_CTOR_ANI_SPC = 'ANI/SPC';
    public const A_CTOR_ANI_WLD = 'ANI/WLD';
    public const A_CTOR_BEV_ASR = 'BEV/ASR';
    public const A_CTOR_BEV_IND = 'BEV/IND';
    public const A_CTOR_BEV_NRES = 'BEV/NRES';
    public const A_CTOR_BEV_OFF = 'BEV/OFF';
    public const A_CTOR_BEV_OTH = 'BEV/OTH';
    public const A_CTOR_BEV_RESDW = 'BEV/RESDW';
    public const A_CTOR_BEV_RESIN = 'BEV/RESIN';
    public const A_CTOR_BEV_RESINT = 'BEV/RESINT';
    public const A_CTOR_BEV_RESOTH = 'BEV/RESOTH';
    public const A_CTOR_BEV_SHP = 'BEV/SHP';
    public const A_CTOR_PPL_1 = 'PPL/1';
    public const A_CTOR_PPL_ADU = 'PPL/ADU';
    public const A_CTOR_PPL_CHD = 'PPL/CHD';
    public const A_CTOR_PPL_CNT = 'PPL/CNT';
    public const A_CTOR_PPL_DED = 'PPL/DED';
    public const A_CTOR_PPL_EVC = 'PPL/EVC';
    public const A_CTOR_PPL_GND = 'PPL/GND';
    public const A_CTOR_PPL_GRP = 'PPL/GRP';
    public const A_CTOR_PPL_HST = 'PPL/HST';
    public const A_CTOR_PPL_INT = 'PPL/INT';
    public const A_CTOR_PPL_OTH = 'PPL/OTH';
    public const A_CTOR_PPL_PRS = 'PPL/PRS';
    public const A_CTOR_PPL_SNS = 'PPL/SNS';
    public const A_CTOR_PPL_VIO = 'PPL/VIO';
    public const A_CTOR_PPL_VLN = 'PPL/VLN';
    public const A_CTOR_PPL_WTN = 'PPL/WTN';
    public const A_CTOR_PPL_CHD_BAB = 'PPL/CHD/BAB';
    public const A_CTOR_PPL_CHD_CHILD = 'PPL/CHD/CHILD';
    public const A_CTOR_PPL_CHD_INF = 'PPL/CHD/INF';
    public const A_CTOR_PPL_CHD_YOUTH = 'PPL/CHD/YOUTH';
    public const A_CTOR_PPL_GND_FML = 'PPL/GND/FML';
    public const A_CTOR_PPL_GND_MAL = 'PPL/GND/MAL';
    public const A_CTOR_PPL_GND_UND = 'PPL/GND/UND';
    public const A_CTOR_PPL_HST_PCF = 'PPL/HST/PCF';
    public const A_CTOR_PPL_HST_SUI = 'PPL/HST/SUI';
    public const A_CTOR_PPL_HST_THT = 'PPL/HST/THT';
    public const A_CTOR_PPL_HST_WPN = 'PPL/HST/WPN';
    public const A_CTOR_PPL_PRS_CST = 'PPL/PRS/CST';
    public const A_CTOR_PPL_PRS_ESC = 'PPL/PRS/ESC';
    public const A_CTOR_PPL_PRS_HGS = 'PPL/PRS/HGS';
    public const A_CTOR_PPL_SNS_ETH = 'PPL/SNS/ETH';
    public const A_CTOR_PPL_SNS_FOR = 'PPL/SNS/FOR';
    public const A_CTOR_PPL_SNS_LAN = 'PPL/SNS/LAN';
    public const A_CTOR_PPL_SNS_REL = 'PPL/SNS/REL';
    public const A_CTOR_PPL_SNS_VIP = 'PPL/SNS/VIP';
    public const A_CTOR_PPL_VLN_BLD = 'PPL/VLN/BLD';
    public const A_CTOR_PPL_VLN_DEF = 'PPL/VLN/DEF';
    public const A_CTOR_PPL_VLN_DSB = 'PPL/VLN/DSB';
    public const A_CTOR_PPL_VLN_ELD = 'PPL/VLN/ELD';
    public const A_CTOR_PPL_VLN_INJ = 'PPL/VLN/INJ';
    public const A_CTOR_PPL_VLN_LDF = 'PPL/VLN/LDF';
    public const A_CTOR_PPL_VLN_OBS = 'PPL/VLN/OBS';
    public const A_CTOR_PPL_VLN_PAT = 'PPL/VLN/PAT';
    public const A_CTOR_PPL_VLN_PGN = 'PPL/VLN/PGN';
    public const A_CTOR_PPL_VLN_SLFPRS = 'PPL/VLN/SLFPRS';
    public const A_CTOR_PPL_VLN_UNC = 'PPL/VLN/UNC';
    public const A_CTOR_VEH_AIR = 'VEH/AIR';
    public const A_CTOR_VEH_ANI = 'VEH/ANI';
    public const A_CTOR_VEH_BIC = 'VEH/BIC';
    public const A_CTOR_VEH_CAR = 'VEH/CAR';
    public const A_CTOR_VEH_EMG = 'VEH/EMG';
    public const A_CTOR_VEH_MBK = 'VEH/MBK';
    public const A_CTOR_VEH_MIL = 'VEH/MIL';
    public const A_CTOR_VEH_OTH = 'VEH/OTH';
    public const A_CTOR_VEH_TRK = 'VEH/TRK';
    public const A_CTOR_VEH_TRN = 'VEH/TRN';
    public const A_CTOR_VEH_VES = 'VEH/VES';
    public const A_CTOR_VEH_AIR_ARM = 'VEH/AIR/ARM';
    public const A_CTOR_VEH_AIR_FLBA = 'VEH/AIR/FLBA';
    public const A_CTOR_VEH_AIR_FRG = 'VEH/AIR/FRG';
    public const A_CTOR_VEH_AIR_FXBA = 'VEH/AIR/FXBA';
    public const A_CTOR_VEH_AIR_GLD = 'VEH/AIR/GLD';
    public const A_CTOR_VEH_AIR_HEL = 'VEH/AIR/HEL';
    public const A_CTOR_VEH_AIR_HVY = 'VEH/AIR/HVY';
    public const A_CTOR_VEH_AIR_JET = 'VEH/AIR/JET';
    public const A_CTOR_VEH_AIR_LGT = 'VEH/AIR/LGT';
    public const A_CTOR_VEH_AIR_MIL = 'VEH/AIR/MIL';
    public const A_CTOR_VEH_AIR_ORD = 'VEH/AIR/ORD';
    public const A_CTOR_VEH_AIR_OTH = 'VEH/AIR/OTH';
    public const A_CTOR_VEH_AIR_PAS = 'VEH/AIR/PAS';
    public const A_CTOR_VEH_AIR_PRBA = 'VEH/AIR/PRBA';
    public const A_CTOR_VEH_AIR_PST = 'VEH/AIR/PST';
    public const A_CTOR_VEH_AIR_RKT = 'VEH/AIR/RKT';
    public const A_CTOR_VEH_AIR_SEA = 'VEH/AIR/SEA';
    public const A_CTOR_VEH_AIR_SNO = 'VEH/AIR/SNO';
    public const A_CTOR_VEH_AIR_TNK = 'VEH/AIR/TNK';
    public const A_CTOR_VEH_AIR_UAV = 'VEH/AIR/UAV';
    public const A_CTOR_VEH_AIR_ULG = 'VEH/AIR/ULG';
    public const A_CTOR_VEH_OTH_HIL = 'VEH/OTH/HIL';
    public const A_CTOR_VEH_OTH_SNO = 'VEH/OTH/SNO';
    public const A_CTOR_VEH_TRK_ART = 'VEH/TRK/ART';
    public const A_CTOR_VEH_TRK_EXC = 'VEH/TRK/EXC';
    public const A_CTOR_VEH_TRK_HZD = 'VEH/TRK/HZD';
    public const A_CTOR_VEH_TRK_NHZ = 'VEH/TRK/NHZ';
    public const A_CTOR_VEH_TRK_NUK = 'VEH/TRK/NUK';
    public const A_CTOR_VEH_TRK_REF = 'VEH/TRK/REF';
    public const A_CTOR_VEH_TRK_UND = 'VEH/TRK/UND';
    public const A_CTOR_VEH_TRN_3_RL = 'VEH/TRN/3RL';
    public const A_CTOR_VEH_TRN_DSL = 'VEH/TRN/DSL';
    public const A_CTOR_VEH_TRN_HZD = 'VEH/TRN/HZD';
    public const A_CTOR_VEH_TRN_LOC = 'VEH/TRN/LOC';
    public const A_CTOR_VEH_TRN_NHZ = 'VEH/TRN/NHZ';
    public const A_CTOR_VEH_TRN_NUK = 'VEH/TRN/NUK';
    public const A_CTOR_VEH_TRN_OVH = 'VEH/TRN/OVH';
    public const A_CTOR_VEH_TRN_PAS = 'VEH/TRN/PAS';
    public const A_CTOR_VEH_TRN_REF = 'VEH/TRN/REF';
    public const A_CTOR_VEH_TRN_STM = 'VEH/TRN/STM';
    public const A_CTOR_VEH_TRN_TRM = 'VEH/TRN/TRM';
    public const A_CTOR_VEH_TRN_UDG = 'VEH/TRN/UDG';
    public const A_CTOR_VEH_TRN_UND = 'VEH/TRN/UND';
    public const A_CTOR_VEH_TRN_VIP = 'VEH/TRN/VIP';
    public const A_CTOR_VEH_TRN_VLT = 'VEH/TRN/VLT';
    public const A_CTOR_VEH_VES_AMB = 'VEH/VES/AMB';
    public const A_CTOR_VEH_VES_BOT = 'VEH/VES/BOT';
    public const A_CTOR_VEH_VES_CNO = 'VEH/VES/CNO';
    public const A_CTOR_VEH_VES_CRG = 'VEH/VES/CRG';
    public const A_CTOR_VEH_VES_DSL = 'VEH/VES/DSL';
    public const A_CTOR_VEH_VES_FLO = 'VEH/VES/FLO';
    public const A_CTOR_VEH_VES_FRY = 'VEH/VES/FRY';
    public const A_CTOR_VEH_VES_HOV = 'VEH/VES/HOV';
    public const A_CTOR_VEH_VES_HZD = 'VEH/VES/HZD';
    public const A_CTOR_VEH_VES_JSK = 'VEH/VES/JSK';
    public const A_CTOR_VEH_VES_LEI = 'VEH/VES/LEI';
    public const A_CTOR_VEH_VES_LIS = 'VEH/VES/LIS';
    public const A_CTOR_VEH_VES_MIL = 'VEH/VES/MIL';
    public const A_CTOR_VEH_VES_MPW = 'VEH/VES/MPW';
    public const A_CTOR_VEH_VES_NHZ = 'VEH/VES/NHZ';
    public const A_CTOR_VEH_VES_NUK = 'VEH/VES/NUK';
    public const A_CTOR_VEH_VES_PAS = 'VEH/VES/PAS';
    public const A_CTOR_VEH_VES_POL = 'VEH/VES/POL';
    public const A_CTOR_VEH_VES_PTL = 'VEH/VES/PTL';
    public const A_CTOR_VEH_VES_RSC = 'VEH/VES/RSC';
    public const A_CTOR_VEH_VES_SAI = 'VEH/VES/SAI';
    public const A_CTOR_VEH_VES_SBM = 'VEH/VES/SBM';
    public const A_CTOR_VEH_VES_SINK = 'VEH/VES/SINK';
    public const A_CTOR_VEH_VES_SPC = 'VEH/VES/SPC';
    public const A_CTOR_VEH_VES_STE = 'VEH/VES/STE';
    public const A_CTOR_VEH_VES_SUNK = 'VEH/VES/SUNK';
    public const A_CTOR_VEH_VES_UNM = 'VEH/VES/UNM';
    public const E_NV_CDIS = 'CDIS';
    public const E_NV_DIS = 'DIS';
    public const E_NV_TER = 'TER';
    public const E_NV_CDIS_RIOT = 'CDIS/RIOT';
    public const E_NV_DIS_CBRN = 'DIS/CBRN';
    public const E_NV_DIS_ERTHQK = 'DIS/ERTHQK';
    public const E_NV_DIS_FIRE = 'DIS/FIRE';
    public const E_NV_DIS_FLOOD = 'DIS/FLOOD';
    public const E_NV_DIS_INDHAZ = 'DIS/INDHAZ';
    public const E_NV_DIS_LNDSLD = 'DIS/LNDSLD';
    public const E_NV_DIS_PWROUT = 'DIS/PWROUT';
    public const E_NV_DIS_RADCNT = 'DIS/RADCNT';
    public const E_NV_DIS_SNOW = 'DIS/SNOW';
    public const E_NV_DIS_STCLPS = 'DIS/STCLPS';
    public const E_NV_DIS_STORM = 'DIS/STORM';
    public const E_NV_DIS_TRSPRT = 'DIS/TRSPRT';
    public const E_NV_DIS_TSNAMI = 'DIS/TSNAMI';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCATEGORYAllowableValues()
    {
        return [
            self::C_ATEGORY_ASB,
            self::C_ATEGORY_ASR,
            self::C_ATEGORY_EXP,
            self::C_ATEGORY_FIR,
            self::C_ATEGORY_FLD,
            self::C_ATEGORY_GND,
            self::C_ATEGORY_HLT,
            self::C_ATEGORY_POL,
            self::C_ATEGORY_PSW,
            self::C_ATEGORY_TRP,
            self::C_ATEGORY_ASB_ABV,
            self::C_ATEGORY_ASR_ATM,
            self::C_ATEGORY_ASR_HGT,
            self::C_ATEGORY_ASR_ICE,
            self::C_ATEGORY_ASR_MAR,
            self::C_ATEGORY_ASR_SIL,
            self::C_ATEGORY_ASR_TRP,
            self::C_ATEGORY_ASR_UDG,
            self::C_ATEGORY_ASR_WAT,
            self::C_ATEGORY_EXP_AER,
            self::C_ATEGORY_EXP_AMM,
            self::C_ATEGORY_EXP_BLEVE,
            self::C_ATEGORY_EXP_CHM,
            self::C_ATEGORY_EXP_CYL,
            self::C_ATEGORY_EXP_DST,
            self::C_ATEGORY_EXP_FRW,
            self::C_ATEGORY_EXP_GAS,
            self::C_ATEGORY_EXP_HGHFLM,
            self::C_ATEGORY_EXP_HPP,
            self::C_ATEGORY_EXP_IMP,
            self::C_ATEGORY_EXP_LPG,
            self::C_ATEGORY_EXP_NUK,
            self::C_ATEGORY_EXP_PRD,
            self::C_ATEGORY_EXP_UKN,
            self::C_ATEGORY_FIR_CLA,
            self::C_ATEGORY_FIR_CLB,
            self::C_ATEGORY_FIR_CLC,
            self::C_ATEGORY_FIR_CLD,
            self::C_ATEGORY_FIR_UKN,
            self::C_ATEGORY_FLD_FLS,
            self::C_ATEGORY_FLD_PLN,
            self::C_ATEGORY_FLD_TID,
            self::C_ATEGORY_GND_AVL,
            self::C_ATEGORY_GND_EQK,
            self::C_ATEGORY_GND_GEY,
            self::C_ATEGORY_GND_LDS,
            self::C_ATEGORY_GND_MUD,
            self::C_ATEGORY_GND_SUB,
            self::C_ATEGORY_GND_VUL,
            self::C_ATEGORY_HLT_EPI,
            self::C_ATEGORY_HLT_FMN,
            self::C_ATEGORY_HLT_NDS,
            self::C_ATEGORY_POL_BIO,
            self::C_ATEGORY_POL_CHM,
            self::C_ATEGORY_POL_NUK,
            self::C_ATEGORY_POL_RAD,
            self::C_ATEGORY_PSW_ALM,
            self::C_ATEGORY_PSW_ASY,
            self::C_ATEGORY_PSW_DEM,
            self::C_ATEGORY_PSW_IMM,
            self::C_ATEGORY_PSW_MEV,
            self::C_ATEGORY_PSW_MIS,
            self::C_ATEGORY_PSW_PKG,
            self::C_ATEGORY_PSW_PRO,
            self::C_ATEGORY_PSW_PRSUIT,
            self::C_ATEGORY_PSW_RIOT,
            self::C_ATEGORY_PSW_SUS,
            self::C_ATEGORY_PSW_WNG,
            self::C_ATEGORY_TRP_BRK,
            self::C_ATEGORY_TRP_COL,
            self::C_ATEGORY_TRP_CRS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getACTORAllowableValues()
    {
        return [
            self::A_CTOR_ANI,
            self::A_CTOR_BEV,
            self::A_CTOR_PPL,
            self::A_CTOR_VEH,
            self::A_CTOR_ANI_CON,
            self::A_CTOR_ANI_DEA,
            self::A_CTOR_ANI_DGR,
            self::A_CTOR_ANI_FRM,
            self::A_CTOR_ANI_HRD,
            self::A_CTOR_ANI_INJ,
            self::A_CTOR_ANI_LIV,
            self::A_CTOR_ANI_PET,
            self::A_CTOR_ANI_PRO,
            self::A_CTOR_ANI_SPC,
            self::A_CTOR_ANI_WLD,
            self::A_CTOR_BEV_ASR,
            self::A_CTOR_BEV_IND,
            self::A_CTOR_BEV_NRES,
            self::A_CTOR_BEV_OFF,
            self::A_CTOR_BEV_OTH,
            self::A_CTOR_BEV_RESDW,
            self::A_CTOR_BEV_RESIN,
            self::A_CTOR_BEV_RESINT,
            self::A_CTOR_BEV_RESOTH,
            self::A_CTOR_BEV_SHP,
            self::A_CTOR_PPL_1,
            self::A_CTOR_PPL_ADU,
            self::A_CTOR_PPL_CHD,
            self::A_CTOR_PPL_CNT,
            self::A_CTOR_PPL_DED,
            self::A_CTOR_PPL_EVC,
            self::A_CTOR_PPL_GND,
            self::A_CTOR_PPL_GRP,
            self::A_CTOR_PPL_HST,
            self::A_CTOR_PPL_INT,
            self::A_CTOR_PPL_OTH,
            self::A_CTOR_PPL_PRS,
            self::A_CTOR_PPL_SNS,
            self::A_CTOR_PPL_VIO,
            self::A_CTOR_PPL_VLN,
            self::A_CTOR_PPL_WTN,
            self::A_CTOR_PPL_CHD_BAB,
            self::A_CTOR_PPL_CHD_CHILD,
            self::A_CTOR_PPL_CHD_INF,
            self::A_CTOR_PPL_CHD_YOUTH,
            self::A_CTOR_PPL_GND_FML,
            self::A_CTOR_PPL_GND_MAL,
            self::A_CTOR_PPL_GND_UND,
            self::A_CTOR_PPL_HST_PCF,
            self::A_CTOR_PPL_HST_SUI,
            self::A_CTOR_PPL_HST_THT,
            self::A_CTOR_PPL_HST_WPN,
            self::A_CTOR_PPL_PRS_CST,
            self::A_CTOR_PPL_PRS_ESC,
            self::A_CTOR_PPL_PRS_HGS,
            self::A_CTOR_PPL_SNS_ETH,
            self::A_CTOR_PPL_SNS_FOR,
            self::A_CTOR_PPL_SNS_LAN,
            self::A_CTOR_PPL_SNS_REL,
            self::A_CTOR_PPL_SNS_VIP,
            self::A_CTOR_PPL_VLN_BLD,
            self::A_CTOR_PPL_VLN_DEF,
            self::A_CTOR_PPL_VLN_DSB,
            self::A_CTOR_PPL_VLN_ELD,
            self::A_CTOR_PPL_VLN_INJ,
            self::A_CTOR_PPL_VLN_LDF,
            self::A_CTOR_PPL_VLN_OBS,
            self::A_CTOR_PPL_VLN_PAT,
            self::A_CTOR_PPL_VLN_PGN,
            self::A_CTOR_PPL_VLN_SLFPRS,
            self::A_CTOR_PPL_VLN_UNC,
            self::A_CTOR_VEH_AIR,
            self::A_CTOR_VEH_ANI,
            self::A_CTOR_VEH_BIC,
            self::A_CTOR_VEH_CAR,
            self::A_CTOR_VEH_EMG,
            self::A_CTOR_VEH_MBK,
            self::A_CTOR_VEH_MIL,
            self::A_CTOR_VEH_OTH,
            self::A_CTOR_VEH_TRK,
            self::A_CTOR_VEH_TRN,
            self::A_CTOR_VEH_VES,
            self::A_CTOR_VEH_AIR_ARM,
            self::A_CTOR_VEH_AIR_FLBA,
            self::A_CTOR_VEH_AIR_FRG,
            self::A_CTOR_VEH_AIR_FXBA,
            self::A_CTOR_VEH_AIR_GLD,
            self::A_CTOR_VEH_AIR_HEL,
            self::A_CTOR_VEH_AIR_HVY,
            self::A_CTOR_VEH_AIR_JET,
            self::A_CTOR_VEH_AIR_LGT,
            self::A_CTOR_VEH_AIR_MIL,
            self::A_CTOR_VEH_AIR_ORD,
            self::A_CTOR_VEH_AIR_OTH,
            self::A_CTOR_VEH_AIR_PAS,
            self::A_CTOR_VEH_AIR_PRBA,
            self::A_CTOR_VEH_AIR_PST,
            self::A_CTOR_VEH_AIR_RKT,
            self::A_CTOR_VEH_AIR_SEA,
            self::A_CTOR_VEH_AIR_SNO,
            self::A_CTOR_VEH_AIR_TNK,
            self::A_CTOR_VEH_AIR_UAV,
            self::A_CTOR_VEH_AIR_ULG,
            self::A_CTOR_VEH_OTH_HIL,
            self::A_CTOR_VEH_OTH_SNO,
            self::A_CTOR_VEH_TRK_ART,
            self::A_CTOR_VEH_TRK_EXC,
            self::A_CTOR_VEH_TRK_HZD,
            self::A_CTOR_VEH_TRK_NHZ,
            self::A_CTOR_VEH_TRK_NUK,
            self::A_CTOR_VEH_TRK_REF,
            self::A_CTOR_VEH_TRK_UND,
            self::A_CTOR_VEH_TRN_3_RL,
            self::A_CTOR_VEH_TRN_DSL,
            self::A_CTOR_VEH_TRN_HZD,
            self::A_CTOR_VEH_TRN_LOC,
            self::A_CTOR_VEH_TRN_NHZ,
            self::A_CTOR_VEH_TRN_NUK,
            self::A_CTOR_VEH_TRN_OVH,
            self::A_CTOR_VEH_TRN_PAS,
            self::A_CTOR_VEH_TRN_REF,
            self::A_CTOR_VEH_TRN_STM,
            self::A_CTOR_VEH_TRN_TRM,
            self::A_CTOR_VEH_TRN_UDG,
            self::A_CTOR_VEH_TRN_UND,
            self::A_CTOR_VEH_TRN_VIP,
            self::A_CTOR_VEH_TRN_VLT,
            self::A_CTOR_VEH_VES_AMB,
            self::A_CTOR_VEH_VES_BOT,
            self::A_CTOR_VEH_VES_CNO,
            self::A_CTOR_VEH_VES_CRG,
            self::A_CTOR_VEH_VES_DSL,
            self::A_CTOR_VEH_VES_FLO,
            self::A_CTOR_VEH_VES_FRY,
            self::A_CTOR_VEH_VES_HOV,
            self::A_CTOR_VEH_VES_HZD,
            self::A_CTOR_VEH_VES_JSK,
            self::A_CTOR_VEH_VES_LEI,
            self::A_CTOR_VEH_VES_LIS,
            self::A_CTOR_VEH_VES_MIL,
            self::A_CTOR_VEH_VES_MPW,
            self::A_CTOR_VEH_VES_NHZ,
            self::A_CTOR_VEH_VES_NUK,
            self::A_CTOR_VEH_VES_PAS,
            self::A_CTOR_VEH_VES_POL,
            self::A_CTOR_VEH_VES_PTL,
            self::A_CTOR_VEH_VES_RSC,
            self::A_CTOR_VEH_VES_SAI,
            self::A_CTOR_VEH_VES_SBM,
            self::A_CTOR_VEH_VES_SINK,
            self::A_CTOR_VEH_VES_SPC,
            self::A_CTOR_VEH_VES_STE,
            self::A_CTOR_VEH_VES_SUNK,
            self::A_CTOR_VEH_VES_UNM,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getENVAllowableValues()
    {
        return [
            self::E_NV_CDIS,
            self::E_NV_DIS,
            self::E_NV_TER,
            self::E_NV_CDIS_RIOT,
            self::E_NV_DIS_CBRN,
            self::E_NV_DIS_ERTHQK,
            self::E_NV_DIS_FIRE,
            self::E_NV_DIS_FLOOD,
            self::E_NV_DIS_INDHAZ,
            self::E_NV_DIS_LNDSLD,
            self::E_NV_DIS_PWROUT,
            self::E_NV_DIS_RADCNT,
            self::E_NV_DIS_SNOW,
            self::E_NV_DIS_STCLPS,
            self::E_NV_DIS_STORM,
            self::E_NV_DIS_TRSPRT,
            self::E_NV_DIS_TSNAMI,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('cATEGORY', $data ?? [], null);
        $this->setIfExists('aCTOR', $data ?? [], null);
        $this->setIfExists('lOCTYPE', $data ?? [], null);
        $this->setIfExists('eNV', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['cATEGORY'] === null) {
            $invalidProperties[] = "'cATEGORY' can't be null";
        }
        if ((count($this->container['cATEGORY']) < 1)) {
            $invalidProperties[] = "invalid value for 'cATEGORY', number of items must be greater than or equal to 1.";
        }

        if ($this->container['aCTOR'] === null) {
            $invalidProperties[] = "'aCTOR' can't be null";
        }
        if ((count($this->container['aCTOR']) < 1)) {
            $invalidProperties[] = "invalid value for 'aCTOR', number of items must be greater than or equal to 1.";
        }

        if ($this->container['lOCTYPE'] === null) {
            $invalidProperties[] = "'lOCTYPE' can't be null";
        }
        if ((count($this->container['lOCTYPE']) < 1)) {
            $invalidProperties[] = "invalid value for 'lOCTYPE', number of items must be greater than or equal to 1.";
        }

        $allowedValues = $this->getENVAllowableValues();
        if (!is_null($this->container['eNV']) && !in_array($this->container['eNV'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'eNV', must be one of '%s'",
                $this->container['eNV'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cATEGORY
     *
     * @return string[]
     */
    public function getCATEGORY()
    {
        return $this->container['cATEGORY'];
    }

    /**
     * Sets cATEGORY
     *
     * @param string[] $cATEGORY cATEGORY
     *
     * @return self
     */
    public function setCATEGORY($cATEGORY)
    {
        if (is_null($cATEGORY)) {
            throw new \InvalidArgumentException('non-nullable cATEGORY cannot be null');
        }
        $allowedValues = $this->getCATEGORYAllowableValues();
        if (array_diff($cATEGORY, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'cATEGORY', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }


        if ((count($cATEGORY) < 1)) {
            throw new \InvalidArgumentException('invalid length for $cATEGORY when calling Etype., number of items must be greater than or equal to 1.');
        }
        $this->container['cATEGORY'] = $cATEGORY;

        return $this;
    }

    /**
     * Gets aCTOR
     *
     * @return string[]
     */
    public function getACTOR()
    {
        return $this->container['aCTOR'];
    }

    /**
     * Sets aCTOR
     *
     * @param string[] $aCTOR aCTOR
     *
     * @return self
     */
    public function setACTOR($aCTOR)
    {
        if (is_null($aCTOR)) {
            throw new \InvalidArgumentException('non-nullable aCTOR cannot be null');
        }
        $allowedValues = $this->getACTORAllowableValues();
        if (array_diff($aCTOR, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'aCTOR', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }


        if ((count($aCTOR) < 1)) {
            throw new \InvalidArgumentException('invalid length for $aCTOR when calling Etype., number of items must be greater than or equal to 1.');
        }
        $this->container['aCTOR'] = $aCTOR;

        return $this;
    }

    /**
     * Gets lOCTYPE
     *
     * @return string[]
     */
    public function getLOCTYPE()
    {
        return $this->container['lOCTYPE'];
    }

    /**
     * Sets lOCTYPE
     *
     * @param string[] $lOCTYPE lOCTYPE
     *
     * @return self
     */
    public function setLOCTYPE($lOCTYPE)
    {
        if (is_null($lOCTYPE)) {
            throw new \InvalidArgumentException('non-nullable lOCTYPE cannot be null');
        }


        if ((count($lOCTYPE) < 1)) {
            throw new \InvalidArgumentException('invalid length for $lOCTYPE when calling Etype., number of items must be greater than or equal to 1.');
        }
        $this->container['lOCTYPE'] = $lOCTYPE;

        return $this;
    }

    /**
     * Gets eNV
     *
     * @return string|null
     */
    public function getENV()
    {
        return $this->container['eNV'];
    }

    /**
     * Sets eNV
     *
     * @param string|null $eNV Optionnel
     *
     * @return self
     */
    public function setENV($eNV)
    {
        if (is_null($eNV)) {
            throw new \InvalidArgumentException('non-nullable eNV cannot be null');
        }
        $allowedValues = $this->getENVAllowableValues();
        if (!in_array($eNV, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'eNV', must be one of '%s'",
                    $eNV,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['eNV'] = $eNV;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


