<?php
/**
 * Rtype
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hubsante
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hubsante\Model\emsi;

use \ArrayAccess;
use \Hubsante\ObjectSerializer;

/**
 * Rtype Class Doc Comment
 *
 * @category Class
 * @package  Hubsante
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Rtype implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'rtype';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'rCLASS' => 'string[]',
        'cAPABILITY' => 'string[]',
        'cHARACTERISTICS' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'rCLASS' => null,
        'cAPABILITY' => null,
        'cHARACTERISTICS' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'rCLASS' => false,
        'cAPABILITY' => false,
        'cHARACTERISTICS' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rCLASS' => 'RCLASS',
        'cAPABILITY' => 'CAPABILITY',
        'cHARACTERISTICS' => 'CHARACTERISTICS'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rCLASS' => 'setRCLASS',
        'cAPABILITY' => 'setCAPABILITY',
        'cHARACTERISTICS' => 'setCHARACTERISTICS'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rCLASS' => 'getRCLASS',
        'cAPABILITY' => 'getCAPABILITY',
        'cHARACTERISTICS' => 'getCHARACTERISTICS'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const R_CLASS_FAC = 'FAC';
    public const R_CLASS_HUM = 'HUM';
    public const R_CLASS_MAT = 'MAT';
    public const R_CLASS_ORG = 'ORG';
    public const R_CLASS_FAC_BRIDGE = 'FAC/BRIDGE';
    public const R_CLASS_FAC_BUILDN = 'FAC/BUILDN';
    public const R_CLASS_FAC_DEPOT = 'FAC/DEPOT';
    public const R_CLASS_FAC_NETWK = 'FAC/NETWK';
    public const R_CLASS_FAC_OPR = 'FAC/OPR';
    public const R_CLASS_FAC_OTH = 'FAC/OTH';
    public const R_CLASS_FAC_WATFIR = 'FAC/WATFIR';
    public const R_CLASS_FAC_BRIDGE_MILVHL = 'FAC/BRIDGE/MILVHL';
    public const R_CLASS_FAC_BUILDN_BARRCK = 'FAC/BUILDN/BARRCK';
    public const R_CLASS_FAC_BUILDN_BUNKER = 'FAC/BUILDN/BUNKER';
    public const R_CLASS_FAC_BUILDN_COB = 'FAC/BUILDN/COB';
    public const R_CLASS_FAC_BUILDN_CTT = 'FAC/BUILDN/CTT';
    public const R_CLASS_FAC_BUILDN_DAM = 'FAC/BUILDN/DAM';
    public const R_CLASS_FAC_BUILDN_GYMNAS = 'FAC/BUILDN/GYMNAS';
    public const R_CLASS_FAC_BUILDN_HANGAR = 'FAC/BUILDN/HANGAR';
    public const R_CLASS_FAC_BUILDN_HOUSE = 'FAC/BUILDN/HOUSE';
    public const R_CLASS_FAC_BUILDN_HUT = 'FAC/BUILDN/HUT';
    public const R_CLASS_FAC_BUILDN_INDINS = 'FAC/BUILDN/INDINS';
    public const R_CLASS_FAC_BUILDN_OFFICE = 'FAC/BUILDN/OFFICE';
    public const R_CLASS_FAC_BUILDN_SCHOOL = 'FAC/BUILDN/SCHOOL';
    public const R_CLASS_FAC_BUILDN_SHD = 'FAC/BUILDN/SHD';
    public const R_CLASS_FAC_BUILDN_SHLSUR = 'FAC/BUILDN/SHLSUR';
    public const R_CLASS_FAC_BUILDN_SHLUND = 'FAC/BUILDN/SHLUND';
    public const R_CLASS_FAC_BUILDN_SHOP = 'FAC/BUILDN/SHOP';
    public const R_CLASS_FAC_BUILDN_TOW = 'FAC/BUILDN/TOW';
    public const R_CLASS_FAC_BUILDN_TUN = 'FAC/BUILDN/TUN';
    public const R_CLASS_FAC_BUILDN_WALL = 'FAC/BUILDN/WALL';
    public const R_CLASS_FAC_BUILDN_WTW = 'FAC/BUILDN/WTW';
    public const R_CLASS_FAC_DEPOT_BIO = 'FAC/DEPOT/BIO';
    public const R_CLASS_FAC_DEPOT_CBRN = 'FAC/DEPOT/CBRN';
    public const R_CLASS_FAC_DEPOT_CHM = 'FAC/DEPOT/CHM';
    public const R_CLASS_FAC_DEPOT_ENG = 'FAC/DEPOT/ENG';
    public const R_CLASS_FAC_DEPOT_MED = 'FAC/DEPOT/MED';
    public const R_CLASS_FAC_DEPOT_MUN = 'FAC/DEPOT/MUN';
    public const R_CLASS_FAC_DEPOT_POL = 'FAC/DEPOT/POL';
    public const R_CLASS_FAC_NETWK_ADSL = 'FAC/NETWK/ADSL';
    public const R_CLASS_FAC_NETWK_ATM = 'FAC/NETWK/ATM';
    public const R_CLASS_FAC_NETWK_CTZALT = 'FAC/NETWK/CTZALT';
    public const R_CLASS_FAC_NETWK_EMGNWK = 'FAC/NETWK/EMGNWK';
    public const R_CLASS_FAC_NETWK_GPRS = 'FAC/NETWK/GPRS';
    public const R_CLASS_FAC_NETWK_GSM = 'FAC/NETWK/GSM';
    public const R_CLASS_FAC_NETWK_INTRAN = 'FAC/NETWK/INTRAN';
    public const R_CLASS_FAC_NETWK_INTRNT = 'FAC/NETWK/INTRNT';
    public const R_CLASS_FAC_NETWK_ISDN = 'FAC/NETWK/ISDN';
    public const R_CLASS_FAC_NETWK_LAN = 'FAC/NETWK/LAN';
    public const R_CLASS_FAC_NETWK_PAMR = 'FAC/NETWK/PAMR';
    public const R_CLASS_FAC_NETWK_PDMR = 'FAC/NETWK/PDMR';
    public const R_CLASS_FAC_NETWK_PGSM = 'FAC/NETWK/PGSM';
    public const R_CLASS_FAC_NETWK_PSTN = 'FAC/NETWK/PSTN';
    public const R_CLASS_FAC_NETWK_RADEHF = 'FAC/NETWK/RADEHF';
    public const R_CLASS_FAC_NETWK_RADHF = 'FAC/NETWK/RADHF';
    public const R_CLASS_FAC_NETWK_RADIO = 'FAC/NETWK/RADIO';
    public const R_CLASS_FAC_NETWK_RADLF = 'FAC/NETWK/RADLF';
    public const R_CLASS_FAC_NETWK_RADMF = 'FAC/NETWK/RADMF';
    public const R_CLASS_FAC_NETWK_RADSHF = 'FAC/NETWK/RADSHF';
    public const R_CLASS_FAC_NETWK_RADUHF = 'FAC/NETWK/RADUHF';
    public const R_CLASS_FAC_NETWK_RADVHF = 'FAC/NETWK/RADVHF';
    public const R_CLASS_FAC_NETWK_RADVLF = 'FAC/NETWK/RADVLF';
    public const R_CLASS_FAC_NETWK_RAYNET = 'FAC/NETWK/RAYNET';
    public const R_CLASS_FAC_NETWK_RELAY = 'FAC/NETWK/RELAY';
    public const R_CLASS_FAC_NETWK_SDSL = 'FAC/NETWK/SDSL';
    public const R_CLASS_FAC_NETWK_TV = 'FAC/NETWK/TV';
    public const R_CLASS_FAC_NETWK_UMTS = 'FAC/NETWK/UMTS';
    public const R_CLASS_FAC_NETWK_VDSL = 'FAC/NETWK/VDSL';
    public const R_CLASS_FAC_NETWK_WAN = 'FAC/NETWK/WAN';
    public const R_CLASS_FAC_NETWK_WIMAX = 'FAC/NETWK/WIMAX';
    public const R_CLASS_FAC_NETWK_WLAN = 'FAC/NETWK/WLAN';
    public const R_CLASS_FAC_OPR_AMBFAC = 'FAC/OPR/AMBFAC';
    public const R_CLASS_FAC_OPR_BDHOLD = 'FAC/OPR/BDHOLD';
    public const R_CLASS_FAC_OPR_CAMP = 'FAC/OPR/CAMP';
    public const R_CLASS_FAC_OPR_CASBUR = 'FAC/OPR/CASBUR';
    public const R_CLASS_FAC_OPR_CASCLR = 'FAC/OPR/CASCLR';
    public const R_CLASS_FAC_OPR_CASCOL = 'FAC/OPR/CASCOL';
    public const R_CLASS_FAC_OPR_CP = 'FAC/OPR/CP';
    public const R_CLASS_FAC_OPR_CSCLPT = 'FAC/OPR/CSCLPT';
    public const R_CLASS_FAC_OPR_CVCLPT = 'FAC/OPR/CVCLPT';
    public const R_CLASS_FAC_OPR_DEBRDP = 'FAC/OPR/DEBRDP';
    public const R_CLASS_FAC_OPR_DECONP = 'FAC/OPR/DECONP';
    public const R_CLASS_FAC_OPR_DISBED = 'FAC/OPR/DISBED';
    public const R_CLASS_FAC_OPR_DOCFAC = 'FAC/OPR/DOCFAC';
    public const R_CLASS_FAC_OPR_EMMORT = 'FAC/OPR/EMMORT';
    public const R_CLASS_FAC_OPR_EQPOOL = 'FAC/OPR/EQPOOL';
    public const R_CLASS_FAC_OPR_EVASSP = 'FAC/OPR/EVASSP';
    public const R_CLASS_FAC_OPR_FACAIR = 'FAC/OPR/FACAIR';
    public const R_CLASS_FAC_OPR_FACMIL = 'FAC/OPR/FACMIL';
    public const R_CLASS_FAC_OPR_FACNAV = 'FAC/OPR/FACNAV';
    public const R_CLASS_FAC_OPR_FAMFRD = 'FAC/OPR/FAMFRD';
    public const R_CLASS_FAC_OPR_FIRFAC = 'FAC/OPR/FIRFAC';
    public const R_CLASS_FAC_OPR_FSAAMM = 'FAC/OPR/FSAAMM';
    public const R_CLASS_FAC_OPR_GERBED = 'FAC/OPR/GERBED';
    public const R_CLASS_FAC_OPR_HOLD = 'FAC/OPR/HOLD';
    public const R_CLASS_FAC_OPR_HPD = 'FAC/OPR/HPD';
    public const R_CLASS_FAC_OPR_HPT = 'FAC/OPR/HPT';
    public const R_CLASS_FAC_OPR_HSP = 'FAC/OPR/HSP';
    public const R_CLASS_FAC_OPR_HSPFLD = 'FAC/OPR/HSPFLD';
    public const R_CLASS_FAC_OPR_HSPFLD2 = 'FAC/OPR/HSPFLD2';
    public const R_CLASS_FAC_OPR_IRM = 'FAC/OPR/IRM';
    public const R_CLASS_FAC_OPR_MARSHAL = 'FAC/OPR/MARSHAL';
    public const R_CLASS_FAC_OPR_MATBED = 'FAC/OPR/MATBED';
    public const R_CLASS_FAC_OPR_MEDBED = 'FAC/OPR/MEDBED';
    public const R_CLASS_FAC_OPR_MEDSPT = 'FAC/OPR/MEDSPT';
    public const R_CLASS_FAC_OPR_MOBLCP = 'FAC/OPR/MOBLCP';
    public const R_CLASS_FAC_OPR_OPCTCN = 'FAC/OPR/OPCTCN';
    public const R_CLASS_FAC_OPR_PHARMA = 'FAC/OPR/PHARMA';
    public const R_CLASS_FAC_OPR_POLFAC = 'FAC/OPR/POLFAC';
    public const R_CLASS_FAC_OPR_POLPT = 'FAC/OPR/POLPT';
    public const R_CLASS_FAC_OPR_REFARE = 'FAC/OPR/REFARE';
    public const R_CLASS_FAC_OPR_RRRSPT = 'FAC/OPR/RRRSPT';
    public const R_CLASS_FAC_OPR_SITLOG = 'FAC/OPR/SITLOG';
    public const R_CLASS_FAC_OPR_SPTARE = 'FAC/OPR/SPTARE';
    public const R_CLASS_FAC_OPR_SRVCNT = 'FAC/OPR/SRVCNT';
    public const R_CLASS_FAC_OPR_STCOCN = 'FAC/OPR/STCOCN';
    public const R_CLASS_FAC_OPR_STCTCN = 'FAC/OPR/STCTCN';
    public const R_CLASS_FAC_OPR_TCCTCN = 'FAC/OPR/TCCTCN';
    public const R_CLASS_FAC_OTH_ACCOM = 'FAC/OTH/ACCOM';
    public const R_CLASS_FAC_OTH_AIRFLD = 'FAC/OTH/AIRFLD';
    public const R_CLASS_FAC_OTH_BANK = 'FAC/OTH/BANK';
    public const R_CLASS_FAC_OTH_BATH = 'FAC/OTH/BATH';
    public const R_CLASS_FAC_OTH_CAN = 'FAC/OTH/CAN';
    public const R_CLASS_FAC_OTH_CEM = 'FAC/OTH/CEM';
    public const R_CLASS_FAC_OTH_DCH = 'FAC/OTH/DCH';
    public const R_CLASS_FAC_OTH_ELCINS = 'FAC/OTH/ELCINS';
    public const R_CLASS_FAC_OTH_ELCSPL = 'FAC/OTH/ELCSPL';
    public const R_CLASS_FAC_OTH_EQIMFT = 'FAC/OTH/EQIMFT';
    public const R_CLASS_FAC_OTH_FACGOV = 'FAC/OTH/FACGOV';
    public const R_CLASS_FAC_OTH_FACPOW = 'FAC/OTH/FACPOW';
    public const R_CLASS_FAC_OTH_FACTEC = 'FAC/OTH/FACTEC';
    public const R_CLASS_FAC_OTH_FACTEL = 'FAC/OTH/FACTEL';
    public const R_CLASS_FAC_OTH_FACTRN = 'FAC/OTH/FACTRN';
    public const R_CLASS_FAC_OTH_FATST = 'FAC/OTH/FATST';
    public const R_CLASS_FAC_OTH_FERINS = 'FAC/OTH/FERINS';
    public const R_CLASS_FAC_OTH_FHPT = 'FAC/OTH/FHPT';
    public const R_CLASS_FAC_OTH_LGRLPT = 'FAC/OTH/LGRLPT';
    public const R_CLASS_FAC_OTH_MAINTF = 'FAC/OTH/MAINTF';
    public const R_CLASS_FAC_OTH_PTL = 'FAC/OTH/PTL';
    public const R_CLASS_FAC_OTH_RES = 'FAC/OTH/RES';
    public const R_CLASS_FAC_OTH_VST = 'FAC/OTH/VST';
    public const R_CLASS_FAC_OTH_WATSPL = 'FAC/OTH/WATSPL';
    public const R_CLASS_FAC_OTH_WSHFAC = 'FAC/OTH/WSHFAC';
    public const R_CLASS_FAC_WATFIR_FOMBLK = 'FAC/WATFIR/FOMBLK';
    public const R_CLASS_FAC_WATFIR_HYDRNT = 'FAC/WATFIR/HYDRNT';
    public const R_CLASS_FAC_WATFIR_TOWNMN = 'FAC/WATFIR/TOWNMN';
    public const R_CLASS_HUM_CAPAB = 'HUM/CAPAB';
    public const R_CLASS_HUM_PERSON = 'HUM/PERSON';
    public const R_CLASS_HUM_UNIT = 'HUM/UNIT';
    public const R_CLASS_HUM_CAPAB_AMB = 'HUM/CAPAB/AMB';
    public const R_CLASS_HUM_CAPAB_FIR = 'HUM/CAPAB/FIR';
    public const R_CLASS_HUM_CAPAB_MED = 'HUM/CAPAB/MED';
    public const R_CLASS_HUM_CAPAB_MIL = 'HUM/CAPAB/MIL';
    public const R_CLASS_HUM_CAPAB_POL = 'HUM/CAPAB/POL';
    public const R_CLASS_HUM_CAPAB_TRP = 'HUM/CAPAB/TRP';
    public const R_CLASS_HUM_CAPAB_AMB_INCOFF = 'HUM/CAPAB/AMB/INCOFF';
    public const R_CLASS_HUM_CAPAB_AMB_PARAMD = 'HUM/CAPAB/AMB/PARAMD';
    public const R_CLASS_HUM_CAPAB_AMB_SAFOFF = 'HUM/CAPAB/AMB/SAFOFF';
    public const R_CLASS_HUM_CAPAB_AMB_TECHNIC = 'HUM/CAPAB/AMB/TECHNIC';
    public const R_CLASS_HUM_CAPAB_FIR_BACOFF = 'HUM/CAPAB/FIR/BACOFF';
    public const R_CLASS_HUM_CAPAB_FIR_BAEOFF = 'HUM/CAPAB/FIR/BAEOFF';
    public const R_CLASS_HUM_CAPAB_FIR_COMOFF = 'HUM/CAPAB/FIR/COMOFF';
    public const R_CLASS_HUM_CAPAB_FIR_CONOFF = 'HUM/CAPAB/FIR/CONOFF';
    public const R_CLASS_HUM_CAPAB_FIR_DECOFF = 'HUM/CAPAB/FIR/DECOFF';
    public const R_CLASS_HUM_CAPAB_FIR_FINOFF = 'HUM/CAPAB/FIR/FINOFF';
    public const R_CLASS_HUM_CAPAB_FIR_FOMOFF = 'HUM/CAPAB/FIR/FOMOFF';
    public const R_CLASS_HUM_CAPAB_FIR_HAZOFF = 'HUM/CAPAB/FIR/HAZOFF';
    public const R_CLASS_HUM_CAPAB_FIR_INCCOM = 'HUM/CAPAB/FIR/INCCOM';
    public const R_CLASS_HUM_CAPAB_FIR_LIAOFF = 'HUM/CAPAB/FIR/LIAOFF';
    public const R_CLASS_HUM_CAPAB_FIR_LOGOFF = 'HUM/CAPAB/FIR/LOGOFF';
    public const R_CLASS_HUM_CAPAB_FIR_MAROFF = 'HUM/CAPAB/FIR/MAROFF';
    public const R_CLASS_HUM_CAPAB_FIR_MEDOFF = 'HUM/CAPAB/FIR/MEDOFF';
    public const R_CLASS_HUM_CAPAB_FIR_OPRCOM = 'HUM/CAPAB/FIR/OPRCOM';
    public const R_CLASS_HUM_CAPAB_FIR_SAFOFF = 'HUM/CAPAB/FIR/SAFOFF';
    public const R_CLASS_HUM_CAPAB_FIR_SALOFF = 'HUM/CAPAB/FIR/SALOFF';
    public const R_CLASS_HUM_CAPAB_FIR_SECCOM = 'HUM/CAPAB/FIR/SECCOM';
    public const R_CLASS_HUM_CAPAB_FIR_STAOFF = 'HUM/CAPAB/FIR/STAOFF';
    public const R_CLASS_HUM_CAPAB_FIR_STRCOM = 'HUM/CAPAB/FIR/STRCOM';
    public const R_CLASS_HUM_CAPAB_FIR_TACCOM = 'HUM/CAPAB/FIR/TACCOM';
    public const R_CLASS_HUM_CAPAB_FIR_WATOFF = 'HUM/CAPAB/FIR/WATOFF';
    public const R_CLASS_HUM_CAPAB_MED_ANSPHY = 'HUM/CAPAB/MED/ANSPHY';
    public const R_CLASS_HUM_CAPAB_MED_DNTPHY = 'HUM/CAPAB/MED/DNTPHY';
    public const R_CLASS_HUM_CAPAB_MED_DOCTOR = 'HUM/CAPAB/MED/DOCTOR';
    public const R_CLASS_HUM_CAPAB_MED_GYNPHY = 'HUM/CAPAB/MED/GYNPHY';
    public const R_CLASS_HUM_CAPAB_MED_HDNPHY = 'HUM/CAPAB/MED/HDNPHY';
    public const R_CLASS_HUM_CAPAB_MED_INMPHY = 'HUM/CAPAB/MED/INMPHY';
    public const R_CLASS_HUM_CAPAB_MED_NURSE = 'HUM/CAPAB/MED/NURSE';
    public const R_CLASS_HUM_CAPAB_MED_ORTPHY = 'HUM/CAPAB/MED/ORTPHY';
    public const R_CLASS_HUM_CAPAB_MED_OTHPHY = 'HUM/CAPAB/MED/OTHPHY';
    public const R_CLASS_HUM_CAPAB_MED_PRCPHY = 'HUM/CAPAB/MED/PRCPHY';
    public const R_CLASS_HUM_CAPAB_MED_PSYPHY = 'HUM/CAPAB/MED/PSYPHY';
    public const R_CLASS_HUM_CAPAB_MED_PTHPHY = 'HUM/CAPAB/MED/PTHPHY';
    public const R_CLASS_HUM_CAPAB_MED_RADPHY = 'HUM/CAPAB/MED/RADPHY';
    public const R_CLASS_HUM_CAPAB_MED_SURPHY = 'HUM/CAPAB/MED/SURPHY';
    public const R_CLASS_HUM_CAPAB_MIL_AUTCDR = 'HUM/CAPAB/MIL/AUTCDR';
    public const R_CLASS_HUM_CAPAB_MIL_INTOFF = 'HUM/CAPAB/MIL/INTOFF';
    public const R_CLASS_HUM_CAPAB_MIL_LIAISN = 'HUM/CAPAB/MIL/LIAISN';
    public const R_CLASS_HUM_CAPAB_MIL_OF1 = 'HUM/CAPAB/MIL/OF1';
    public const R_CLASS_HUM_CAPAB_MIL_OF10 = 'HUM/CAPAB/MIL/OF10';
    public const R_CLASS_HUM_CAPAB_MIL_OF2 = 'HUM/CAPAB/MIL/OF2';
    public const R_CLASS_HUM_CAPAB_MIL_OF3 = 'HUM/CAPAB/MIL/OF3';
    public const R_CLASS_HUM_CAPAB_MIL_OF4 = 'HUM/CAPAB/MIL/OF4';
    public const R_CLASS_HUM_CAPAB_MIL_OF5 = 'HUM/CAPAB/MIL/OF5';
    public const R_CLASS_HUM_CAPAB_MIL_OF6 = 'HUM/CAPAB/MIL/OF6';
    public const R_CLASS_HUM_CAPAB_MIL_OF7 = 'HUM/CAPAB/MIL/OF7';
    public const R_CLASS_HUM_CAPAB_MIL_OF8 = 'HUM/CAPAB/MIL/OF8';
    public const R_CLASS_HUM_CAPAB_MIL_OF9 = 'HUM/CAPAB/MIL/OF9';
    public const R_CLASS_HUM_CAPAB_MIL_OFFR = 'HUM/CAPAB/MIL/OFFR';
    public const R_CLASS_HUM_CAPAB_MIL_OPSOFF = 'HUM/CAPAB/MIL/OPSOFF';
    public const R_CLASS_HUM_CAPAB_MIL_OR1 = 'HUM/CAPAB/MIL/OR1';
    public const R_CLASS_HUM_CAPAB_MIL_OR2 = 'HUM/CAPAB/MIL/OR2';
    public const R_CLASS_HUM_CAPAB_MIL_OR3 = 'HUM/CAPAB/MIL/OR3';
    public const R_CLASS_HUM_CAPAB_MIL_OR4 = 'HUM/CAPAB/MIL/OR4';
    public const R_CLASS_HUM_CAPAB_MIL_OR5 = 'HUM/CAPAB/MIL/OR5';
    public const R_CLASS_HUM_CAPAB_MIL_OR6 = 'HUM/CAPAB/MIL/OR6';
    public const R_CLASS_HUM_CAPAB_MIL_OR7 = 'HUM/CAPAB/MIL/OR7';
    public const R_CLASS_HUM_CAPAB_MIL_OR8 = 'HUM/CAPAB/MIL/OR8';
    public const R_CLASS_HUM_CAPAB_MIL_OR9 = 'HUM/CAPAB/MIL/OR9';
    public const R_CLASS_HUM_CAPAB_MIL_OTHR = 'HUM/CAPAB/MIL/OTHR';
    public const R_CLASS_HUM_CAPAB_MIL_POC = 'HUM/CAPAB/MIL/POC';
    public const R_CLASS_HUM_CAPAB_POL_BMBOFF = 'HUM/CAPAB/POL/BMBOFF';
    public const R_CLASS_HUM_CAPAB_POL_CASOFF = 'HUM/CAPAB/POL/CASOFF';
    public const R_CLASS_HUM_CAPAB_POL_COFF = 'HUM/CAPAB/POL/COFF';
    public const R_CLASS_HUM_CAPAB_POL_DETCTV = 'HUM/CAPAB/POL/DETCTV';
    public const R_CLASS_HUM_CAPAB_POL_DIVER = 'HUM/CAPAB/POL/DIVER';
    public const R_CLASS_HUM_CAPAB_POL_MOM = 'HUM/CAPAB/POL/MOM';
    public const R_CLASS_HUM_CAPAB_POL_PIO = 'HUM/CAPAB/POL/PIO';
    public const R_CLASS_HUM_CAPAB_POL_PMR = 'HUM/CAPAB/POL/PMR';
    public const R_CLASS_HUM_CAPAB_POL_RDINV = 'HUM/CAPAB/POL/RDINV';
    public const R_CLASS_HUM_CAPAB_POL_SCO = 'HUM/CAPAB/POL/SCO';
    public const R_CLASS_HUM_CAPAB_POL_SIO = 'HUM/CAPAB/POL/SIO';
    public const R_CLASS_HUM_CAPAB_POL_STTTK = 'HUM/CAPAB/POL/STTTK';
    public const R_CLASS_HUM_CAPAB_TRP_AIRFW = 'HUM/CAPAB/TRP/AIRFW';
    public const R_CLASS_HUM_CAPAB_TRP_AIRRW = 'HUM/CAPAB/TRP/AIRRW';
    public const R_CLASS_HUM_CAPAB_TRP_AMPH = 'HUM/CAPAB/TRP/AMPH';
    public const R_CLASS_HUM_CAPAB_TRP_LNDRAI = 'HUM/CAPAB/TRP/LNDRAI';
    public const R_CLASS_HUM_CAPAB_TRP_LNDWHL = 'HUM/CAPAB/TRP/LNDWHL';
    public const R_CLASS_HUM_CAPAB_TRP_SEASS = 'HUM/CAPAB/TRP/SEASS';
    public const R_CLASS_HUM_CAPAB_TRP_SEASUR = 'HUM/CAPAB/TRP/SEASUR';
    public const R_CLASS_HUM_PERSON_CFIROF = 'HUM/PERSON/CFIROF';
    public const R_CLASS_HUM_PERSON_GOVEMP = 'HUM/PERSON/GOVEMP';
    public const R_CLASS_HUM_PERSON_INTLCT = 'HUM/PERSON/INTLCT';
    public const R_CLASS_HUM_PERSON_JRNLST = 'HUM/PERSON/JRNLST';
    public const R_CLASS_HUM_PERSON_MEDIA = 'HUM/PERSON/MEDIA';
    public const R_CLASS_HUM_PERSON_NONGVE = 'HUM/PERSON/NONGVE';
    public const R_CLASS_HUM_PERSON_POLCHF = 'HUM/PERSON/POLCHF';
    public const R_CLASS_HUM_PERSON_VILELD = 'HUM/PERSON/VILELD';
    public const R_CLASS_HUM_PERSON_WRITER = 'HUM/PERSON/WRITER';
    public const R_CLASS_HUM_UNIT_AIRLSN = 'HUM/UNIT/AIRLSN';
    public const R_CLASS_HUM_UNIT_C2 = 'HUM/UNIT/C2';
    public const R_CLASS_HUM_UNIT_CBRN = 'HUM/UNIT/CBRN';
    public const R_CLASS_HUM_UNIT_CONST = 'HUM/UNIT/CONST';
    public const R_CLASS_HUM_UNIT_CRSMAN = 'HUM/UNIT/CRSMAN';
    public const R_CLASS_HUM_UNIT_DISID = 'HUM/UNIT/DISID';
    public const R_CLASS_HUM_UNIT_EMPOFF = 'HUM/UNIT/EMPOFF';
    public const R_CLASS_HUM_UNIT_ENG = 'HUM/UNIT/ENG';
    public const R_CLASS_HUM_UNIT_ENVOFF = 'HUM/UNIT/ENVOFF';
    public const R_CLASS_HUM_UNIT_FINANC = 'HUM/UNIT/FINANC';
    public const R_CLASS_HUM_UNIT_FIXWNG = 'HUM/UNIT/FIXWNG';
    public const R_CLASS_HUM_UNIT_GUID = 'HUM/UNIT/GUID';
    public const R_CLASS_HUM_UNIT_HELCTR = 'HUM/UNIT/HELCTR';
    public const R_CLASS_HUM_UNIT_LAWENF = 'HUM/UNIT/LAWENF';
    public const R_CLASS_HUM_UNIT_LNDSPT = 'HUM/UNIT/LNDSPT';
    public const R_CLASS_HUM_UNIT_LOG = 'HUM/UNIT/LOG';
    public const R_CLASS_HUM_UNIT_MAGRSP = 'HUM/UNIT/MAGRSP';
    public const R_CLASS_HUM_UNIT_MAINT = 'HUM/UNIT/MAINT';
    public const R_CLASS_HUM_UNIT_MDSADV = 'HUM/UNIT/MDSADV';
    public const R_CLASS_HUM_UNIT_MEDCL = 'HUM/UNIT/MEDCL';
    public const R_CLASS_HUM_UNIT_MST = 'HUM/UNIT/MST';
    public const R_CLASS_HUM_UNIT_MSURTM = 'HUM/UNIT/MSURTM';
    public const R_CLASS_HUM_UNIT_NAVAL = 'HUM/UNIT/NAVAL';
    public const R_CLASS_HUM_UNIT_POL = 'HUM/UNIT/POL';
    public const R_CLASS_HUM_UNIT_PSYCH = 'HUM/UNIT/PSYCH';
    public const R_CLASS_HUM_UNIT_RAILWY = 'HUM/UNIT/RAILWY';
    public const R_CLASS_HUM_UNIT_RECCE = 'HUM/UNIT/RECCE';
    public const R_CLASS_HUM_UNIT_RELCHP = 'HUM/UNIT/RELCHP';
    public const R_CLASS_HUM_UNIT_RIVERN = 'HUM/UNIT/RIVERN';
    public const R_CLASS_HUM_UNIT_SAR = 'HUM/UNIT/SAR';
    public const R_CLASS_HUM_UNIT_SECPOL = 'HUM/UNIT/SECPOL';
    public const R_CLASS_HUM_UNIT_SHRPAT = 'HUM/UNIT/SHRPAT';
    public const R_CLASS_HUM_UNIT_SPECIA = 'HUM/UNIT/SPECIA';
    public const R_CLASS_HUM_UNIT_SURG = 'HUM/UNIT/SURG';
    public const R_CLASS_HUM_UNIT_TRAUMA = 'HUM/UNIT/TRAUMA';
    public const R_CLASS_HUM_UNIT_TRNPTN = 'HUM/UNIT/TRNPTN';
    public const R_CLASS_HUM_UNIT_VET = 'HUM/UNIT/VET';
    public const R_CLASS_HUM_UNIT_WLFCOR = 'HUM/UNIT/WLFCOR';
    public const R_CLASS_HUM_UNIT_POL_AIRSPT = 'HUM/UNIT/POL/AIRSPT';
    public const R_CLASS_HUM_UNIT_POL_MNTPOL = 'HUM/UNIT/POL/MNTPOL';
    public const R_CLASS_HUM_UNIT_POL_PUBORD = 'HUM/UNIT/POL/PUBORD';
    public const R_CLASS_HUM_UNIT_POL_RDSPT = 'HUM/UNIT/POL/RDSPT';
    public const R_CLASS_HUM_UNIT_POL_SPCLST = 'HUM/UNIT/POL/SPCLST';
    public const R_CLASS_HUM_UNIT_SAR_CSAR = 'HUM/UNIT/SAR/CSAR';
    public const R_CLASS_HUM_UNIT_SAR_MSAR = 'HUM/UNIT/SAR/MSAR';
    public const R_CLASS_HUM_UNIT_SAR_RSAR = 'HUM/UNIT/SAR/RSAR';
    public const R_CLASS_HUM_UNIT_SAR_RST = 'HUM/UNIT/SAR/RST';
    public const R_CLASS_HUM_UNIT_SAR_SSAR = 'HUM/UNIT/SAR/SSAR';
    public const R_CLASS_HUM_UNIT_SAR_USAR = 'HUM/UNIT/SAR/USAR';
    public const R_CLASS_HUM_UNIT_SAR_WSAR = 'HUM/UNIT/SAR/WSAR';
    public const R_CLASS_HUM_UNIT_SAR_USAR_CANIN = 'HUM/UNIT/SAR/USAR/CANIN';
    public const R_CLASS_HUM_UNIT_SAR_USAR_DETEC = 'HUM/UNIT/SAR/USAR/DETEC';
    public const R_CLASS_MAT_CM = 'MAT/CM';
    public const R_CLASS_MAT_EQ = 'MAT/EQ';
    public const R_CLASS_MAT_VEH = 'MAT/VEH';
    public const R_CLASS_MAT_CM_ABSAG = 'MAT/CM/ABSAG';
    public const R_CLASS_MAT_CM_BIOAGN = 'MAT/CM/BIOAGN';
    public const R_CLASS_MAT_CM_CHMAGN = 'MAT/CM/CHMAGN';
    public const R_CLASS_MAT_CM_CON = 'MAT/CM/CON';
    public const R_CLASS_MAT_CM_EXTAG = 'MAT/CM/EXTAG';
    public const R_CLASS_MAT_CM_FOO = 'MAT/CM/FOO';
    public const R_CLASS_MAT_CM_FUEL = 'MAT/CM/FUEL';
    public const R_CLASS_MAT_CM_FUSE = 'MAT/CM/FUSE';
    public const R_CLASS_MAT_CM_LUBRIC = 'MAT/CM/LUBRIC';
    public const R_CLASS_MAT_CM_MATING = 'MAT/CM/MATING';
    public const R_CLASS_MAT_CM_MEDICN = 'MAT/CM/MEDICN';
    public const R_CLASS_MAT_CM_MEDSPL = 'MAT/CM/MEDSPL';
    public const R_CLASS_MAT_CM_MEGPHN = 'MAT/CM/MEGPHN';
    public const R_CLASS_MAT_CM_MONEY = 'MAT/CM/MONEY';
    public const R_CLASS_MAT_CM_OIL = 'MAT/CM/OIL';
    public const R_CLASS_MAT_CM_PAINT = 'MAT/CM/PAINT';
    public const R_CLASS_MAT_CM_PAPER = 'MAT/CM/PAPER';
    public const R_CLASS_MAT_CM_PPE = 'MAT/CM/PPE';
    public const R_CLASS_MAT_CM_RATCO = 'MAT/CM/RATCO';
    public const R_CLASS_MAT_CM_RATFR = 'MAT/CM/RATFR';
    public const R_CLASS_MAT_CM_RATTI = 'MAT/CM/RATTI';
    public const R_CLASS_MAT_CM_RETAG = 'MAT/CM/RETAG';
    public const R_CLASS_MAT_CM_TIMBER = 'MAT/CM/TIMBER';
    public const R_CLASS_MAT_CM_UNIFRM = 'MAT/CM/UNIFRM';
    public const R_CLASS_MAT_CM_WIRE = 'MAT/CM/WIRE';
    public const R_CLASS_MAT_CM_WTREXT = 'MAT/CM/WTREXT';
    public const R_CLASS_MAT_CM_WTRPOT = 'MAT/CM/WTRPOT';
    public const R_CLASS_MAT_CM_ABSAG_CHM = 'MAT/CM/ABSAG/CHM';
    public const R_CLASS_MAT_CM_ABSAG_PHY = 'MAT/CM/ABSAG/PHY';
    public const R_CLASS_MAT_CM_EXTAG_CO2 = 'MAT/CM/EXTAG/CO2';
    public const R_CLASS_MAT_CM_EXTAG_DRYMIN = 'MAT/CM/EXTAG/DRYMIN';
    public const R_CLASS_MAT_CM_EXTAG_FATFIR = 'MAT/CM/EXTAG/FATFIR';
    public const R_CLASS_MAT_CM_EXTAG_FOAM = 'MAT/CM/EXTAG/FOAM';
    public const R_CLASS_MAT_CM_EXTAG_HALON = 'MAT/CM/EXTAG/HALON';
    public const R_CLASS_MAT_CM_EXTAG_INERT = 'MAT/CM/EXTAG/INERT';
    public const R_CLASS_MAT_CM_EXTAG_METPWD = 'MAT/CM/EXTAG/METPWD';
    public const R_CLASS_MAT_CM_EXTAG_POWDER = 'MAT/CM/EXTAG/POWDER';
    public const R_CLASS_MAT_CM_EXTAG_FOAM_AFFF = 'MAT/CM/EXTAG/FOAM/AFFF';
    public const R_CLASS_MAT_CM_EXTAG_FOAM_AFFFAR = 'MAT/CM/EXTAG/FOAM/AFFFAR';
    public const R_CLASS_MAT_CM_EXTAG_FOAM_OTH = 'MAT/CM/EXTAG/FOAM/OTH';
    public const R_CLASS_MAT_CM_FUEL_AVNFU = 'MAT/CM/FUEL/AVNFU';
    public const R_CLASS_MAT_CM_FUEL_DIESEL = 'MAT/CM/FUEL/DIESEL';
    public const R_CLASS_MAT_CM_FUEL_KEROS = 'MAT/CM/FUEL/KEROS';
    public const R_CLASS_MAT_CM_FUEL_LPG = 'MAT/CM/FUEL/LPG';
    public const R_CLASS_MAT_CM_FUEL_NATGAS = 'MAT/CM/FUEL/NATGAS';
    public const R_CLASS_MAT_CM_FUEL_PETROL = 'MAT/CM/FUEL/PETROL';
    public const R_CLASS_MAT_CM_MEDICN_1_STAID = 'MAT/CM/MEDICN/1STAID';
    public const R_CLASS_MAT_CM_MEDICN_AMPHTM = 'MAT/CM/MEDICN/AMPHTM';
    public const R_CLASS_MAT_CM_MEDICN_BLOOD = 'MAT/CM/MEDICN/BLOOD';
    public const R_CLASS_MAT_CM_MEDICN_BNDDR = 'MAT/CM/MEDICN/BNDDR';
    public const R_CLASS_MAT_CM_MEDICN_KTMINE = 'MAT/CM/MEDICN/KTMINE';
    public const R_CLASS_MAT_CM_MEDICN_MORFIN = 'MAT/CM/MEDICN/MORFIN';
    public const R_CLASS_MAT_CM_MEDICN_WTRMED = 'MAT/CM/MEDICN/WTRMED';
    public const R_CLASS_MAT_CM_PPE_CBRNKIT = 'MAT/CM/PPE/CBRNKIT';
    public const R_CLASS_MAT_CM_PPE_CLOTH = 'MAT/CM/PPE/CLOTH';
    public const R_CLASS_MAT_CM_PPE_RESP = 'MAT/CM/PPE/RESP';
    public const R_CLASS_MAT_CM_PPE_SURCOT = 'MAT/CM/PPE/SURCOT';
    public const R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL = 'MAT/CM/PPE/CLOTH/CHEMCL';
    public const R_CLASS_MAT_CM_PPE_CLOTH_FFCLO = 'MAT/CM/PPE/CLOTH/FFCLO';
    public const R_CLASS_MAT_CM_PPE_CLOTH_FKIT = 'MAT/CM/PPE/CLOTH/FKIT';
    public const R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL_CHEMB = 'MAT/CM/PPE/CLOTH/CHEMCL/CHEMB';
    public const R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL_CHEMG = 'MAT/CM/PPE/CLOTH/CHEMCL/CHEMG';
    public const R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL_GASSU = 'MAT/CM/PPE/CLOTH/CHEMCL/GASSU';
    public const R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL_LIQSU = 'MAT/CM/PPE/CLOTH/CHEMCL/LIQSU';
    public const R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL_SPLASU = 'MAT/CM/PPE/CLOTH/CHEMCL/SPLASU';
    public const R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL_TEMPSU = 'MAT/CM/PPE/CLOTH/CHEMCL/TEMPSU';
    public const R_CLASS_MAT_EQ_CBRN = 'MAT/EQ/CBRN';
    public const R_CLASS_MAT_EQ_ELC = 'MAT/EQ/ELC';
    public const R_CLASS_MAT_EQ_ENG = 'MAT/EQ/ENG';
    public const R_CLASS_MAT_EQ_OTH = 'MAT/EQ/OTH';
    public const R_CLASS_MAT_EQ_POLICE = 'MAT/EQ/POLICE';
    public const R_CLASS_MAT_EQ_CBRN_ABICHM = 'MAT/EQ/CBRN/ABICHM';
    public const R_CLASS_MAT_EQ_CBRN_ABIDET = 'MAT/EQ/CBRN/ABIDET';
    public const R_CLASS_MAT_EQ_CBRN_ACHDET = 'MAT/EQ/CBRN/ACHDET';
    public const R_CLASS_MAT_EQ_CBRN_ARDDET = 'MAT/EQ/CBRN/ARDDET';
    public const R_CLASS_MAT_EQ_CBRN_BIOINT = 'MAT/EQ/CBRN/BIOINT';
    public const R_CLASS_MAT_EQ_CBRN_BIOSTO = 'MAT/EQ/CBRN/BIOSTO';
    public const R_CLASS_MAT_EQ_CBRN_CBRNDEC = 'MAT/EQ/CBRN/CBRNDEC';
    public const R_CLASS_MAT_EQ_CBRN_CBRNREC = 'MAT/EQ/CBRN/CBRNREC';
    public const R_CLASS_MAT_EQ_CBRN_CHMMON = 'MAT/EQ/CBRN/CHMMON';
    public const R_CLASS_MAT_EQ_CBRN_MSSPTR = 'MAT/EQ/CBRN/MSSPTR';
    public const R_CLASS_MAT_EQ_CBRN_RDSPTR = 'MAT/EQ/CBRN/RDSPTR';
    public const R_CLASS_MAT_EQ_ELC_AMTRAD = 'MAT/EQ/ELC/AMTRAD';
    public const R_CLASS_MAT_EQ_ELC_C3_I = 'MAT/EQ/ELC/C3I';
    public const R_CLASS_MAT_EQ_ELC_COMSYS = 'MAT/EQ/ELC/COMSYS';
    public const R_CLASS_MAT_EQ_ELC_COMVEH = 'MAT/EQ/ELC/COMVEH';
    public const R_CLASS_MAT_EQ_ELC_MULTIRE = 'MAT/EQ/ELC/MULTIRE';
    public const R_CLASS_MAT_EQ_ELC_NAV = 'MAT/EQ/ELC/NAV';
    public const R_CLASS_MAT_EQ_ELC_NAVRAD = 'MAT/EQ/ELC/NAVRAD';
    public const R_CLASS_MAT_EQ_ELC_OTH = 'MAT/EQ/ELC/OTH';
    public const R_CLASS_MAT_EQ_ELC_POWGN = 'MAT/EQ/ELC/POWGN';
    public const R_CLASS_MAT_EQ_ELC_RIDD = 'MAT/EQ/ELC/RIDD';
    public const R_CLASS_MAT_EQ_ELC_SEN = 'MAT/EQ/ELC/SEN';
    public const R_CLASS_MAT_EQ_ELC_SONAR = 'MAT/EQ/ELC/SONAR';
    public const R_CLASS_MAT_EQ_ELC_THIMC = 'MAT/EQ/ELC/THIMC';
    public const R_CLASS_MAT_EQ_ELC_VIBRA = 'MAT/EQ/ELC/VIBRA';
    public const R_CLASS_MAT_EQ_ELC_COMSYS_MEGPHN = 'MAT/EQ/ELC/COMSYS/MEGPHN';
    public const R_CLASS_MAT_EQ_ELC_COMSYS_PAGER = 'MAT/EQ/ELC/COMSYS/PAGER';
    public const R_CLASS_MAT_EQ_ELC_COMSYS_PMRRDIO = 'MAT/EQ/ELC/COMSYS/PMRRDIO';
    public const R_CLASS_MAT_EQ_ELC_COMSYS_PUBADD = 'MAT/EQ/ELC/COMSYS/PUBADD';
    public const R_CLASS_MAT_EQ_ELC_COMSYS_RDBRCT = 'MAT/EQ/ELC/COMSYS/RDBRCT';
    public const R_CLASS_MAT_EQ_ENG_BRIDGG = 'MAT/EQ/ENG/BRIDGG';
    public const R_CLASS_MAT_EQ_ENG_CNSTVE = 'MAT/EQ/ENG/CNSTVE';
    public const R_CLASS_MAT_EQ_ENG_CONST = 'MAT/EQ/ENG/CONST';
    public const R_CLASS_MAT_EQ_ENG_DOZER = 'MAT/EQ/ENG/DOZER';
    public const R_CLASS_MAT_EQ_ENG_ERTHMV = 'MAT/EQ/ENG/ERTHMV';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT = 'MAT/EQ/ENG/FIRFGT';
    public const R_CLASS_MAT_EQ_ENG_INTEL = 'MAT/EQ/ENG/INTEL';
    public const R_CLASS_MAT_EQ_ENG_MINECL = 'MAT/EQ/ENG/MINECL';
    public const R_CLASS_MAT_EQ_ENG_MINEDT = 'MAT/EQ/ENG/MINEDT';
    public const R_CLASS_MAT_EQ_ENG_MINEMR = 'MAT/EQ/ENG/MINEMR';
    public const R_CLASS_MAT_EQ_ENG_WPNPRT = 'MAT/EQ/ENG/WPNPRT';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_BRHTAP = 'MAT/EQ/ENG/FIRFGT/BRHTAP';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_CEAR = 'MAT/EQ/ENG/FIRFGT/CEAR';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_CEC = 'MAT/EQ/ENG/FIRFGT/CEC';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_CECH = 'MAT/EQ/ENG/FIRFGT/CECH';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_CEEV = 'MAT/EQ/ENG/FIRFGT/CEEV';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_CEM = 'MAT/EQ/ENG/FIRFGT/CEM';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_CEPC = 'MAT/EQ/ENG/FIRFGT/CEPC';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_CEPO = 'MAT/EQ/ENG/FIRFGT/CEPO';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_CEPOL = 'MAT/EQ/ENG/FIRFGT/CEPOL';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_CER = 'MAT/EQ/ENG/FIRFGT/CER';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_CESD = 'MAT/EQ/ENG/FIRFGT/CESD';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_GRDMON = 'MAT/EQ/ENG/FIRFGT/GRDMON';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_MPR = 'MAT/EQ/ENG/FIRFGT/MPR';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_RAR = 'MAT/EQ/ENG/FIRFGT/RAR';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_UMIR = 'MAT/EQ/ENG/FIRFGT/UMIR';
    public const R_CLASS_MAT_EQ_ENG_FIRFGT_VAMUR = 'MAT/EQ/ENG/FIRFGT/VAMUR';
    public const R_CLASS_MAT_EQ_ENG_INTEL_CAMERA = 'MAT/EQ/ENG/INTEL/CAMERA';
    public const R_CLASS_MAT_EQ_ENG_INTEL_CCTVCM = 'MAT/EQ/ENG/INTEL/CCTVCM';
    public const R_CLASS_MAT_EQ_ENG_INTEL_CDVDOG = 'MAT/EQ/ENG/INTEL/CDVDOG';
    public const R_CLASS_MAT_EQ_ENG_INTEL_FSPDCM = 'MAT/EQ/ENG/INTEL/FSPDCM';
    public const R_CLASS_MAT_EQ_ENG_INTEL_FTFLCM = 'MAT/EQ/ENG/INTEL/FTFLCM';
    public const R_CLASS_MAT_EQ_ENG_INTEL_PSPDCM = 'MAT/EQ/ENG/INTEL/PSPDCM';
    public const R_CLASS_MAT_EQ_ENG_INTEL_TCKDOG = 'MAT/EQ/ENG/INTEL/TCKDOG';
    public const R_CLASS_MAT_EQ_ENG_WPNPRT_BALVST = 'MAT/EQ/ENG/WPNPRT/BALVST';
    public const R_CLASS_MAT_EQ_ENG_WPNPRT_BATON = 'MAT/EQ/ENG/WPNPRT/BATON';
    public const R_CLASS_MAT_EQ_ENG_WPNPRT_ENFDOG = 'MAT/EQ/ENG/WPNPRT/ENFDOG';
    public const R_CLASS_MAT_EQ_ENG_WPNPRT_FIREARM = 'MAT/EQ/ENG/WPNPRT/FIREARM';
    public const R_CLASS_MAT_EQ_ENG_WPNPRT_HNDCUF = 'MAT/EQ/ENG/WPNPRT/HNDCUF';
    public const R_CLASS_MAT_EQ_ENG_WPNPRT_OFFPRT = 'MAT/EQ/ENG/WPNPRT/OFFPRT';
    public const R_CLASS_MAT_EQ_ENG_WPNPRT_PRSCNT = 'MAT/EQ/ENG/WPNPRT/PRSCNT';
    public const R_CLASS_MAT_EQ_OTH_BLNKT = 'MAT/EQ/OTH/BLNKT';
    public const R_CLASS_MAT_EQ_OTH_CONTNR = 'MAT/EQ/OTH/CONTNR';
    public const R_CLASS_MAT_EQ_OTH_CUTING = 'MAT/EQ/OTH/CUTING';
    public const R_CLASS_MAT_EQ_OTH_TANK = 'MAT/EQ/OTH/TANK';
    public const R_CLASS_MAT_EQ_OTH_TENT = 'MAT/EQ/OTH/TENT';
    public const R_CLASS_MAT_EQ_OTH_WATPUR = 'MAT/EQ/OTH/WATPUR';
    public const R_CLASS_MAT_EQ_POLICE_BRTEST = 'MAT/EQ/POLICE/BRTEST';
    public const R_CLASS_MAT_EQ_POLICE_CONE = 'MAT/EQ/POLICE/CONE';
    public const R_CLASS_MAT_EQ_POLICE_LAMP = 'MAT/EQ/POLICE/LAMP';
    public const R_CLASS_MAT_EQ_POLICE_STINGER = 'MAT/EQ/POLICE/STINGER';
    public const R_CLASS_MAT_EQ_POLICE_TORCH = 'MAT/EQ/POLICE/TORCH';
    public const R_CLASS_MAT_EQ_POLICE_UNFRMC = 'MAT/EQ/POLICE/UNFRMC';
    public const R_CLASS_MAT_EQ_POLICE_UNFRMN = 'MAT/EQ/POLICE/UNFRMN';
    public const R_CLASS_MAT_VEH_AIRCRF = 'MAT/VEH/AIRCRF';
    public const R_CLASS_MAT_VEH_HORSE = 'MAT/VEH/HORSE';
    public const R_CLASS_MAT_VEH_RAILVE = 'MAT/VEH/RAILVE';
    public const R_CLASS_MAT_VEH_ROADVE = 'MAT/VEH/ROADVE';
    public const R_CLASS_MAT_VEH_VESSEL = 'MAT/VEH/VESSEL';
    public const R_CLASS_MAT_VEH_AIRCRF_AIRTRS = 'MAT/VEH/AIRCRF/AIRTRS';
    public const R_CLASS_MAT_VEH_AIRCRF_CMDCTL = 'MAT/VEH/AIRCRF/CMDCTL';
    public const R_CLASS_MAT_VEH_AIRCRF_HEL = 'MAT/VEH/AIRCRF/HEL';
    public const R_CLASS_MAT_VEH_AIRCRF_HELCMD = 'MAT/VEH/AIRCRF/HELCMD';
    public const R_CLASS_MAT_VEH_AIRCRF_HELMED = 'MAT/VEH/AIRCRF/HELMED';
    public const R_CLASS_MAT_VEH_AIRCRF_HELREC = 'MAT/VEH/AIRCRF/HELREC';
    public const R_CLASS_MAT_VEH_AIRCRF_MEDEVC = 'MAT/VEH/AIRCRF/MEDEVC';
    public const R_CLASS_MAT_VEH_AIRCRF_PLANE = 'MAT/VEH/AIRCRF/PLANE';
    public const R_CLASS_MAT_VEH_AIRCRF_POLHEL = 'MAT/VEH/AIRCRF/POLHEL';
    public const R_CLASS_MAT_VEH_AIRCRF_RECCE = 'MAT/VEH/AIRCRF/RECCE';
    public const R_CLASS_MAT_VEH_AIRCRF_SAR = 'MAT/VEH/AIRCRF/SAR';
    public const R_CLASS_MAT_VEH_AIRCRF_TANKER = 'MAT/VEH/AIRCRF/TANKER';
    public const R_CLASS_MAT_VEH_AIRCRF_UAV = 'MAT/VEH/AIRCRF/UAV';
    public const R_CLASS_MAT_VEH_RAILVE_LCMDSE = 'MAT/VEH/RAILVE/LCMDSE';
    public const R_CLASS_MAT_VEH_RAILVE_LCMDSL = 'MAT/VEH/RAILVE/LCMDSL';
    public const R_CLASS_MAT_VEH_RAILVE_LCMELC = 'MAT/VEH/RAILVE/LCMELC';
    public const R_CLASS_MAT_VEH_RAILVE_LCMSTM = 'MAT/VEH/RAILVE/LCMSTM';
    public const R_CLASS_MAT_VEH_RAILVE_LCMTND = 'MAT/VEH/RAILVE/LCMTND';
    public const R_CLASS_MAT_VEH_RAILVE_LCMTVE = 'MAT/VEH/RAILVE/LCMTVE';
    public const R_CLASS_MAT_VEH_RAILVE_RLDEQP = 'MAT/VEH/RAILVE/RLDEQP';
    public const R_CLASS_MAT_VEH_RAILVE_RLLSTK = 'MAT/VEH/RAILVE/RLLSTK';
    public const R_CLASS_MAT_VEH_RAILVE_TRAM = 'MAT/VEH/RAILVE/TRAM';
    public const R_CLASS_MAT_VEH_RAILVE_WGNART = 'MAT/VEH/RAILVE/WGNART';
    public const R_CLASS_MAT_VEH_RAILVE_WGNBRK = 'MAT/VEH/RAILVE/WGNBRK';
    public const R_CLASS_MAT_VEH_RAILVE_WGNCAR = 'MAT/VEH/RAILVE/WGNCAR';
    public const R_CLASS_MAT_VEH_RAILVE_WGNCRG = 'MAT/VEH/RAILVE/WGNCRG';
    public const R_CLASS_MAT_VEH_RAILVE_WGNCSS = 'MAT/VEH/RAILVE/WGNCSS';
    public const R_CLASS_MAT_VEH_RAILVE_WGNCTL = 'MAT/VEH/RAILVE/WGNCTL';
    public const R_CLASS_MAT_VEH_RAILVE_WGNFLB = 'MAT/VEH/RAILVE/WGNFLB';
    public const R_CLASS_MAT_VEH_RAILVE_WGNFUL = 'MAT/VEH/RAILVE/WGNFUL';
    public const R_CLASS_MAT_VEH_RAILVE_WGNHPR = 'MAT/VEH/RAILVE/WGNHPR';
    public const R_CLASS_MAT_VEH_RAILVE_WGNISO = 'MAT/VEH/RAILVE/WGNISO';
    public const R_CLASS_MAT_VEH_RAILVE_WGNLQD = 'MAT/VEH/RAILVE/WGNLQD';
    public const R_CLASS_MAT_VEH_RAILVE_WGNMNR = 'MAT/VEH/RAILVE/WGNMNR';
    public const R_CLASS_MAT_VEH_RAILVE_WGNOPC = 'MAT/VEH/RAILVE/WGNOPC';
    public const R_CLASS_MAT_VEH_RAILVE_WGNPAS = 'MAT/VEH/RAILVE/WGNPAS';
    public const R_CLASS_MAT_VEH_RAILVE_WGNRFG = 'MAT/VEH/RAILVE/WGNRFG';
    public const R_CLASS_MAT_VEH_RAILVE_WGNRPR = 'MAT/VEH/RAILVE/WGNRPR';
    public const R_CLASS_MAT_VEH_RAILVE_WGNSPP = 'MAT/VEH/RAILVE/WGNSPP';
    public const R_CLASS_MAT_VEH_RAILVE_WGNWAT = 'MAT/VEH/RAILVE/WGNWAT';
    public const R_CLASS_MAT_VEH_RAILVE_WGNWFL = 'MAT/VEH/RAILVE/WGNWFL';
    public const R_CLASS_MAT_VEH_ROADVE_AMBUL = 'MAT/VEH/ROADVE/AMBUL';
    public const R_CLASS_MAT_VEH_ROADVE_AUTOMO = 'MAT/VEH/ROADVE/AUTOMO';
    public const R_CLASS_MAT_VEH_ROADVE_BICYCL = 'MAT/VEH/ROADVE/BICYCL';
    public const R_CLASS_MAT_VEH_ROADVE_BUS = 'MAT/VEH/ROADVE/BUS';
    public const R_CLASS_MAT_VEH_ROADVE_CCTRCK = 'MAT/VEH/ROADVE/CCTRCK';
    public const R_CLASS_MAT_VEH_ROADVE_CRANE = 'MAT/VEH/ROADVE/CRANE';
    public const R_CLASS_MAT_VEH_ROADVE_FRFGTN = 'MAT/VEH/ROADVE/FRFGTN';
    public const R_CLASS_MAT_VEH_ROADVE_HETVEH = 'MAT/VEH/ROADVE/HETVEH';
    public const R_CLASS_MAT_VEH_ROADVE_MAINT = 'MAT/VEH/ROADVE/MAINT';
    public const R_CLASS_MAT_VEH_ROADVE_MHVEH = 'MAT/VEH/ROADVE/MHVEH';
    public const R_CLASS_MAT_VEH_ROADVE_MILUV = 'MAT/VEH/ROADVE/MILUV';
    public const R_CLASS_MAT_VEH_ROADVE_MOTCYC = 'MAT/VEH/ROADVE/MOTCYC';
    public const R_CLASS_MAT_VEH_ROADVE_POD = 'MAT/VEH/ROADVE/POD';
    public const R_CLASS_MAT_VEH_ROADVE_POLICE = 'MAT/VEH/ROADVE/POLICE';
    public const R_CLASS_MAT_VEH_ROADVE_SEMI = 'MAT/VEH/ROADVE/SEMI';
    public const R_CLASS_MAT_VEH_ROADVE_TRACTR = 'MAT/VEH/ROADVE/TRACTR';
    public const R_CLASS_MAT_VEH_ROADVE_TRAILR = 'MAT/VEH/ROADVE/TRAILR';
    public const R_CLASS_MAT_VEH_ROADVE_TRLBUS = 'MAT/VEH/ROADVE/TRLBUS';
    public const R_CLASS_MAT_VEH_ROADVE_TRUCK = 'MAT/VEH/ROADVE/TRUCK';
    public const R_CLASS_MAT_VEH_ROADVE_FRFGTN_AERIAL = 'MAT/VEH/ROADVE/FRFGTN/AERIAL';
    public const R_CLASS_MAT_VEH_ROADVE_FRFGTN_BREATH = 'MAT/VEH/ROADVE/FRFGTN/BREATH';
    public const R_CLASS_MAT_VEH_ROADVE_FRFGTN_C3 = 'MAT/VEH/ROADVE/FRFGTN/C3';
    public const R_CLASS_MAT_VEH_ROADVE_FRFGTN_FRF = 'MAT/VEH/ROADVE/FRFGTN/FRF';
    public const R_CLASS_MAT_VEH_ROADVE_FRFGTN_HAZMAT = 'MAT/VEH/ROADVE/FRFGTN/HAZMAT';
    public const R_CLASS_MAT_VEH_ROADVE_FRFGTN_OTHR = 'MAT/VEH/ROADVE/FRFGTN/OTHR';
    public const R_CLASS_MAT_VEH_ROADVE_FRFGTN_PERCAR = 'MAT/VEH/ROADVE/FRFGTN/PERCAR';
    public const R_CLASS_MAT_VEH_ROADVE_FRFGTN_PUMP = 'MAT/VEH/ROADVE/FRFGTN/PUMP';
    public const R_CLASS_MAT_VEH_ROADVE_FRFGTN_RSC = 'MAT/VEH/ROADVE/FRFGTN/RSC';
    public const R_CLASS_MAT_VEH_ROADVE_POLICE_COMLIA = 'MAT/VEH/ROADVE/POLICE/COMLIA';
    public const R_CLASS_MAT_VEH_ROADVE_POLICE_DOGUNT = 'MAT/VEH/ROADVE/POLICE/DOGUNT';
    public const R_CLASS_MAT_VEH_ROADVE_POLICE_GENPUR = 'MAT/VEH/ROADVE/POLICE/GENPUR';
    public const R_CLASS_MAT_VEH_ROADVE_POLICE_HAZMAT = 'MAT/VEH/ROADVE/POLICE/HAZMAT';
    public const R_CLASS_MAT_VEH_ROADVE_POLICE_MBIKE = 'MAT/VEH/ROADVE/POLICE/MBIKE';
    public const R_CLASS_MAT_VEH_ROADVE_POLICE_PATROL = 'MAT/VEH/ROADVE/POLICE/PATROL';
    public const R_CLASS_MAT_VEH_ROADVE_POLICE_RSPONSE = 'MAT/VEH/ROADVE/POLICE/RSPONSE';
    public const R_CLASS_MAT_VEH_ROADVE_POLICE_TRAFFIC = 'MAT/VEH/ROADVE/POLICE/TRAFFIC';
    public const R_CLASS_MAT_VEH_ROADVE_POLICE_TRANSIT = 'MAT/VEH/ROADVE/POLICE/TRANSIT';
    public const R_CLASS_MAT_VEH_ROADVE_POLICE_VAN = 'MAT/VEH/ROADVE/POLICE/VAN';
    public const R_CLASS_MAT_VEH_VESSEL_AIRCAR = 'MAT/VEH/VESSEL/AIRCAR';
    public const R_CLASS_MAT_VEH_VESSEL_AMPH = 'MAT/VEH/VESSEL/AMPH';
    public const R_CLASS_MAT_VEH_VESSEL_BARGE = 'MAT/VEH/VESSEL/BARGE';
    public const R_CLASS_MAT_VEH_VESSEL_BARSHP = 'MAT/VEH/VESSEL/BARSHP';
    public const R_CLASS_MAT_VEH_VESSEL_BRDGBT = 'MAT/VEH/VESSEL/BRDGBT';
    public const R_CLASS_MAT_VEH_VESSEL_CNTSHP = 'MAT/VEH/VESSEL/CNTSHP';
    public const R_CLASS_MAT_VEH_VESSEL_CSRSHP = 'MAT/VEH/VESSEL/CSRSHP';
    public const R_CLASS_MAT_VEH_VESSEL_CSTSHP = 'MAT/VEH/VESSEL/CSTSHP';
    public const R_CLASS_MAT_VEH_VESSEL_DPSMVS = 'MAT/VEH/VESSEL/DPSMVS';
    public const R_CLASS_MAT_VEH_VESSEL_FERRY = 'MAT/VEH/VESSEL/FERRY';
    public const R_CLASS_MAT_VEH_VESSEL_FIRBOT = 'MAT/VEH/VESSEL/FIRBOT';
    public const R_CLASS_MAT_VEH_VESSEL_FLTCRN = 'MAT/VEH/VESSEL/FLTCRN';
    public const R_CLASS_MAT_VEH_VESSEL_FLTDRG = 'MAT/VEH/VESSEL/FLTDRG';
    public const R_CLASS_MAT_VEH_VESSEL_FLTDRY = 'MAT/VEH/VESSEL/FLTDRY';
    public const R_CLASS_MAT_VEH_VESSEL_FREBLK = 'MAT/VEH/VESSEL/FREBLK';
    public const R_CLASS_MAT_VEH_VESSEL_FRELIQ = 'MAT/VEH/VESSEL/FRELIQ';
    public const R_CLASS_MAT_VEH_VESSEL_HOSSHP = 'MAT/VEH/VESSEL/HOSSHP';
    public const R_CLASS_MAT_VEH_VESSEL_HOVCRF = 'MAT/VEH/VESSEL/HOVCRF';
    public const R_CLASS_MAT_VEH_VESSEL_ICEBRK = 'MAT/VEH/VESSEL/ICEBRK';
    public const R_CLASS_MAT_VEH_VESSEL_LAUNCH = 'MAT/VEH/VESSEL/LAUNCH';
    public const R_CLASS_MAT_VEH_VESSEL_LGHTER = 'MAT/VEH/VESSEL/LGHTER';
    public const R_CLASS_MAT_VEH_VESSEL_LNDCRF = 'MAT/VEH/VESSEL/LNDCRF';
    public const R_CLASS_MAT_VEH_VESSEL_MERSHP = 'MAT/VEH/VESSEL/MERSHP';
    public const R_CLASS_MAT_VEH_VESSEL_MOBLS = 'MAT/VEH/VESSEL/MOBLS';
    public const R_CLASS_MAT_VEH_VESSEL_OILER = 'MAT/VEH/VESSEL/OILER';
    public const R_CLASS_MAT_VEH_VESSEL_PASSGR = 'MAT/VEH/VESSEL/PASSGR';
    public const R_CLASS_MAT_VEH_VESSEL_PATVES = 'MAT/VEH/VESSEL/PATVES';
    public const R_CLASS_MAT_VEH_VESSEL_POLSPD = 'MAT/VEH/VESSEL/POLSPD';
    public const R_CLASS_MAT_VEH_VESSEL_PRV = 'MAT/VEH/VESSEL/PRV';
    public const R_CLASS_MAT_VEH_VESSEL_RAFT = 'MAT/VEH/VESSEL/RAFT';
    public const R_CLASS_MAT_VEH_VESSEL_RPRSHP = 'MAT/VEH/VESSEL/RPRSHP';
    public const R_CLASS_MAT_VEH_VESSEL_SAILVS = 'MAT/VEH/VESSEL/SAILVS';
    public const R_CLASS_MAT_VEH_VESSEL_SALSHP = 'MAT/VEH/VESSEL/SALSHP';
    public const R_CLASS_MAT_VEH_VESSEL_SMLLBO = 'MAT/VEH/VESSEL/SMLLBO';
    public const R_CLASS_MAT_VEH_VESSEL_SUBMAR = 'MAT/VEH/VESSEL/SUBMAR';
    public const R_CLASS_MAT_VEH_VESSEL_TANKER = 'MAT/VEH/VESSEL/TANKER';
    public const R_CLASS_MAT_VEH_VESSEL_TENDER = 'MAT/VEH/VESSEL/TENDER';
    public const R_CLASS_MAT_VEH_VESSEL_TUGBOT = 'MAT/VEH/VESSEL/TUGBOT';
    public const R_CLASS_ORG_AMBUL = 'ORG/AMBUL';
    public const R_CLASS_ORG_CIVP = 'ORG/CIVP';
    public const R_CLASS_ORG_COASTG = 'ORG/COASTG';
    public const R_CLASS_ORG_DOCTOR = 'ORG/DOCTOR';
    public const R_CLASS_ORG_ENVAGC = 'ORG/ENVAGC';
    public const R_CLASS_ORG_FIRFS = 'ORG/FIRFS';
    public const R_CLASS_ORG_GEND = 'ORG/GEND';
    public const R_CLASS_ORG_HOSP = 'ORG/HOSP';
    public const R_CLASS_ORG_IDCOM = 'ORG/IDCOM';
    public const R_CLASS_ORG_LCRESF = 'ORG/LCRESF';
    public const R_CLASS_ORG_LOCAUT = 'ORG/LOCAUT';
    public const R_CLASS_ORG_MARAGC = 'ORG/MARAGC';
    public const R_CLASS_ORG_METAGC = 'ORG/METAGC';
    public const R_CLASS_ORG_MIL = 'ORG/MIL';
    public const R_CLASS_ORG_NGO = 'ORG/NGO';
    public const R_CLASS_ORG_POLCNG = 'ORG/POLCNG';
    public const R_CLASS_ORG_POLICE = 'ORG/POLICE';
    public const R_CLASS_ORG_RGRESF = 'ORG/RGRESF';
    public const R_CLASS_ORG_SPADPV = 'ORG/SPADPV';
    public const R_CLASS_ORG_TRS = 'ORG/TRS';
    public const R_CLASS_ORG_WATAGC = 'ORG/WATAGC';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRCLASSAllowableValues()
    {
        return [
            self::R_CLASS_FAC,
            self::R_CLASS_HUM,
            self::R_CLASS_MAT,
            self::R_CLASS_ORG,
            self::R_CLASS_FAC_BRIDGE,
            self::R_CLASS_FAC_BUILDN,
            self::R_CLASS_FAC_DEPOT,
            self::R_CLASS_FAC_NETWK,
            self::R_CLASS_FAC_OPR,
            self::R_CLASS_FAC_OTH,
            self::R_CLASS_FAC_WATFIR,
            self::R_CLASS_FAC_BRIDGE_MILVHL,
            self::R_CLASS_FAC_BUILDN_BARRCK,
            self::R_CLASS_FAC_BUILDN_BUNKER,
            self::R_CLASS_FAC_BUILDN_COB,
            self::R_CLASS_FAC_BUILDN_CTT,
            self::R_CLASS_FAC_BUILDN_DAM,
            self::R_CLASS_FAC_BUILDN_GYMNAS,
            self::R_CLASS_FAC_BUILDN_HANGAR,
            self::R_CLASS_FAC_BUILDN_HOUSE,
            self::R_CLASS_FAC_BUILDN_HUT,
            self::R_CLASS_FAC_BUILDN_INDINS,
            self::R_CLASS_FAC_BUILDN_OFFICE,
            self::R_CLASS_FAC_BUILDN_SCHOOL,
            self::R_CLASS_FAC_BUILDN_SHD,
            self::R_CLASS_FAC_BUILDN_SHLSUR,
            self::R_CLASS_FAC_BUILDN_SHLUND,
            self::R_CLASS_FAC_BUILDN_SHOP,
            self::R_CLASS_FAC_BUILDN_TOW,
            self::R_CLASS_FAC_BUILDN_TUN,
            self::R_CLASS_FAC_BUILDN_WALL,
            self::R_CLASS_FAC_BUILDN_WTW,
            self::R_CLASS_FAC_DEPOT_BIO,
            self::R_CLASS_FAC_DEPOT_CBRN,
            self::R_CLASS_FAC_DEPOT_CHM,
            self::R_CLASS_FAC_DEPOT_ENG,
            self::R_CLASS_FAC_DEPOT_MED,
            self::R_CLASS_FAC_DEPOT_MUN,
            self::R_CLASS_FAC_DEPOT_POL,
            self::R_CLASS_FAC_NETWK_ADSL,
            self::R_CLASS_FAC_NETWK_ATM,
            self::R_CLASS_FAC_NETWK_CTZALT,
            self::R_CLASS_FAC_NETWK_EMGNWK,
            self::R_CLASS_FAC_NETWK_GPRS,
            self::R_CLASS_FAC_NETWK_GSM,
            self::R_CLASS_FAC_NETWK_INTRAN,
            self::R_CLASS_FAC_NETWK_INTRNT,
            self::R_CLASS_FAC_NETWK_ISDN,
            self::R_CLASS_FAC_NETWK_LAN,
            self::R_CLASS_FAC_NETWK_PAMR,
            self::R_CLASS_FAC_NETWK_PDMR,
            self::R_CLASS_FAC_NETWK_PGSM,
            self::R_CLASS_FAC_NETWK_PSTN,
            self::R_CLASS_FAC_NETWK_RADEHF,
            self::R_CLASS_FAC_NETWK_RADHF,
            self::R_CLASS_FAC_NETWK_RADIO,
            self::R_CLASS_FAC_NETWK_RADLF,
            self::R_CLASS_FAC_NETWK_RADMF,
            self::R_CLASS_FAC_NETWK_RADSHF,
            self::R_CLASS_FAC_NETWK_RADUHF,
            self::R_CLASS_FAC_NETWK_RADVHF,
            self::R_CLASS_FAC_NETWK_RADVLF,
            self::R_CLASS_FAC_NETWK_RAYNET,
            self::R_CLASS_FAC_NETWK_RELAY,
            self::R_CLASS_FAC_NETWK_SDSL,
            self::R_CLASS_FAC_NETWK_TV,
            self::R_CLASS_FAC_NETWK_UMTS,
            self::R_CLASS_FAC_NETWK_VDSL,
            self::R_CLASS_FAC_NETWK_WAN,
            self::R_CLASS_FAC_NETWK_WIMAX,
            self::R_CLASS_FAC_NETWK_WLAN,
            self::R_CLASS_FAC_OPR_AMBFAC,
            self::R_CLASS_FAC_OPR_BDHOLD,
            self::R_CLASS_FAC_OPR_CAMP,
            self::R_CLASS_FAC_OPR_CASBUR,
            self::R_CLASS_FAC_OPR_CASCLR,
            self::R_CLASS_FAC_OPR_CASCOL,
            self::R_CLASS_FAC_OPR_CP,
            self::R_CLASS_FAC_OPR_CSCLPT,
            self::R_CLASS_FAC_OPR_CVCLPT,
            self::R_CLASS_FAC_OPR_DEBRDP,
            self::R_CLASS_FAC_OPR_DECONP,
            self::R_CLASS_FAC_OPR_DISBED,
            self::R_CLASS_FAC_OPR_DOCFAC,
            self::R_CLASS_FAC_OPR_EMMORT,
            self::R_CLASS_FAC_OPR_EQPOOL,
            self::R_CLASS_FAC_OPR_EVASSP,
            self::R_CLASS_FAC_OPR_FACAIR,
            self::R_CLASS_FAC_OPR_FACMIL,
            self::R_CLASS_FAC_OPR_FACNAV,
            self::R_CLASS_FAC_OPR_FAMFRD,
            self::R_CLASS_FAC_OPR_FIRFAC,
            self::R_CLASS_FAC_OPR_FSAAMM,
            self::R_CLASS_FAC_OPR_GERBED,
            self::R_CLASS_FAC_OPR_HOLD,
            self::R_CLASS_FAC_OPR_HPD,
            self::R_CLASS_FAC_OPR_HPT,
            self::R_CLASS_FAC_OPR_HSP,
            self::R_CLASS_FAC_OPR_HSPFLD,
            self::R_CLASS_FAC_OPR_HSPFLD2,
            self::R_CLASS_FAC_OPR_IRM,
            self::R_CLASS_FAC_OPR_MARSHAL,
            self::R_CLASS_FAC_OPR_MATBED,
            self::R_CLASS_FAC_OPR_MEDBED,
            self::R_CLASS_FAC_OPR_MEDSPT,
            self::R_CLASS_FAC_OPR_MOBLCP,
            self::R_CLASS_FAC_OPR_OPCTCN,
            self::R_CLASS_FAC_OPR_PHARMA,
            self::R_CLASS_FAC_OPR_POLFAC,
            self::R_CLASS_FAC_OPR_POLPT,
            self::R_CLASS_FAC_OPR_REFARE,
            self::R_CLASS_FAC_OPR_RRRSPT,
            self::R_CLASS_FAC_OPR_SITLOG,
            self::R_CLASS_FAC_OPR_SPTARE,
            self::R_CLASS_FAC_OPR_SRVCNT,
            self::R_CLASS_FAC_OPR_STCOCN,
            self::R_CLASS_FAC_OPR_STCTCN,
            self::R_CLASS_FAC_OPR_TCCTCN,
            self::R_CLASS_FAC_OTH_ACCOM,
            self::R_CLASS_FAC_OTH_AIRFLD,
            self::R_CLASS_FAC_OTH_BANK,
            self::R_CLASS_FAC_OTH_BATH,
            self::R_CLASS_FAC_OTH_CAN,
            self::R_CLASS_FAC_OTH_CEM,
            self::R_CLASS_FAC_OTH_DCH,
            self::R_CLASS_FAC_OTH_ELCINS,
            self::R_CLASS_FAC_OTH_ELCSPL,
            self::R_CLASS_FAC_OTH_EQIMFT,
            self::R_CLASS_FAC_OTH_FACGOV,
            self::R_CLASS_FAC_OTH_FACPOW,
            self::R_CLASS_FAC_OTH_FACTEC,
            self::R_CLASS_FAC_OTH_FACTEL,
            self::R_CLASS_FAC_OTH_FACTRN,
            self::R_CLASS_FAC_OTH_FATST,
            self::R_CLASS_FAC_OTH_FERINS,
            self::R_CLASS_FAC_OTH_FHPT,
            self::R_CLASS_FAC_OTH_LGRLPT,
            self::R_CLASS_FAC_OTH_MAINTF,
            self::R_CLASS_FAC_OTH_PTL,
            self::R_CLASS_FAC_OTH_RES,
            self::R_CLASS_FAC_OTH_VST,
            self::R_CLASS_FAC_OTH_WATSPL,
            self::R_CLASS_FAC_OTH_WSHFAC,
            self::R_CLASS_FAC_WATFIR_FOMBLK,
            self::R_CLASS_FAC_WATFIR_HYDRNT,
            self::R_CLASS_FAC_WATFIR_TOWNMN,
            self::R_CLASS_HUM_CAPAB,
            self::R_CLASS_HUM_PERSON,
            self::R_CLASS_HUM_UNIT,
            self::R_CLASS_HUM_CAPAB_AMB,
            self::R_CLASS_HUM_CAPAB_FIR,
            self::R_CLASS_HUM_CAPAB_MED,
            self::R_CLASS_HUM_CAPAB_MIL,
            self::R_CLASS_HUM_CAPAB_POL,
            self::R_CLASS_HUM_CAPAB_TRP,
            self::R_CLASS_HUM_CAPAB_AMB_INCOFF,
            self::R_CLASS_HUM_CAPAB_AMB_PARAMD,
            self::R_CLASS_HUM_CAPAB_AMB_SAFOFF,
            self::R_CLASS_HUM_CAPAB_AMB_TECHNIC,
            self::R_CLASS_HUM_CAPAB_FIR_BACOFF,
            self::R_CLASS_HUM_CAPAB_FIR_BAEOFF,
            self::R_CLASS_HUM_CAPAB_FIR_COMOFF,
            self::R_CLASS_HUM_CAPAB_FIR_CONOFF,
            self::R_CLASS_HUM_CAPAB_FIR_DECOFF,
            self::R_CLASS_HUM_CAPAB_FIR_FINOFF,
            self::R_CLASS_HUM_CAPAB_FIR_FOMOFF,
            self::R_CLASS_HUM_CAPAB_FIR_HAZOFF,
            self::R_CLASS_HUM_CAPAB_FIR_INCCOM,
            self::R_CLASS_HUM_CAPAB_FIR_LIAOFF,
            self::R_CLASS_HUM_CAPAB_FIR_LOGOFF,
            self::R_CLASS_HUM_CAPAB_FIR_MAROFF,
            self::R_CLASS_HUM_CAPAB_FIR_MEDOFF,
            self::R_CLASS_HUM_CAPAB_FIR_OPRCOM,
            self::R_CLASS_HUM_CAPAB_FIR_SAFOFF,
            self::R_CLASS_HUM_CAPAB_FIR_SALOFF,
            self::R_CLASS_HUM_CAPAB_FIR_SECCOM,
            self::R_CLASS_HUM_CAPAB_FIR_STAOFF,
            self::R_CLASS_HUM_CAPAB_FIR_STRCOM,
            self::R_CLASS_HUM_CAPAB_FIR_TACCOM,
            self::R_CLASS_HUM_CAPAB_FIR_WATOFF,
            self::R_CLASS_HUM_CAPAB_MED_ANSPHY,
            self::R_CLASS_HUM_CAPAB_MED_DNTPHY,
            self::R_CLASS_HUM_CAPAB_MED_DOCTOR,
            self::R_CLASS_HUM_CAPAB_MED_GYNPHY,
            self::R_CLASS_HUM_CAPAB_MED_HDNPHY,
            self::R_CLASS_HUM_CAPAB_MED_INMPHY,
            self::R_CLASS_HUM_CAPAB_MED_NURSE,
            self::R_CLASS_HUM_CAPAB_MED_ORTPHY,
            self::R_CLASS_HUM_CAPAB_MED_OTHPHY,
            self::R_CLASS_HUM_CAPAB_MED_PRCPHY,
            self::R_CLASS_HUM_CAPAB_MED_PSYPHY,
            self::R_CLASS_HUM_CAPAB_MED_PTHPHY,
            self::R_CLASS_HUM_CAPAB_MED_RADPHY,
            self::R_CLASS_HUM_CAPAB_MED_SURPHY,
            self::R_CLASS_HUM_CAPAB_MIL_AUTCDR,
            self::R_CLASS_HUM_CAPAB_MIL_INTOFF,
            self::R_CLASS_HUM_CAPAB_MIL_LIAISN,
            self::R_CLASS_HUM_CAPAB_MIL_OF1,
            self::R_CLASS_HUM_CAPAB_MIL_OF10,
            self::R_CLASS_HUM_CAPAB_MIL_OF2,
            self::R_CLASS_HUM_CAPAB_MIL_OF3,
            self::R_CLASS_HUM_CAPAB_MIL_OF4,
            self::R_CLASS_HUM_CAPAB_MIL_OF5,
            self::R_CLASS_HUM_CAPAB_MIL_OF6,
            self::R_CLASS_HUM_CAPAB_MIL_OF7,
            self::R_CLASS_HUM_CAPAB_MIL_OF8,
            self::R_CLASS_HUM_CAPAB_MIL_OF9,
            self::R_CLASS_HUM_CAPAB_MIL_OFFR,
            self::R_CLASS_HUM_CAPAB_MIL_OPSOFF,
            self::R_CLASS_HUM_CAPAB_MIL_OR1,
            self::R_CLASS_HUM_CAPAB_MIL_OR2,
            self::R_CLASS_HUM_CAPAB_MIL_OR3,
            self::R_CLASS_HUM_CAPAB_MIL_OR4,
            self::R_CLASS_HUM_CAPAB_MIL_OR5,
            self::R_CLASS_HUM_CAPAB_MIL_OR6,
            self::R_CLASS_HUM_CAPAB_MIL_OR7,
            self::R_CLASS_HUM_CAPAB_MIL_OR8,
            self::R_CLASS_HUM_CAPAB_MIL_OR9,
            self::R_CLASS_HUM_CAPAB_MIL_OTHR,
            self::R_CLASS_HUM_CAPAB_MIL_POC,
            self::R_CLASS_HUM_CAPAB_POL_BMBOFF,
            self::R_CLASS_HUM_CAPAB_POL_CASOFF,
            self::R_CLASS_HUM_CAPAB_POL_COFF,
            self::R_CLASS_HUM_CAPAB_POL_DETCTV,
            self::R_CLASS_HUM_CAPAB_POL_DIVER,
            self::R_CLASS_HUM_CAPAB_POL_MOM,
            self::R_CLASS_HUM_CAPAB_POL_PIO,
            self::R_CLASS_HUM_CAPAB_POL_PMR,
            self::R_CLASS_HUM_CAPAB_POL_RDINV,
            self::R_CLASS_HUM_CAPAB_POL_SCO,
            self::R_CLASS_HUM_CAPAB_POL_SIO,
            self::R_CLASS_HUM_CAPAB_POL_STTTK,
            self::R_CLASS_HUM_CAPAB_TRP_AIRFW,
            self::R_CLASS_HUM_CAPAB_TRP_AIRRW,
            self::R_CLASS_HUM_CAPAB_TRP_AMPH,
            self::R_CLASS_HUM_CAPAB_TRP_LNDRAI,
            self::R_CLASS_HUM_CAPAB_TRP_LNDWHL,
            self::R_CLASS_HUM_CAPAB_TRP_SEASS,
            self::R_CLASS_HUM_CAPAB_TRP_SEASUR,
            self::R_CLASS_HUM_PERSON_CFIROF,
            self::R_CLASS_HUM_PERSON_GOVEMP,
            self::R_CLASS_HUM_PERSON_INTLCT,
            self::R_CLASS_HUM_PERSON_JRNLST,
            self::R_CLASS_HUM_PERSON_MEDIA,
            self::R_CLASS_HUM_PERSON_NONGVE,
            self::R_CLASS_HUM_PERSON_POLCHF,
            self::R_CLASS_HUM_PERSON_VILELD,
            self::R_CLASS_HUM_PERSON_WRITER,
            self::R_CLASS_HUM_UNIT_AIRLSN,
            self::R_CLASS_HUM_UNIT_C2,
            self::R_CLASS_HUM_UNIT_CBRN,
            self::R_CLASS_HUM_UNIT_CONST,
            self::R_CLASS_HUM_UNIT_CRSMAN,
            self::R_CLASS_HUM_UNIT_DISID,
            self::R_CLASS_HUM_UNIT_EMPOFF,
            self::R_CLASS_HUM_UNIT_ENG,
            self::R_CLASS_HUM_UNIT_ENVOFF,
            self::R_CLASS_HUM_UNIT_FINANC,
            self::R_CLASS_HUM_UNIT_FIXWNG,
            self::R_CLASS_HUM_UNIT_GUID,
            self::R_CLASS_HUM_UNIT_HELCTR,
            self::R_CLASS_HUM_UNIT_LAWENF,
            self::R_CLASS_HUM_UNIT_LNDSPT,
            self::R_CLASS_HUM_UNIT_LOG,
            self::R_CLASS_HUM_UNIT_MAGRSP,
            self::R_CLASS_HUM_UNIT_MAINT,
            self::R_CLASS_HUM_UNIT_MDSADV,
            self::R_CLASS_HUM_UNIT_MEDCL,
            self::R_CLASS_HUM_UNIT_MST,
            self::R_CLASS_HUM_UNIT_MSURTM,
            self::R_CLASS_HUM_UNIT_NAVAL,
            self::R_CLASS_HUM_UNIT_POL,
            self::R_CLASS_HUM_UNIT_PSYCH,
            self::R_CLASS_HUM_UNIT_RAILWY,
            self::R_CLASS_HUM_UNIT_RECCE,
            self::R_CLASS_HUM_UNIT_RELCHP,
            self::R_CLASS_HUM_UNIT_RIVERN,
            self::R_CLASS_HUM_UNIT_SAR,
            self::R_CLASS_HUM_UNIT_SECPOL,
            self::R_CLASS_HUM_UNIT_SHRPAT,
            self::R_CLASS_HUM_UNIT_SPECIA,
            self::R_CLASS_HUM_UNIT_SURG,
            self::R_CLASS_HUM_UNIT_TRAUMA,
            self::R_CLASS_HUM_UNIT_TRNPTN,
            self::R_CLASS_HUM_UNIT_VET,
            self::R_CLASS_HUM_UNIT_WLFCOR,
            self::R_CLASS_HUM_UNIT_POL_AIRSPT,
            self::R_CLASS_HUM_UNIT_POL_MNTPOL,
            self::R_CLASS_HUM_UNIT_POL_PUBORD,
            self::R_CLASS_HUM_UNIT_POL_RDSPT,
            self::R_CLASS_HUM_UNIT_POL_SPCLST,
            self::R_CLASS_HUM_UNIT_SAR_CSAR,
            self::R_CLASS_HUM_UNIT_SAR_MSAR,
            self::R_CLASS_HUM_UNIT_SAR_RSAR,
            self::R_CLASS_HUM_UNIT_SAR_RST,
            self::R_CLASS_HUM_UNIT_SAR_SSAR,
            self::R_CLASS_HUM_UNIT_SAR_USAR,
            self::R_CLASS_HUM_UNIT_SAR_WSAR,
            self::R_CLASS_HUM_UNIT_SAR_USAR_CANIN,
            self::R_CLASS_HUM_UNIT_SAR_USAR_DETEC,
            self::R_CLASS_MAT_CM,
            self::R_CLASS_MAT_EQ,
            self::R_CLASS_MAT_VEH,
            self::R_CLASS_MAT_CM_ABSAG,
            self::R_CLASS_MAT_CM_BIOAGN,
            self::R_CLASS_MAT_CM_CHMAGN,
            self::R_CLASS_MAT_CM_CON,
            self::R_CLASS_MAT_CM_EXTAG,
            self::R_CLASS_MAT_CM_FOO,
            self::R_CLASS_MAT_CM_FUEL,
            self::R_CLASS_MAT_CM_FUSE,
            self::R_CLASS_MAT_CM_LUBRIC,
            self::R_CLASS_MAT_CM_MATING,
            self::R_CLASS_MAT_CM_MEDICN,
            self::R_CLASS_MAT_CM_MEDSPL,
            self::R_CLASS_MAT_CM_MEGPHN,
            self::R_CLASS_MAT_CM_MONEY,
            self::R_CLASS_MAT_CM_OIL,
            self::R_CLASS_MAT_CM_PAINT,
            self::R_CLASS_MAT_CM_PAPER,
            self::R_CLASS_MAT_CM_PPE,
            self::R_CLASS_MAT_CM_RATCO,
            self::R_CLASS_MAT_CM_RATFR,
            self::R_CLASS_MAT_CM_RATTI,
            self::R_CLASS_MAT_CM_RETAG,
            self::R_CLASS_MAT_CM_TIMBER,
            self::R_CLASS_MAT_CM_UNIFRM,
            self::R_CLASS_MAT_CM_WIRE,
            self::R_CLASS_MAT_CM_WTREXT,
            self::R_CLASS_MAT_CM_WTRPOT,
            self::R_CLASS_MAT_CM_ABSAG_CHM,
            self::R_CLASS_MAT_CM_ABSAG_PHY,
            self::R_CLASS_MAT_CM_EXTAG_CO2,
            self::R_CLASS_MAT_CM_EXTAG_DRYMIN,
            self::R_CLASS_MAT_CM_EXTAG_FATFIR,
            self::R_CLASS_MAT_CM_EXTAG_FOAM,
            self::R_CLASS_MAT_CM_EXTAG_HALON,
            self::R_CLASS_MAT_CM_EXTAG_INERT,
            self::R_CLASS_MAT_CM_EXTAG_METPWD,
            self::R_CLASS_MAT_CM_EXTAG_POWDER,
            self::R_CLASS_MAT_CM_EXTAG_FOAM_AFFF,
            self::R_CLASS_MAT_CM_EXTAG_FOAM_AFFFAR,
            self::R_CLASS_MAT_CM_EXTAG_FOAM_OTH,
            self::R_CLASS_MAT_CM_FUEL_AVNFU,
            self::R_CLASS_MAT_CM_FUEL_DIESEL,
            self::R_CLASS_MAT_CM_FUEL_KEROS,
            self::R_CLASS_MAT_CM_FUEL_LPG,
            self::R_CLASS_MAT_CM_FUEL_NATGAS,
            self::R_CLASS_MAT_CM_FUEL_PETROL,
            self::R_CLASS_MAT_CM_MEDICN_1_STAID,
            self::R_CLASS_MAT_CM_MEDICN_AMPHTM,
            self::R_CLASS_MAT_CM_MEDICN_BLOOD,
            self::R_CLASS_MAT_CM_MEDICN_BNDDR,
            self::R_CLASS_MAT_CM_MEDICN_KTMINE,
            self::R_CLASS_MAT_CM_MEDICN_MORFIN,
            self::R_CLASS_MAT_CM_MEDICN_WTRMED,
            self::R_CLASS_MAT_CM_PPE_CBRNKIT,
            self::R_CLASS_MAT_CM_PPE_CLOTH,
            self::R_CLASS_MAT_CM_PPE_RESP,
            self::R_CLASS_MAT_CM_PPE_SURCOT,
            self::R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL,
            self::R_CLASS_MAT_CM_PPE_CLOTH_FFCLO,
            self::R_CLASS_MAT_CM_PPE_CLOTH_FKIT,
            self::R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL_CHEMB,
            self::R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL_CHEMG,
            self::R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL_GASSU,
            self::R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL_LIQSU,
            self::R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL_SPLASU,
            self::R_CLASS_MAT_CM_PPE_CLOTH_CHEMCL_TEMPSU,
            self::R_CLASS_MAT_EQ_CBRN,
            self::R_CLASS_MAT_EQ_ELC,
            self::R_CLASS_MAT_EQ_ENG,
            self::R_CLASS_MAT_EQ_OTH,
            self::R_CLASS_MAT_EQ_POLICE,
            self::R_CLASS_MAT_EQ_CBRN_ABICHM,
            self::R_CLASS_MAT_EQ_CBRN_ABIDET,
            self::R_CLASS_MAT_EQ_CBRN_ACHDET,
            self::R_CLASS_MAT_EQ_CBRN_ARDDET,
            self::R_CLASS_MAT_EQ_CBRN_BIOINT,
            self::R_CLASS_MAT_EQ_CBRN_BIOSTO,
            self::R_CLASS_MAT_EQ_CBRN_CBRNDEC,
            self::R_CLASS_MAT_EQ_CBRN_CBRNREC,
            self::R_CLASS_MAT_EQ_CBRN_CHMMON,
            self::R_CLASS_MAT_EQ_CBRN_MSSPTR,
            self::R_CLASS_MAT_EQ_CBRN_RDSPTR,
            self::R_CLASS_MAT_EQ_ELC_AMTRAD,
            self::R_CLASS_MAT_EQ_ELC_C3_I,
            self::R_CLASS_MAT_EQ_ELC_COMSYS,
            self::R_CLASS_MAT_EQ_ELC_COMVEH,
            self::R_CLASS_MAT_EQ_ELC_MULTIRE,
            self::R_CLASS_MAT_EQ_ELC_NAV,
            self::R_CLASS_MAT_EQ_ELC_NAVRAD,
            self::R_CLASS_MAT_EQ_ELC_OTH,
            self::R_CLASS_MAT_EQ_ELC_POWGN,
            self::R_CLASS_MAT_EQ_ELC_RIDD,
            self::R_CLASS_MAT_EQ_ELC_SEN,
            self::R_CLASS_MAT_EQ_ELC_SONAR,
            self::R_CLASS_MAT_EQ_ELC_THIMC,
            self::R_CLASS_MAT_EQ_ELC_VIBRA,
            self::R_CLASS_MAT_EQ_ELC_COMSYS_MEGPHN,
            self::R_CLASS_MAT_EQ_ELC_COMSYS_PAGER,
            self::R_CLASS_MAT_EQ_ELC_COMSYS_PMRRDIO,
            self::R_CLASS_MAT_EQ_ELC_COMSYS_PUBADD,
            self::R_CLASS_MAT_EQ_ELC_COMSYS_RDBRCT,
            self::R_CLASS_MAT_EQ_ENG_BRIDGG,
            self::R_CLASS_MAT_EQ_ENG_CNSTVE,
            self::R_CLASS_MAT_EQ_ENG_CONST,
            self::R_CLASS_MAT_EQ_ENG_DOZER,
            self::R_CLASS_MAT_EQ_ENG_ERTHMV,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT,
            self::R_CLASS_MAT_EQ_ENG_INTEL,
            self::R_CLASS_MAT_EQ_ENG_MINECL,
            self::R_CLASS_MAT_EQ_ENG_MINEDT,
            self::R_CLASS_MAT_EQ_ENG_MINEMR,
            self::R_CLASS_MAT_EQ_ENG_WPNPRT,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_BRHTAP,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_CEAR,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_CEC,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_CECH,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_CEEV,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_CEM,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_CEPC,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_CEPO,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_CEPOL,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_CER,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_CESD,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_GRDMON,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_MPR,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_RAR,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_UMIR,
            self::R_CLASS_MAT_EQ_ENG_FIRFGT_VAMUR,
            self::R_CLASS_MAT_EQ_ENG_INTEL_CAMERA,
            self::R_CLASS_MAT_EQ_ENG_INTEL_CCTVCM,
            self::R_CLASS_MAT_EQ_ENG_INTEL_CDVDOG,
            self::R_CLASS_MAT_EQ_ENG_INTEL_FSPDCM,
            self::R_CLASS_MAT_EQ_ENG_INTEL_FTFLCM,
            self::R_CLASS_MAT_EQ_ENG_INTEL_PSPDCM,
            self::R_CLASS_MAT_EQ_ENG_INTEL_TCKDOG,
            self::R_CLASS_MAT_EQ_ENG_WPNPRT_BALVST,
            self::R_CLASS_MAT_EQ_ENG_WPNPRT_BATON,
            self::R_CLASS_MAT_EQ_ENG_WPNPRT_ENFDOG,
            self::R_CLASS_MAT_EQ_ENG_WPNPRT_FIREARM,
            self::R_CLASS_MAT_EQ_ENG_WPNPRT_HNDCUF,
            self::R_CLASS_MAT_EQ_ENG_WPNPRT_OFFPRT,
            self::R_CLASS_MAT_EQ_ENG_WPNPRT_PRSCNT,
            self::R_CLASS_MAT_EQ_OTH_BLNKT,
            self::R_CLASS_MAT_EQ_OTH_CONTNR,
            self::R_CLASS_MAT_EQ_OTH_CUTING,
            self::R_CLASS_MAT_EQ_OTH_TANK,
            self::R_CLASS_MAT_EQ_OTH_TENT,
            self::R_CLASS_MAT_EQ_OTH_WATPUR,
            self::R_CLASS_MAT_EQ_POLICE_BRTEST,
            self::R_CLASS_MAT_EQ_POLICE_CONE,
            self::R_CLASS_MAT_EQ_POLICE_LAMP,
            self::R_CLASS_MAT_EQ_POLICE_STINGER,
            self::R_CLASS_MAT_EQ_POLICE_TORCH,
            self::R_CLASS_MAT_EQ_POLICE_UNFRMC,
            self::R_CLASS_MAT_EQ_POLICE_UNFRMN,
            self::R_CLASS_MAT_VEH_AIRCRF,
            self::R_CLASS_MAT_VEH_HORSE,
            self::R_CLASS_MAT_VEH_RAILVE,
            self::R_CLASS_MAT_VEH_ROADVE,
            self::R_CLASS_MAT_VEH_VESSEL,
            self::R_CLASS_MAT_VEH_AIRCRF_AIRTRS,
            self::R_CLASS_MAT_VEH_AIRCRF_CMDCTL,
            self::R_CLASS_MAT_VEH_AIRCRF_HEL,
            self::R_CLASS_MAT_VEH_AIRCRF_HELCMD,
            self::R_CLASS_MAT_VEH_AIRCRF_HELMED,
            self::R_CLASS_MAT_VEH_AIRCRF_HELREC,
            self::R_CLASS_MAT_VEH_AIRCRF_MEDEVC,
            self::R_CLASS_MAT_VEH_AIRCRF_PLANE,
            self::R_CLASS_MAT_VEH_AIRCRF_POLHEL,
            self::R_CLASS_MAT_VEH_AIRCRF_RECCE,
            self::R_CLASS_MAT_VEH_AIRCRF_SAR,
            self::R_CLASS_MAT_VEH_AIRCRF_TANKER,
            self::R_CLASS_MAT_VEH_AIRCRF_UAV,
            self::R_CLASS_MAT_VEH_RAILVE_LCMDSE,
            self::R_CLASS_MAT_VEH_RAILVE_LCMDSL,
            self::R_CLASS_MAT_VEH_RAILVE_LCMELC,
            self::R_CLASS_MAT_VEH_RAILVE_LCMSTM,
            self::R_CLASS_MAT_VEH_RAILVE_LCMTND,
            self::R_CLASS_MAT_VEH_RAILVE_LCMTVE,
            self::R_CLASS_MAT_VEH_RAILVE_RLDEQP,
            self::R_CLASS_MAT_VEH_RAILVE_RLLSTK,
            self::R_CLASS_MAT_VEH_RAILVE_TRAM,
            self::R_CLASS_MAT_VEH_RAILVE_WGNART,
            self::R_CLASS_MAT_VEH_RAILVE_WGNBRK,
            self::R_CLASS_MAT_VEH_RAILVE_WGNCAR,
            self::R_CLASS_MAT_VEH_RAILVE_WGNCRG,
            self::R_CLASS_MAT_VEH_RAILVE_WGNCSS,
            self::R_CLASS_MAT_VEH_RAILVE_WGNCTL,
            self::R_CLASS_MAT_VEH_RAILVE_WGNFLB,
            self::R_CLASS_MAT_VEH_RAILVE_WGNFUL,
            self::R_CLASS_MAT_VEH_RAILVE_WGNHPR,
            self::R_CLASS_MAT_VEH_RAILVE_WGNISO,
            self::R_CLASS_MAT_VEH_RAILVE_WGNLQD,
            self::R_CLASS_MAT_VEH_RAILVE_WGNMNR,
            self::R_CLASS_MAT_VEH_RAILVE_WGNOPC,
            self::R_CLASS_MAT_VEH_RAILVE_WGNPAS,
            self::R_CLASS_MAT_VEH_RAILVE_WGNRFG,
            self::R_CLASS_MAT_VEH_RAILVE_WGNRPR,
            self::R_CLASS_MAT_VEH_RAILVE_WGNSPP,
            self::R_CLASS_MAT_VEH_RAILVE_WGNWAT,
            self::R_CLASS_MAT_VEH_RAILVE_WGNWFL,
            self::R_CLASS_MAT_VEH_ROADVE_AMBUL,
            self::R_CLASS_MAT_VEH_ROADVE_AUTOMO,
            self::R_CLASS_MAT_VEH_ROADVE_BICYCL,
            self::R_CLASS_MAT_VEH_ROADVE_BUS,
            self::R_CLASS_MAT_VEH_ROADVE_CCTRCK,
            self::R_CLASS_MAT_VEH_ROADVE_CRANE,
            self::R_CLASS_MAT_VEH_ROADVE_FRFGTN,
            self::R_CLASS_MAT_VEH_ROADVE_HETVEH,
            self::R_CLASS_MAT_VEH_ROADVE_MAINT,
            self::R_CLASS_MAT_VEH_ROADVE_MHVEH,
            self::R_CLASS_MAT_VEH_ROADVE_MILUV,
            self::R_CLASS_MAT_VEH_ROADVE_MOTCYC,
            self::R_CLASS_MAT_VEH_ROADVE_POD,
            self::R_CLASS_MAT_VEH_ROADVE_POLICE,
            self::R_CLASS_MAT_VEH_ROADVE_SEMI,
            self::R_CLASS_MAT_VEH_ROADVE_TRACTR,
            self::R_CLASS_MAT_VEH_ROADVE_TRAILR,
            self::R_CLASS_MAT_VEH_ROADVE_TRLBUS,
            self::R_CLASS_MAT_VEH_ROADVE_TRUCK,
            self::R_CLASS_MAT_VEH_ROADVE_FRFGTN_AERIAL,
            self::R_CLASS_MAT_VEH_ROADVE_FRFGTN_BREATH,
            self::R_CLASS_MAT_VEH_ROADVE_FRFGTN_C3,
            self::R_CLASS_MAT_VEH_ROADVE_FRFGTN_FRF,
            self::R_CLASS_MAT_VEH_ROADVE_FRFGTN_HAZMAT,
            self::R_CLASS_MAT_VEH_ROADVE_FRFGTN_OTHR,
            self::R_CLASS_MAT_VEH_ROADVE_FRFGTN_PERCAR,
            self::R_CLASS_MAT_VEH_ROADVE_FRFGTN_PUMP,
            self::R_CLASS_MAT_VEH_ROADVE_FRFGTN_RSC,
            self::R_CLASS_MAT_VEH_ROADVE_POLICE_COMLIA,
            self::R_CLASS_MAT_VEH_ROADVE_POLICE_DOGUNT,
            self::R_CLASS_MAT_VEH_ROADVE_POLICE_GENPUR,
            self::R_CLASS_MAT_VEH_ROADVE_POLICE_HAZMAT,
            self::R_CLASS_MAT_VEH_ROADVE_POLICE_MBIKE,
            self::R_CLASS_MAT_VEH_ROADVE_POLICE_PATROL,
            self::R_CLASS_MAT_VEH_ROADVE_POLICE_RSPONSE,
            self::R_CLASS_MAT_VEH_ROADVE_POLICE_TRAFFIC,
            self::R_CLASS_MAT_VEH_ROADVE_POLICE_TRANSIT,
            self::R_CLASS_MAT_VEH_ROADVE_POLICE_VAN,
            self::R_CLASS_MAT_VEH_VESSEL_AIRCAR,
            self::R_CLASS_MAT_VEH_VESSEL_AMPH,
            self::R_CLASS_MAT_VEH_VESSEL_BARGE,
            self::R_CLASS_MAT_VEH_VESSEL_BARSHP,
            self::R_CLASS_MAT_VEH_VESSEL_BRDGBT,
            self::R_CLASS_MAT_VEH_VESSEL_CNTSHP,
            self::R_CLASS_MAT_VEH_VESSEL_CSRSHP,
            self::R_CLASS_MAT_VEH_VESSEL_CSTSHP,
            self::R_CLASS_MAT_VEH_VESSEL_DPSMVS,
            self::R_CLASS_MAT_VEH_VESSEL_FERRY,
            self::R_CLASS_MAT_VEH_VESSEL_FIRBOT,
            self::R_CLASS_MAT_VEH_VESSEL_FLTCRN,
            self::R_CLASS_MAT_VEH_VESSEL_FLTDRG,
            self::R_CLASS_MAT_VEH_VESSEL_FLTDRY,
            self::R_CLASS_MAT_VEH_VESSEL_FREBLK,
            self::R_CLASS_MAT_VEH_VESSEL_FRELIQ,
            self::R_CLASS_MAT_VEH_VESSEL_HOSSHP,
            self::R_CLASS_MAT_VEH_VESSEL_HOVCRF,
            self::R_CLASS_MAT_VEH_VESSEL_ICEBRK,
            self::R_CLASS_MAT_VEH_VESSEL_LAUNCH,
            self::R_CLASS_MAT_VEH_VESSEL_LGHTER,
            self::R_CLASS_MAT_VEH_VESSEL_LNDCRF,
            self::R_CLASS_MAT_VEH_VESSEL_MERSHP,
            self::R_CLASS_MAT_VEH_VESSEL_MOBLS,
            self::R_CLASS_MAT_VEH_VESSEL_OILER,
            self::R_CLASS_MAT_VEH_VESSEL_PASSGR,
            self::R_CLASS_MAT_VEH_VESSEL_PATVES,
            self::R_CLASS_MAT_VEH_VESSEL_POLSPD,
            self::R_CLASS_MAT_VEH_VESSEL_PRV,
            self::R_CLASS_MAT_VEH_VESSEL_RAFT,
            self::R_CLASS_MAT_VEH_VESSEL_RPRSHP,
            self::R_CLASS_MAT_VEH_VESSEL_SAILVS,
            self::R_CLASS_MAT_VEH_VESSEL_SALSHP,
            self::R_CLASS_MAT_VEH_VESSEL_SMLLBO,
            self::R_CLASS_MAT_VEH_VESSEL_SUBMAR,
            self::R_CLASS_MAT_VEH_VESSEL_TANKER,
            self::R_CLASS_MAT_VEH_VESSEL_TENDER,
            self::R_CLASS_MAT_VEH_VESSEL_TUGBOT,
            self::R_CLASS_ORG_AMBUL,
            self::R_CLASS_ORG_CIVP,
            self::R_CLASS_ORG_COASTG,
            self::R_CLASS_ORG_DOCTOR,
            self::R_CLASS_ORG_ENVAGC,
            self::R_CLASS_ORG_FIRFS,
            self::R_CLASS_ORG_GEND,
            self::R_CLASS_ORG_HOSP,
            self::R_CLASS_ORG_IDCOM,
            self::R_CLASS_ORG_LCRESF,
            self::R_CLASS_ORG_LOCAUT,
            self::R_CLASS_ORG_MARAGC,
            self::R_CLASS_ORG_METAGC,
            self::R_CLASS_ORG_MIL,
            self::R_CLASS_ORG_NGO,
            self::R_CLASS_ORG_POLCNG,
            self::R_CLASS_ORG_POLICE,
            self::R_CLASS_ORG_RGRESF,
            self::R_CLASS_ORG_SPADPV,
            self::R_CLASS_ORG_TRS,
            self::R_CLASS_ORG_WATAGC,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('rCLASS', $data ?? [], null);
        $this->setIfExists('cAPABILITY', $data ?? [], null);
        $this->setIfExists('cHARACTERISTICS', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['rCLASS'] === null) {
            $invalidProperties[] = "'rCLASS' can't be null";
        }
        if ((count($this->container['rCLASS']) < 1)) {
            $invalidProperties[] = "invalid value for 'rCLASS', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rCLASS
     *
     * @return string[]
     */
    public function getRCLASS()
    {
        return $this->container['rCLASS'];
    }

    /**
     * Sets rCLASS
     *
     * @param string[] $rCLASS rCLASS
     *
     * @return self
     */
    public function setRCLASS($rCLASS)
    {
        if (is_null($rCLASS)) {
            throw new \InvalidArgumentException('non-nullable rCLASS cannot be null');
        }
        $allowedValues = $this->getRCLASSAllowableValues();
        if (array_diff($rCLASS, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'rCLASS', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }


        if ((count($rCLASS) < 1)) {
            throw new \InvalidArgumentException('invalid length for $rCLASS when calling Rtype., number of items must be greater than or equal to 1.');
        }
        $this->container['rCLASS'] = $rCLASS;

        return $this;
    }

    /**
     * Gets cAPABILITY
     *
     * @return string[]|null
     */
    public function getCAPABILITY()
    {
        return $this->container['cAPABILITY'];
    }

    /**
     * Sets cAPABILITY
     *
     * @param string[]|null $cAPABILITY cAPABILITY
     *
     * @return self
     */
    public function setCAPABILITY($cAPABILITY)
    {
        if (is_null($cAPABILITY)) {
            throw new \InvalidArgumentException('non-nullable cAPABILITY cannot be null');
        }
        $this->container['cAPABILITY'] = $cAPABILITY;

        return $this;
    }

    /**
     * Gets cHARACTERISTICS
     *
     * @return string[]|null
     */
    public function getCHARACTERISTICS()
    {
        return $this->container['cHARACTERISTICS'];
    }

    /**
     * Sets cHARACTERISTICS
     *
     * @param string[]|null $cHARACTERISTICS cHARACTERISTICS
     *
     * @return self
     */
    public function setCHARACTERISTICS($cHARACTERISTICS)
    {
        if (is_null($cHARACTERISTICS)) {
            throw new \InvalidArgumentException('non-nullable cHARACTERISTICS cannot be null');
        }
        $this->container['cHARACTERISTICS'] = $cHARACTERISTICS;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


