<?php
/**
 * Content
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  Hubsante\Model\edxl
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Hubsante\Model\edxl;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Content model.
 *
 * @package Hubsante\Model\edxl
 * @author  OpenAPI Generator team
 */

class Content 
{
        /**
     * @var ContentObject|null
     * @SerializedName("contentObject")
     * @Type("Hubsante\Model\edxl\ContentObject")
    */
    #[Assert\NotNull]
    #[Assert\Valid]
    #[Assert\Type("Hubsante\Model\edxl\ContentObject")]
    protected ?ContentObject $contentObject = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->contentObject = array_key_exists('contentObject', $data) ? $data['contentObject'] : $this->contentObject;
        }
    }

    /**
     * Gets contentObject.
     *
     * @return ContentObject|null
     */
    public function getContentObject(): ?ContentObject
    {
        return $this->contentObject;
    }

    /**
    * Sets contentObject.
    *
    * @param ContentObject|null $contentObject
    *
    * @return $this
    */
    public function setContentObject(?ContentObject $contentObject): self
    {
        $this->contentObject = $contentObject;

        return $this;
    }



}


