/**
 * Copyright © 2023-2024 Agence du Numerique en Sante (ANS)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 *
 *
 *
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

package com.hubsante.model.rcde;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.dataformat.xml.annotation.*;
import com.hubsante.model.rcde.DistributionElement;
import java.util.Arrays;
import java.util.Arrays;
import java.util.Objects;

/**
 * DistributionElementWrapper
 */
@JsonPropertyOrder(
    {DistributionElementWrapper.JSON_PROPERTY_DISTRIBUTION_ELEMENT})
@JsonInclude(JsonInclude.Include.NON_EMPTY)

public class DistributionElementWrapper {
  public static final String JSON_PROPERTY_DISTRIBUTION_ELEMENT =
      "DistributionElement";
  private DistributionElement distributionElement;

  public DistributionElementWrapper() {}

  public DistributionElementWrapper
  distributionElement(DistributionElement distributionElement) {

    this.distributionElement = distributionElement;
    return this;
  }

  /**
   * Get distributionElement
   * @return distributionElement
   **/
  @JsonProperty(JSON_PROPERTY_DISTRIBUTION_ELEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DistributionElement getDistributionElement() {
    return distributionElement;
  }

  @JsonProperty(JSON_PROPERTY_DISTRIBUTION_ELEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistributionElement(DistributionElement distributionElement) {
    this.distributionElement = distributionElement;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DistributionElementWrapper distributionElementWrapper =
        (DistributionElementWrapper)o;
    return Objects.equals(this.distributionElement,
                          distributionElementWrapper.distributionElement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(distributionElement);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DistributionElementWrapper {\n");
    sb.append("    distributionElement: ")
        .append(toIndentedString(distributionElement))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
