<?php
/**
 * Error
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  Hubsante\Model\report
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Hubsante\Model\report;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Error model.
 *
 * @package Hubsante\Model\report
 * @author  OpenAPI Generator team
 */

class Error 
{
        /**
     * @var ErrorCode|null
     * @SerializedName("errorCode")
     * @Type("Hubsante\Model\report\ErrorCode")
    */
    #[Assert\NotNull]
    #[Assert\Valid]
    #[Assert\Type("Hubsante\Model\report\ErrorCode")]
    protected ?ErrorCode $errorCode = null;

    /**
     * La ou les causes d&#39;erreur dans le message source
     *
     * @var string|null
     * @SerializedName("errorCause")
     * @Type("string")
    */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $errorCause = null;

    /**
     * @var []|null
     * @SerializedName("sourceMessage")
     * @Type("array<string, AnyType>")
    */
    #[Assert\All([
        new Assert\Type("AnyType"),
    ])]
    protected ?array $sourceMessage = null;

    /**
     * DistributionID du message source
     *
     * @var string|null
     * @SerializedName("referencedDistributionID")
     * @Type("string")
    */
    #[Assert\NotNull]
    #[Assert\Type("string")]
    protected ?string $referencedDistributionID = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->errorCode = array_key_exists('errorCode', $data) ? $data['errorCode'] : $this->errorCode;
            $this->errorCause = array_key_exists('errorCause', $data) ? $data['errorCause'] : $this->errorCause;
            $this->sourceMessage = array_key_exists('sourceMessage', $data) ? $data['sourceMessage'] : $this->sourceMessage;
            $this->referencedDistributionID = array_key_exists('referencedDistributionID', $data) ? $data['referencedDistributionID'] : $this->referencedDistributionID;
        }
    }

    /**
     * Gets errorCode.
     *
     * @return ErrorCode|null
     */
    public function getErrorCode(): ?ErrorCode
    {
        return $this->errorCode;
    }

    /**
    * Sets errorCode.
    *
    * @param ErrorCode|null $errorCode
    *
    * @return $this
    */
    public function setErrorCode(?ErrorCode $errorCode): self
    {
        $this->errorCode = $errorCode;

        return $this;
    }




    /**
     * Gets errorCause.
     *
     * @return string|null
     */
    public function getErrorCause(): ?string
    {
        return $this->errorCause;
    }

    /**
    * Sets errorCause.
    *
    * @param string|null $errorCause  La ou les causes d'erreur dans le message source
    *
    * @return $this
    */
    public function setErrorCause(?string $errorCause): self
    {
        $this->errorCause = $errorCause;

        return $this;
    }




    /**
     * Gets sourceMessage.
     *
     * @return []|null
     */
    public function getSourceMessage(): ?array
    {
        return $this->sourceMessage;
    }

    /**
    * Sets sourceMessage.
    *
    * @param []|null $sourceMessage
    *
    * @return $this
    */
    public function setSourceMessage(?array $sourceMessage = null): self
    {
        $this->sourceMessage = $sourceMessage;

        return $this;
    }




    /**
     * Gets referencedDistributionID.
     *
     * @return string|null
     */
    public function getReferencedDistributionID(): ?string
    {
        return $this->referencedDistributionID;
    }

    /**
    * Sets referencedDistributionID.
    *
    * @param string|null $referencedDistributionID  DistributionID du message source
    *
    * @return $this
    */
    public function setReferencedDistributionID(?string $referencedDistributionID): self
    {
        $this->referencedDistributionID = $referencedDistributionID;

        return $this;
    }



}


