<?php
/**
 * Identity
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  Hubsante\Model\health
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace Hubsante\Model\health;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\Accessor;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Identity model.
 *
 * @package Hubsante\Model\health
 * @author  OpenAPI Generator team
 */

class Identity 
{
        /**
     * @var InsStrictFeatures|null
     * @SerializedName("strictFeatures")
     * @Type("Hubsante\Model\health\InsStrictFeatures")
    */
    #[Assert\Type("Hubsante\Model\health\InsStrictFeatures")]
    protected ?InsStrictFeatures $strictFeatures = null;

    /**
     * @var DetailedName|null
     * @SerializedName("nonStrictFeatures")
     * @Type("Hubsante\Model\health\DetailedName")
    */
    #[Assert\Type("Hubsante\Model\health\DetailedName")]
    protected ?DetailedName $nonStrictFeatures = null;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        if (is_array($data)) {
            $this->strictFeatures = array_key_exists('strictFeatures', $data) ? $data['strictFeatures'] : $this->strictFeatures;
            $this->nonStrictFeatures = array_key_exists('nonStrictFeatures', $data) ? $data['nonStrictFeatures'] : $this->nonStrictFeatures;
        }
    }

    /**
     * Gets strictFeatures.
     *
     * @return InsStrictFeatures|null
     */
    public function getStrictFeatures(): ?InsStrictFeatures
    {
        return $this->strictFeatures;
    }

    /**
    * Sets strictFeatures.
    *
    * @param InsStrictFeatures|null $strictFeatures
    *
    * @return $this
    */
    public function setStrictFeatures(?InsStrictFeatures $strictFeatures = null): self
    {
        $this->strictFeatures = $strictFeatures;

        return $this;
    }




    /**
     * Gets nonStrictFeatures.
     *
     * @return DetailedName|null
     */
    public function getNonStrictFeatures(): ?DetailedName
    {
        return $this->nonStrictFeatures;
    }

    /**
    * Sets nonStrictFeatures.
    *
    * @param DetailedName|null $nonStrictFeatures
    *
    * @return $this
    */
    public function setNonStrictFeatures(?DetailedName $nonStrictFeatures = null): self
    {
        $this->nonStrictFeatures = $nonStrictFeatures;

        return $this;
    }



}


