"""Auto-generated nomenclature mapping. Do not edit by hand — regenerate via scripts/generate_nomenclatures_maps.py."""

MAP: dict[str, dict[str, str] | None] = {
    "R17": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R18": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R60": {"code": "R13", "label": "Risque d'explosion, présence de gaz"},
    "R61": {"code": "R13", "label": "Risque d'explosion, présence de gaz"},
    "R62": {"code": "R13", "label": "Risque d'explosion, présence de gaz"},
    "R63": {
        "code": "R19",
        "label": "Risque électrique/ risque lié à une ligne HT ou THT",
    },
    "R64": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R65": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R66": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R67": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R68": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R69": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R70": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R71": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R72": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R73": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R74": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R75": {"code": "R13", "label": "Risque d'explosion, présence de gaz"},
    "R76": {"code": "R13", "label": "Risque d'explosion, présence de gaz"},
    "R77": {"code": "R13", "label": "Risque d'explosion, présence de gaz"},
    "R78": {"code": "R13", "label": "Risque d'explosion, présence de gaz"},
    "R79": {"code": "R13", "label": "Risque d'explosion, présence de gaz"},
    "R80": {"code": "R13", "label": "Risque d'explosion, présence de gaz"},
    "R81": {"code": "R13", "label": "Risque d'explosion, présence de gaz"},
    "R82": {"code": "R13", "label": "Risque d'explosion, présence de gaz"},
    "R83": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R84": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R85": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R86": {"code": "R20", "label": "Difficulté d’accès sur site"},
    "R88": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R89": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R90": {"code": "R37", "label": "Situation instable/indéterminée"},
    "R91": {"code": "R25", "label": "Implication d’une personnalité"},
}
