<?php
/**
 * Location
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Hubsante
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OpenAPI
 *
 * OpenAPI
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hubsante\Model\cisu;

use \ArrayAccess;
use \Hubsante\ObjectSerializer;

/**
 * Location Class Doc Comment
 *
 * @category Class
 * @package  Hubsante
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Location implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'location';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'locID' => 'string',
        'locLabel' => 'string',
        'name' => 'string',
        'externalLocationId' => '\Hubsante\Model\cisu\ExternalLocationId[]',
        'detailedAddress' => '\Hubsante\Model\cisu\DetailedAddress',
        'city' => '\Hubsante\Model\cisu\City',
        'access' => '\Hubsante\Model\cisu\Access',
        'geometry' => '\Hubsante\Model\cisu\Geometry',
        'externalInfo' => '\Hubsante\Model\cisu\ExternalInfo[]',
        'country' => 'string',
        'freetext' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'locID' => null,
        'locLabel' => null,
        'name' => null,
        'externalLocationId' => null,
        'detailedAddress' => null,
        'city' => null,
        'access' => null,
        'geometry' => null,
        'externalInfo' => null,
        'country' => null,
        'freetext' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'locID' => false,
        'locLabel' => false,
        'name' => false,
        'externalLocationId' => false,
        'detailedAddress' => false,
        'city' => false,
        'access' => false,
        'geometry' => false,
        'externalInfo' => false,
        'country' => false,
        'freetext' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'locID' => 'locID',
        'locLabel' => 'locLabel',
        'name' => 'name',
        'externalLocationId' => 'externalLocationId',
        'detailedAddress' => 'detailedAddress',
        'city' => 'city',
        'access' => 'access',
        'geometry' => 'geometry',
        'externalInfo' => 'externalInfo',
        'country' => 'country',
        'freetext' => 'freetext'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'locID' => 'setLocID',
        'locLabel' => 'setLocLabel',
        'name' => 'setName',
        'externalLocationId' => 'setExternalLocationId',
        'detailedAddress' => 'setDetailedAddress',
        'city' => 'setCity',
        'access' => 'setAccess',
        'geometry' => 'setGeometry',
        'externalInfo' => 'setExternalInfo',
        'country' => 'setCountry',
        'freetext' => 'setFreetext'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'locID' => 'getLocID',
        'locLabel' => 'getLocLabel',
        'name' => 'getName',
        'externalLocationId' => 'getExternalLocationId',
        'detailedAddress' => 'getDetailedAddress',
        'city' => 'getCity',
        'access' => 'getAccess',
        'geometry' => 'getGeometry',
        'externalInfo' => 'getExternalInfo',
        'country' => 'getCountry',
        'freetext' => 'getFreetext'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const COUNTRY_AF = 'AF';
    public const COUNTRY_AX = 'AX';
    public const COUNTRY_AL = 'AL';
    public const COUNTRY_DZ = 'DZ';
    public const COUNTRY__AS = 'AS';
    public const COUNTRY_AD = 'AD';
    public const COUNTRY_AO = 'AO';
    public const COUNTRY_AI = 'AI';
    public const COUNTRY_AQ = 'AQ';
    public const COUNTRY_AG = 'AG';
    public const COUNTRY_AR = 'AR';
    public const COUNTRY_AM = 'AM';
    public const COUNTRY_AW = 'AW';
    public const COUNTRY_AU = 'AU';
    public const COUNTRY_AT = 'AT';
    public const COUNTRY_AZ = 'AZ';
    public const COUNTRY_BS = 'BS';
    public const COUNTRY_BH = 'BH';
    public const COUNTRY_BD = 'BD';
    public const COUNTRY_BB = 'BB';
    public const COUNTRY_BY = 'BY';
    public const COUNTRY_BE = 'BE';
    public const COUNTRY_BZ = 'BZ';
    public const COUNTRY_BJ = 'BJ';
    public const COUNTRY_BM = 'BM';
    public const COUNTRY_BT = 'BT';
    public const COUNTRY_BO = 'BO';
    public const COUNTRY_BA = 'BA';
    public const COUNTRY_BW = 'BW';
    public const COUNTRY_BV = 'BV';
    public const COUNTRY_BR = 'BR';
    public const COUNTRY_IO = 'IO';
    public const COUNTRY_BN = 'BN';
    public const COUNTRY_BG = 'BG';
    public const COUNTRY_BF = 'BF';
    public const COUNTRY_BI = 'BI';
    public const COUNTRY_CV = 'CV';
    public const COUNTRY_KH = 'KH';
    public const COUNTRY_CM = 'CM';
    public const COUNTRY_CA = 'CA';
    public const COUNTRY_KY = 'KY';
    public const COUNTRY_CF = 'CF';
    public const COUNTRY_TD = 'TD';
    public const COUNTRY_CL = 'CL';
    public const COUNTRY_CN = 'CN';
    public const COUNTRY_CX = 'CX';
    public const COUNTRY_CC = 'CC';
    public const COUNTRY_CO = 'CO';
    public const COUNTRY_KM = 'KM';
    public const COUNTRY_CG = 'CG';
    public const COUNTRY_CK = 'CK';
    public const COUNTRY_CR = 'CR';
    public const COUNTRY_CI = 'CI';
    public const COUNTRY_HR = 'HR';
    public const COUNTRY_CU = 'CU';
    public const COUNTRY_CW = 'CW';
    public const COUNTRY_CY = 'CY';
    public const COUNTRY_CZ = 'CZ';
    public const COUNTRY_DK = 'DK';
    public const COUNTRY_DJ = 'DJ';
    public const COUNTRY_DM = 'DM';
    public const COUNTRY__DO = 'DO';
    public const COUNTRY_EC = 'EC';
    public const COUNTRY_EG = 'EG';
    public const COUNTRY_SV = 'SV';
    public const COUNTRY_GQ = 'GQ';
    public const COUNTRY_ER = 'ER';
    public const COUNTRY_EE = 'EE';
    public const COUNTRY_SZ = 'SZ';
    public const COUNTRY_ET = 'ET';
    public const COUNTRY_FK = 'FK';
    public const COUNTRY_FO = 'FO';
    public const COUNTRY_FJ = 'FJ';
    public const COUNTRY_FI = 'FI';
    public const COUNTRY_FR = 'FR';
    public const COUNTRY_GF = 'GF';
    public const COUNTRY_PF = 'PF';
    public const COUNTRY_TF = 'TF';
    public const COUNTRY_GA = 'GA';
    public const COUNTRY_GM = 'GM';
    public const COUNTRY_GE = 'GE';
    public const COUNTRY_DE = 'DE';
    public const COUNTRY_GH = 'GH';
    public const COUNTRY_GI = 'GI';
    public const COUNTRY_GR = 'GR';
    public const COUNTRY_GL = 'GL';
    public const COUNTRY_GD = 'GD';
    public const COUNTRY_GP = 'GP';
    public const COUNTRY_GU = 'GU';
    public const COUNTRY_GT = 'GT';
    public const COUNTRY_GG = 'GG';
    public const COUNTRY_GN = 'GN';
    public const COUNTRY_GW = 'GW';
    public const COUNTRY_GY = 'GY';
    public const COUNTRY_HT = 'HT';
    public const COUNTRY_HM = 'HM';
    public const COUNTRY_VA = 'VA';
    public const COUNTRY_HN = 'HN';
    public const COUNTRY_HK = 'HK';
    public const COUNTRY_HU = 'HU';
    public const COUNTRY_IS = 'IS';
    public const COUNTRY_IN = 'IN';
    public const COUNTRY_ID = 'ID';
    public const COUNTRY_IR = 'IR';
    public const COUNTRY_IQ = 'IQ';
    public const COUNTRY_IE = 'IE';
    public const COUNTRY_IM = 'IM';
    public const COUNTRY_IL = 'IL';
    public const COUNTRY_IT = 'IT';
    public const COUNTRY_JM = 'JM';
    public const COUNTRY_JP = 'JP';
    public const COUNTRY_JE = 'JE';
    public const COUNTRY_JO = 'JO';
    public const COUNTRY_KZ = 'KZ';
    public const COUNTRY_KE = 'KE';
    public const COUNTRY_KI = 'KI';
    public const COUNTRY_KP = 'KP';
    public const COUNTRY_KW = 'KW';
    public const COUNTRY_KG = 'KG';
    public const COUNTRY_LA = 'LA';
    public const COUNTRY_LV = 'LV';
    public const COUNTRY_LB = 'LB';
    public const COUNTRY_LS = 'LS';
    public const COUNTRY_LR = 'LR';
    public const COUNTRY_LY = 'LY';
    public const COUNTRY_LI = 'LI';
    public const COUNTRY_LT = 'LT';
    public const COUNTRY_LU = 'LU';
    public const COUNTRY_MO = 'MO';
    public const COUNTRY_MG = 'MG';
    public const COUNTRY_MW = 'MW';
    public const COUNTRY_MY = 'MY';
    public const COUNTRY_MV = 'MV';
    public const COUNTRY_ML = 'ML';
    public const COUNTRY_MT = 'MT';
    public const COUNTRY_MH = 'MH';
    public const COUNTRY_MQ = 'MQ';
    public const COUNTRY_MR = 'MR';
    public const COUNTRY_MU = 'MU';
    public const COUNTRY_YT = 'YT';
    public const COUNTRY_MX = 'MX';
    public const COUNTRY_FM = 'FM';
    public const COUNTRY_MC = 'MC';
    public const COUNTRY_MN = 'MN';
    public const COUNTRY_ME = 'ME';
    public const COUNTRY_MS = 'MS';
    public const COUNTRY_MA = 'MA';
    public const COUNTRY_MZ = 'MZ';
    public const COUNTRY_MM = 'MM';
    public const COUNTRY_NA = 'NA';
    public const COUNTRY_NR = 'NR';
    public const COUNTRY_NP = 'NP';
    public const COUNTRY_NL = 'NL';
    public const COUNTRY_NC = 'NC';
    public const COUNTRY_NZ = 'NZ';
    public const COUNTRY_NI = 'NI';
    public const COUNTRY_NE = 'NE';
    public const COUNTRY_NG = 'NG';
    public const COUNTRY_NU = 'NU';
    public const COUNTRY_NF = 'NF';
    public const COUNTRY_MK = 'MK';
    public const COUNTRY_MP = 'MP';
    public const COUNTRY_NO = 'NO';
    public const COUNTRY_OM = 'OM';
    public const COUNTRY_PK = 'PK';
    public const COUNTRY_PW = 'PW';
    public const COUNTRY_PA = 'PA';
    public const COUNTRY_PG = 'PG';
    public const COUNTRY_PY = 'PY';
    public const COUNTRY_PE = 'PE';
    public const COUNTRY_PH = 'PH';
    public const COUNTRY_PN = 'PN';
    public const COUNTRY_PL = 'PL';
    public const COUNTRY_PT = 'PT';
    public const COUNTRY_PR = 'PR';
    public const COUNTRY_QA = 'QA';
    public const COUNTRY_RE = 'RE';
    public const COUNTRY_RO = 'RO';
    public const COUNTRY_RU = 'RU';
    public const COUNTRY_RW = 'RW';
    public const COUNTRY_BL = 'BL';
    public const COUNTRY_KN = 'KN';
    public const COUNTRY_LC = 'LC';
    public const COUNTRY_MF = 'MF';
    public const COUNTRY_PM = 'PM';
    public const COUNTRY_VC = 'VC';
    public const COUNTRY_WS = 'WS';
    public const COUNTRY_SM = 'SM';
    public const COUNTRY_ST = 'ST';
    public const COUNTRY_SA = 'SA';
    public const COUNTRY_SN = 'SN';
    public const COUNTRY_RS = 'RS';
    public const COUNTRY_SC = 'SC';
    public const COUNTRY_SL = 'SL';
    public const COUNTRY_SG = 'SG';
    public const COUNTRY_SX = 'SX';
    public const COUNTRY_SK = 'SK';
    public const COUNTRY_SI = 'SI';
    public const COUNTRY_SB = 'SB';
    public const COUNTRY_SO = 'SO';
    public const COUNTRY_ZA = 'ZA';
    public const COUNTRY_GS = 'GS';
    public const COUNTRY_SS = 'SS';
    public const COUNTRY_ES = 'ES';
    public const COUNTRY_LK = 'LK';
    public const COUNTRY_SD = 'SD';
    public const COUNTRY_SR = 'SR';
    public const COUNTRY_SJ = 'SJ';
    public const COUNTRY_SE = 'SE';
    public const COUNTRY_CH = 'CH';
    public const COUNTRY_SY = 'SY';
    public const COUNTRY_TJ = 'TJ';
    public const COUNTRY_TH = 'TH';
    public const COUNTRY_TL = 'TL';
    public const COUNTRY_TG = 'TG';
    public const COUNTRY_TK = 'TK';
    public const COUNTRY_TO = 'TO';
    public const COUNTRY_TT = 'TT';
    public const COUNTRY_TN = 'TN';
    public const COUNTRY_TR = 'TR';
    public const COUNTRY_TM = 'TM';
    public const COUNTRY_TC = 'TC';
    public const COUNTRY_TV = 'TV';
    public const COUNTRY_UG = 'UG';
    public const COUNTRY_UA = 'UA';
    public const COUNTRY_AE = 'AE';
    public const COUNTRY_GB = 'GB';
    public const COUNTRY_US = 'US';
    public const COUNTRY_UM = 'UM';
    public const COUNTRY_UY = 'UY';
    public const COUNTRY_UZ = 'UZ';
    public const COUNTRY_VU = 'VU';
    public const COUNTRY_VE = 'VE';
    public const COUNTRY_VN = 'VN';
    public const COUNTRY_VG = 'VG';
    public const COUNTRY_VI = 'VI';
    public const COUNTRY_WF = 'WF';
    public const COUNTRY_EH = 'EH';
    public const COUNTRY_YE = 'YE';
    public const COUNTRY_ZM = 'ZM';
    public const COUNTRY_ZW = 'ZW';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCountryAllowableValues()
    {
        return [
            self::COUNTRY_AF,
            self::COUNTRY_AX,
            self::COUNTRY_AL,
            self::COUNTRY_DZ,
            self::COUNTRY__AS,
            self::COUNTRY_AD,
            self::COUNTRY_AO,
            self::COUNTRY_AI,
            self::COUNTRY_AQ,
            self::COUNTRY_AG,
            self::COUNTRY_AR,
            self::COUNTRY_AM,
            self::COUNTRY_AW,
            self::COUNTRY_AU,
            self::COUNTRY_AT,
            self::COUNTRY_AZ,
            self::COUNTRY_BS,
            self::COUNTRY_BH,
            self::COUNTRY_BD,
            self::COUNTRY_BB,
            self::COUNTRY_BY,
            self::COUNTRY_BE,
            self::COUNTRY_BZ,
            self::COUNTRY_BJ,
            self::COUNTRY_BM,
            self::COUNTRY_BT,
            self::COUNTRY_BO,
            self::COUNTRY_BA,
            self::COUNTRY_BW,
            self::COUNTRY_BV,
            self::COUNTRY_BR,
            self::COUNTRY_IO,
            self::COUNTRY_BN,
            self::COUNTRY_BG,
            self::COUNTRY_BF,
            self::COUNTRY_BI,
            self::COUNTRY_CV,
            self::COUNTRY_KH,
            self::COUNTRY_CM,
            self::COUNTRY_CA,
            self::COUNTRY_KY,
            self::COUNTRY_CF,
            self::COUNTRY_TD,
            self::COUNTRY_CL,
            self::COUNTRY_CN,
            self::COUNTRY_CX,
            self::COUNTRY_CC,
            self::COUNTRY_CO,
            self::COUNTRY_KM,
            self::COUNTRY_CG,
            self::COUNTRY_CK,
            self::COUNTRY_CR,
            self::COUNTRY_CI,
            self::COUNTRY_HR,
            self::COUNTRY_CU,
            self::COUNTRY_CW,
            self::COUNTRY_CY,
            self::COUNTRY_CZ,
            self::COUNTRY_DK,
            self::COUNTRY_DJ,
            self::COUNTRY_DM,
            self::COUNTRY__DO,
            self::COUNTRY_EC,
            self::COUNTRY_EG,
            self::COUNTRY_SV,
            self::COUNTRY_GQ,
            self::COUNTRY_ER,
            self::COUNTRY_EE,
            self::COUNTRY_SZ,
            self::COUNTRY_ET,
            self::COUNTRY_FK,
            self::COUNTRY_FO,
            self::COUNTRY_FJ,
            self::COUNTRY_FI,
            self::COUNTRY_FR,
            self::COUNTRY_GF,
            self::COUNTRY_PF,
            self::COUNTRY_TF,
            self::COUNTRY_GA,
            self::COUNTRY_GM,
            self::COUNTRY_GE,
            self::COUNTRY_DE,
            self::COUNTRY_GH,
            self::COUNTRY_GI,
            self::COUNTRY_GR,
            self::COUNTRY_GL,
            self::COUNTRY_GD,
            self::COUNTRY_GP,
            self::COUNTRY_GU,
            self::COUNTRY_GT,
            self::COUNTRY_GG,
            self::COUNTRY_GN,
            self::COUNTRY_GW,
            self::COUNTRY_GY,
            self::COUNTRY_HT,
            self::COUNTRY_HM,
            self::COUNTRY_VA,
            self::COUNTRY_HN,
            self::COUNTRY_HK,
            self::COUNTRY_HU,
            self::COUNTRY_IS,
            self::COUNTRY_IN,
            self::COUNTRY_ID,
            self::COUNTRY_IR,
            self::COUNTRY_IQ,
            self::COUNTRY_IE,
            self::COUNTRY_IM,
            self::COUNTRY_IL,
            self::COUNTRY_IT,
            self::COUNTRY_JM,
            self::COUNTRY_JP,
            self::COUNTRY_JE,
            self::COUNTRY_JO,
            self::COUNTRY_KZ,
            self::COUNTRY_KE,
            self::COUNTRY_KI,
            self::COUNTRY_KP,
            self::COUNTRY_KW,
            self::COUNTRY_KG,
            self::COUNTRY_LA,
            self::COUNTRY_LV,
            self::COUNTRY_LB,
            self::COUNTRY_LS,
            self::COUNTRY_LR,
            self::COUNTRY_LY,
            self::COUNTRY_LI,
            self::COUNTRY_LT,
            self::COUNTRY_LU,
            self::COUNTRY_MO,
            self::COUNTRY_MG,
            self::COUNTRY_MW,
            self::COUNTRY_MY,
            self::COUNTRY_MV,
            self::COUNTRY_ML,
            self::COUNTRY_MT,
            self::COUNTRY_MH,
            self::COUNTRY_MQ,
            self::COUNTRY_MR,
            self::COUNTRY_MU,
            self::COUNTRY_YT,
            self::COUNTRY_MX,
            self::COUNTRY_FM,
            self::COUNTRY_MC,
            self::COUNTRY_MN,
            self::COUNTRY_ME,
            self::COUNTRY_MS,
            self::COUNTRY_MA,
            self::COUNTRY_MZ,
            self::COUNTRY_MM,
            self::COUNTRY_NA,
            self::COUNTRY_NR,
            self::COUNTRY_NP,
            self::COUNTRY_NL,
            self::COUNTRY_NC,
            self::COUNTRY_NZ,
            self::COUNTRY_NI,
            self::COUNTRY_NE,
            self::COUNTRY_NG,
            self::COUNTRY_NU,
            self::COUNTRY_NF,
            self::COUNTRY_MK,
            self::COUNTRY_MP,
            self::COUNTRY_NO,
            self::COUNTRY_OM,
            self::COUNTRY_PK,
            self::COUNTRY_PW,
            self::COUNTRY_PA,
            self::COUNTRY_PG,
            self::COUNTRY_PY,
            self::COUNTRY_PE,
            self::COUNTRY_PH,
            self::COUNTRY_PN,
            self::COUNTRY_PL,
            self::COUNTRY_PT,
            self::COUNTRY_PR,
            self::COUNTRY_QA,
            self::COUNTRY_RE,
            self::COUNTRY_RO,
            self::COUNTRY_RU,
            self::COUNTRY_RW,
            self::COUNTRY_BL,
            self::COUNTRY_KN,
            self::COUNTRY_LC,
            self::COUNTRY_MF,
            self::COUNTRY_PM,
            self::COUNTRY_VC,
            self::COUNTRY_WS,
            self::COUNTRY_SM,
            self::COUNTRY_ST,
            self::COUNTRY_SA,
            self::COUNTRY_SN,
            self::COUNTRY_RS,
            self::COUNTRY_SC,
            self::COUNTRY_SL,
            self::COUNTRY_SG,
            self::COUNTRY_SX,
            self::COUNTRY_SK,
            self::COUNTRY_SI,
            self::COUNTRY_SB,
            self::COUNTRY_SO,
            self::COUNTRY_ZA,
            self::COUNTRY_GS,
            self::COUNTRY_SS,
            self::COUNTRY_ES,
            self::COUNTRY_LK,
            self::COUNTRY_SD,
            self::COUNTRY_SR,
            self::COUNTRY_SJ,
            self::COUNTRY_SE,
            self::COUNTRY_CH,
            self::COUNTRY_SY,
            self::COUNTRY_TJ,
            self::COUNTRY_TH,
            self::COUNTRY_TL,
            self::COUNTRY_TG,
            self::COUNTRY_TK,
            self::COUNTRY_TO,
            self::COUNTRY_TT,
            self::COUNTRY_TN,
            self::COUNTRY_TR,
            self::COUNTRY_TM,
            self::COUNTRY_TC,
            self::COUNTRY_TV,
            self::COUNTRY_UG,
            self::COUNTRY_UA,
            self::COUNTRY_AE,
            self::COUNTRY_GB,
            self::COUNTRY_US,
            self::COUNTRY_UM,
            self::COUNTRY_UY,
            self::COUNTRY_UZ,
            self::COUNTRY_VU,
            self::COUNTRY_VE,
            self::COUNTRY_VN,
            self::COUNTRY_VG,
            self::COUNTRY_VI,
            self::COUNTRY_WF,
            self::COUNTRY_EH,
            self::COUNTRY_YE,
            self::COUNTRY_ZM,
            self::COUNTRY_ZW,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('locID', $data ?? [], null);
        $this->setIfExists('locLabel', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('externalLocationId', $data ?? [], null);
        $this->setIfExists('detailedAddress', $data ?? [], null);
        $this->setIfExists('city', $data ?? [], null);
        $this->setIfExists('access', $data ?? [], null);
        $this->setIfExists('geometry', $data ?? [], null);
        $this->setIfExists('externalInfo', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('freetext', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['locID'] === null) {
            $invalidProperties[] = "'locID' can't be null";
        }
        if ($this->container['country'] === null) {
            $invalidProperties[] = "'country' can't be null";
        }
        $allowedValues = $this->getCountryAllowableValues();
        if (!is_null($this->container['country']) && !in_array($this->container['country'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'country', must be one of '%s'",
                $this->container['country'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets locID
     *
     * @return string
     */
    public function getLocID()
    {
        return $this->container['locID'];
    }

    /**
     * Sets locID
     *
     * @param string $locID ID technique et provisoire permettant d'identifier le lieu dans le cadre des échanges de cette affaire.
     *
     * @return self
     */
    public function setLocID($locID)
    {
        if (is_null($locID)) {
            throw new \InvalidArgumentException('non-nullable locID cannot be null');
        }
        $this->container['locID'] = $locID;

        return $this;
    }

    /**
     * Gets locLabel
     *
     * @return string|null
     */
    public function getLocLabel()
    {
        return $this->container['locLabel'];
    }

    /**
     * Sets locLabel
     *
     * @param string|null $locLabel Donne les informations minimales d'identification du lieu d'intervention, qui permet d'identifier rapidement le lieu pour les équipes opérationnelles. Comprend au maximum 255 caractères. 15-18 : Dans les messages NexSIS, va souvent correspondre à la concaténation suivant des règles métiers de différentes informations, dont le \"name\" (toponyme) et l'adresse.
     *
     * @return self
     */
    public function setLocLabel($locLabel)
    {
        if (is_null($locLabel)) {
            throw new \InvalidArgumentException('non-nullable locLabel cannot be null');
        }
        $this->container['locLabel'] = $locLabel;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name A valoriser avec le nom de lieu : nom commercial, nom d'établissement, forêt de Fontainebleau, lac du Der, etc.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets externalLocationId
     *
     * @return \Hubsante\Model\cisu\ExternalLocationId[]|null
     */
    public function getExternalLocationId()
    {
        return $this->container['externalLocationId'];
    }

    /**
     * Sets externalLocationId
     *
     * @param \Hubsante\Model\cisu\ExternalLocationId[]|null $externalLocationId externalLocationId
     *
     * @return self
     */
    public function setExternalLocationId($externalLocationId)
    {
        if (is_null($externalLocationId)) {
            throw new \InvalidArgumentException('non-nullable externalLocationId cannot be null');
        }
        $this->container['externalLocationId'] = $externalLocationId;

        return $this;
    }

    /**
     * Gets detailedAddress
     *
     * @return \Hubsante\Model\cisu\DetailedAddress|null
     */
    public function getDetailedAddress()
    {
        return $this->container['detailedAddress'];
    }

    /**
     * Sets detailedAddress
     *
     * @param \Hubsante\Model\cisu\DetailedAddress|null $detailedAddress detailedAddress
     *
     * @return self
     */
    public function setDetailedAddress($detailedAddress)
    {
        if (is_null($detailedAddress)) {
            throw new \InvalidArgumentException('non-nullable detailedAddress cannot be null');
        }
        $this->container['detailedAddress'] = $detailedAddress;

        return $this;
    }

    /**
     * Gets city
     *
     * @return \Hubsante\Model\cisu\City|null
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param \Hubsante\Model\cisu\City|null $city city
     *
     * @return self
     */
    public function setCity($city)
    {
        if (is_null($city)) {
            throw new \InvalidArgumentException('non-nullable city cannot be null');
        }
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets access
     *
     * @return \Hubsante\Model\cisu\Access|null
     */
    public function getAccess()
    {
        return $this->container['access'];
    }

    /**
     * Sets access
     *
     * @param \Hubsante\Model\cisu\Access|null $access access
     *
     * @return self
     */
    public function setAccess($access)
    {
        if (is_null($access)) {
            throw new \InvalidArgumentException('non-nullable access cannot be null');
        }
        $this->container['access'] = $access;

        return $this;
    }

    /**
     * Gets geometry
     *
     * @return \Hubsante\Model\cisu\Geometry|null
     */
    public function getGeometry()
    {
        return $this->container['geometry'];
    }

    /**
     * Sets geometry
     *
     * @param \Hubsante\Model\cisu\Geometry|null $geometry geometry
     *
     * @return self
     */
    public function setGeometry($geometry)
    {
        if (is_null($geometry)) {
            throw new \InvalidArgumentException('non-nullable geometry cannot be null');
        }
        $this->container['geometry'] = $geometry;

        return $this;
    }

    /**
     * Gets externalInfo
     *
     * @return \Hubsante\Model\cisu\ExternalInfo[]|null
     */
    public function getExternalInfo()
    {
        return $this->container['externalInfo'];
    }

    /**
     * Sets externalInfo
     *
     * @param \Hubsante\Model\cisu\ExternalInfo[]|null $externalInfo externalInfo
     *
     * @return self
     */
    public function setExternalInfo($externalInfo)
    {
        if (is_null($externalInfo)) {
            throw new \InvalidArgumentException('non-nullable externalInfo cannot be null');
        }
        $this->container['externalInfo'] = $externalInfo;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $allowedValues = $this->getCountryAllowableValues();
        if (!in_array($country, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'country', must be one of '%s'",
                    $country,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets freetext
     *
     * @return string|null
     */
    public function getFreetext()
    {
        return $this->container['freetext'];
    }

    /**
     * Sets freetext
     *
     * @param string|null $freetext Champ libre qui permet de compléter les informations liées à la localisation.  Spécificités 15-15 : En envoi, il est souhaitable de mapper ici toute valeur en lien avec la localisation de l'intervention qui ne pourrait pas être transmise de manière structurée dans l'objet location.  En réception, il est très important d'intégrer et d'afficher la valeur de cet attribut, qui est suceptible de contenir des informations d'accès importantes.
     *
     * @return self
     */
    public function setFreetext($freetext)
    {
        if (is_null($freetext)) {
            throw new \InvalidArgumentException('non-nullable freetext cannot be null');
        }
        $this->container['freetext'] = $freetext;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


