name: Generate test cases

# Allow workflow to be triggered by another workflow: https://docs.github.com/en/actions/sharing-automations/reusing-workflows#creating-a-reusable-workflow
on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run csv_parser and collect OpenAPI & JSON Schemas
        working-directory: ./csv_parser
        run: python workflow.py --stage parser_and_mv

      - name: Run test_case_generator
        working-directory: ./csv_parser
        run: |
          rm -r ./out/test-cases || true
          python workflow.py --stage test_case_parser
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ⚙️ Auto-génération des cas de test