name: old-generate-sdks

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

env:
  SCHEMAS: "RC-EDA RS-EDA EMSI GEO-POS GEO-REQ GEO-RES RC-REF RS-ERROR RS-RI RS-DR RS-RR RPIS"

jobs:
  old-generate-sdks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install openapi-generator-cli
        run: npm install -g @openapitools/openapi-generator-cli

      - name: Cleaning output directories
        working-directory: ./generator
        run: |
          rm -r ruby python csharp || true

      - name: Generate Ruby classes
        working-directory: ./generator
        run: |
          npx @openapitools/openapi-generator-cli generate -c ./config/EDXL-DE/ruby/EDXL-DE.generator-config.json --skip-validate-spec

          IFS=' ' read -ra SCHEMAS_ARRAY <<< "$SCHEMAS"
          for SCHEMA in "${SCHEMAS_ARRAY[@]}"; do
            npx @openapitools/openapi-generator-cli generate -c ./config/$SCHEMA/ruby/$SCHEMA.generator-config.json --skip-validate-spec
          done

      - name: Generate Python classes
        working-directory: ./generator
        run: |
          npx @openapitools/openapi-generator-cli generate -c ./config/RS-EDA/python/RS-EDA.generator-config.json --skip-validate-spec

      - name: Generate C# classes
        working-directory: ./generator
        run: |
          npx @openapitools/openapi-generator-cli generate -c ./config/RS-EDA/csharp/RS-EDA.generator-config.json --skip-validate-spec

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ⚙️ Auto-génération des classes et des specs